CartoDB/carto.js

doc/raster_howto.md
examples/leaflet_raster.html
src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

Hey @rochoa take a look.
the way to create a raster thing is: 
```
cartodb.createLayer(map, {
user_name: 'dev',
type: 'cartodb',
sublayers: [{
sql: 'select * from pop',
cartocss: '#pop { raster-opacity: 1.0; }',
raster: true,
}],
})
```
I don't know if use ``raster: true`` or just ``geom_type: 'raster'`` what do you think ?

adds raster support

---

src/vis/vis.js
test/spec/api/layers.spec.js

From an updated branch (develop). (It came from PR 280)
Tests added.
Also, in the example given in the issue, the time steps are: 0.5
Because of that, the condition is greather than 1 (instead of !== 1)

Fix not showing time slider if steps aren't > 1

---

src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

when we had:
``` 
cartodb.createLayer(map, {
user_name: 'andye',
type: 'namedmap',
named_map: {
name: "namedmap_ex_test_interactive"
}
})
.addTo(map)
.done(function(layer) {
layer.getSubLayer(0).setInteraction(true)
layer.getSubLayer(0).on('featureOver', function(e, pos, pixel, data) {
console.log("Event #" + data.cartodb_id + ", magnitude " + data.mag);
// alert("Event #" + data.cartodb_id + ", magnitude " + data.mag);
});
})
```
this was failing because with named maps we don't know client side how many layers are. I fixed this assuming the user knows it and adding client side the objects needed to deal with those layers

fixes getSubLayer for named maps, fixes #158

---

examples/images/basemap.html
examples/images/core.html
examples/images/format.html
examples/images/index.html
examples/images/plain-color.html
examples/images/single-image.html
examples/images/torque.html
grunt/tasks/concat.js
grunt/tasks/jasmine.js
src/api/layers.js
src/cartodb.js
src/core/loader.js
src/vis/image.js
src/vis/vis.js
test/SpecRunner.html
test/spec/api/layers.spec.js
test/spec/core/image.spec.js

This branch:
- Removes the backbone dependency from the Image library.
- Extracts the Loader into its own file (cdb.vis.Loader → cdb.core.Loader)
- Adds a new example that only uses cartodb.core.js
- Update specs.
Extra stuff:
- Allows to specify a custom basemap (see [example/images/basemap.html](https://github.com/CartoDB/cartodb.js/blob/fd15b4c597985f14a94b5936cb20a11962ad594e/examples/images/basemap.html))
- Adds support for Plain basemaps.
- Adds vis namespace to Loader: cdb.vis.Loader = cdb.core.Loader
/cc @javisantana

Image core

---

.gitignore

At least when building CartoDB with `grunt` this is a bit of a pain for switching branches and some other git operations.
@javierarce can you please review and merge? thanks!

Add generated css to .gitignore

---

src/vis/image.js
test/spec/core/image.spec.js

We now support to force the `https` protocol via param: 
```var image = cartodb.Image(vizjson, { https: true }).size(400, 300);```
@javisantana or @CartoDB/frontend: can you review it, please?

Allows to force the https protocol via param

---

examples/images/basemap.html
examples/images/core.html
examples/images/format.html
examples/images/image.html
examples/images/layer_definition.html
examples/images/plain-color.html
examples/images/torque.html
src/vis/image.js
test/SpecRunner.html
test/spec/core/image.spec.js

We weren't getting the correct type from the basemap, and as a result the "plain static maps" (as in a map with one plain color as the basemap) weren't getting generated.
Could you please review it, @javisantana, @CartoDB/frontend?

Fixes generating a static map with a plain layer 

---

grunt/tasks/s3.js

It basically uses the same way we do with JS or CSS. It checks if the version is prerelease and in that case, minor files won't be uploaded.
Example:
http://libs.cartocdn.com.s3.amazonaws.com/cartodb.js/v5/5.0.0-beta/themes/img/dark_loader.gif
http://libs.cartocdn.com.s3.amazonaws.com/cartodb.js/v5/5.0/themes/img/dark_loader.gif
cc @CartoDB/frontend

It won't overwrite images in production when version is prerelease

---

src/geo/ui/legend.js
test/spec/geo/legend.spec.js

Ref. CartoDB/cartodb#1944
Basically the template checks for falsy values for name when making the legends' html. As 0 is a falsy value (```0 == false``` is true, god bless javascript ;) ), is was adding its label as ```NULL```. This makes sure that non-string values (in this case, numbers) are turned into strings before passing them to the template (```"0" == false``` is false).
@xavijam CR please? :) 
cc @ohasselblad

Makes sure values named zero are not legended as NULL

---

NEWS
examples/images/torque.html
src/vis/image.js
test/spec/core/image.spec.js

This PR adds:
- A new method (`_getTorqueLayerDefinition`) to generate basemaps of vizjsons with one torque layer.
- A spec for that case.
- Updates the torque example.

Fixes error generating a map preview for torque layers

---

doc/API.md

Searchbox options argument appears to have changed. Also appears to default to 'true'.

`searchControl` has changed to `search` in createVis options hash

---

src/geo/leaflet/leaflet_cartodb_layergroup.js

Ref. #333
Coordinates of the return value of ```findPos()``` were ```NaN``` when passing a touch event on a map in fixed position. Using x and y as a fallback when clientX/clientY are undefined solves this.
@xavijam

Properly generates leaflet point for touch events

---

src/vis/image.js
test/spec/core/image.spec.js

We [check](https://github.com/CartoDB/cartodb.js/pull/356/files#diff-e14eff99e7c7b57af717eedd1f3cc9d2R153) if the vizjson contains a named map and torque layer with a named map inside. If that's the case, we don't send the torque layer in the request.

Fixes tiler request when the vizjson contains a named map and a torque layer with a named map

---

src/geo/gmaps/gmaps_cartodb_layergroup.js
vendor/wax.cartodb.js

Updating wax.cartodb.js
This commit fixes the following issues:
- #346 : Dragging the map triggers the info window
- #313 : Pan/Zoom event don’t work as appropriate on touch-screen
Windows 8
- #223 : Pointer events in IE11 on touch-screen Windows laptops do not
trigger popups
- #139: Layer interaciton in IE10/IE11 not working when dragging a
leaflet marker
*Note:* The [PR 334](https://github.com/CartoDB/cartodb.js/pull/334) is included here because I tested all the fixes together (because of IE 11 mobile case)

Wax pr6 updating wax.cartodb.js - IE, gmaps and mobile issues

---

src/geo/gmaps/gmaps_cartodb_layergroup.js

Related ticket: https://github.com/CartoDB/cartodb.js/issues/313
Click event and its infowindows wasn’t being triggered with Internet Explore
Mobile and GMaps.
It was working with Leaflet maps, and the reason was that in
leaflet_cartodb_leaflet.js file it has the ‘case:’ like in this commit.
Also, I've added a condition in the other *if* because it was returning some errors when I was debugging with MS Visual Studio. It's protecting if the properties clientX and clientY aren't defined in o.e.changedTouches[0]

Fix GMaps and IEMobile click event:

---

src/vis/image.js
test/spec/core/image.spec.js

This PR adds a new user option (`override_bbox`) that allows to override the default use of the bounding box to generate the image, using the center instead.
Plus: [wiki updated](https://github.com/CartoDB/cartodb.js/wiki/CartoDB-Map-API#override_bbox).
@CartoDB/frontend / @javisantana: review this, please :)

Allows to override the bbox

---

src/vis/image.js
test/spec/core/image.spec.js

This PR fixes a problem where images were being generated using all the layers. We now only use the visible ones.

Don't use the hidden layers to generate images

---

NEWS
src/vis/image.js
test/spec/core/image.spec.js

Right now we are using the default one, which works in production, but we need to use the one specified in the the vizjson so it works locally and in staging.

Extract the CDN host configuration from the vizjson

---

src/api/sql.js
test/spec/api/sql.spec.js

The explanation is in this [StackOverflow post](http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-so
metimes-useful) : 
Recaping: (there's a more large explanation in that post)
> what setTimeout does is add a new event to the browser event queue and the rendering engine is already in that queue (not entirely true, but close enough) so it gets executed before the setTimeout event. . 
Also, it was 'hard' to reproduce. I was using Windows 8.1 and InternetExplorer 11 **emulating IE 10**, but it was working correctly. So, I had to use a virtual machine from [modern.ie](https://www.modern.ie/) with Win8/IE10. There, I could reproduce the problem, but it wasn't happening always. I think that the Internet connection and speed in events are related.
Also, I've modified  the test …

Cdb-336_IE10 fails to load infowindow data thats already been viewed

---

src/vis/image.js
test/spec/core/image.spec.js

This will prevent an error generating images for Google Maps, for example. /cc @rochoa 
@CartoDB/frontend / @javisantana: can you :eyes: :pray:?

Don't send the urlTemplate if we don't have it

---

src/geo/layer_definition.js
src/vis/image.js
test/spec/geo/layer_definition.spec.js

Related to: https://github.com/CartoDB/cartodb-onpremise/issues/180
In some cases, the server could send an empty CDN config:
In this case, we should set the `no_cdn` flag to `false`, to avoid an [error in layer_definition.js](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L611)

Disables the CDN if the server doesn't send us the configuration

---

src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

We'll now trust the tiler and use whatever CDN configuration we get (or nothing, if `cdn_url` is empty).

Removes default CDN host

---

examples/annotations.html
examples/cursor_interaction.html
examples/easy.html
examples/gmaps/gmaps_driving_directions_plus_sql_api.html
examples/leaflet.html
examples/leaflet_hover_features.html
examples/tutorial-2.html
examples/tutorials/tutorial-2.html

Looks like the correct order is (e, latlong, pos, ...): http://docs.cartodb.com/cartodb-platform/cartodb-js.html#layerfeatureoverevent-latlng-pos-data-layerindex

docfix: pos and latlng order were switched in event callbacks in examples

---

src/vis/image.js
test/spec/core/image.spec.js

Please, see the description of the original issue: https://github.com/CartoDB/cartodb.js/issues/397
Basically, in the cases where we have a vizjson of a torque with a named map inside (= a torque that was created with a private table, for example) we need to use the named map to do the request.

Torque layer with named map must request the named map 

---

NEWS
src/geo/ui/fullscreen.js

Ref. [ticket #361](https://github.com/CartoDB/cartodb.js/issues/361) : **Full screen button not working on Safari 8.0.3**
This seems to be a Safari bug. In the ticket I pointed several references.
And, I've written this patch using [this reference](http://stackoverflow.com/questions/8427413/webkitrequestfull
screen-fails-when-passing-element-allow-keyboard-input-in-safar)  --> **...(/Safari/.test(navigator.userAgent) ? undefined : Element.ALLOW_KEYBOARD_INPUT)**
Because of that, I used *undefined* as parameter.
I tested it with Safari 8.0 (10600.1.25), Chrome (41.0.2272.76) and Firefox (35.0.1) in MacOS, and Chrome (Android-4.4) and it works ok.
Please, @javierarce , could you check it? Thanks!

Fix fullscreen in Safari

---

src/geo/ui/infowindow.js
test/spec/geo/infowindow.spec.js

This PR fixes cartodb/cartodb#2420.
I have modified `cdb.geo.ui.infowindow.contentForFields`, which is the function that generates the fields that will get rendered in tooltips and infowindows. After these changes, this function will only return empty fields, when `options.empty_fields` is set to true (something that only happens for tooltips in the editor).
I added some tests for it. 
@xavijam @javisantana PTAL

Handle null values in Infowindows and Tooltips

---

NEWS
src/geo/ui/fullscreen.js

Ref. ticket #412 : https://github.com/CartoDB/cartodb.js/issues/412
Track.js was reporting that the error was throw with the following info:
- Browser: Mobile Safari 8.0
- Operating System: iOS 8.2
A fullscreen action was being executed from a mobile device, so the option *force_mobile=false* would be necessary (thanks @xavijam ).
Indeed, I tried it with desktop (OS X 10.10.1) browsers (Chrome/Fixefox/Safari) and it worked. But, I [emulated](http://www.macinstruct.com/node/494) an iOS 8.1 and I was able to reproduce the error.
So, the issue is:
**Nowadays (2015/03/25), fullscreen is not supported in iOS Safari. [Reference](http://caniuse.com/#feat=fullscreen)**
With this patch, I'm avoiding the error messages. Also, I think that it would be better if we don't allow to put on screen the …

Cdb-412-Fullscreen button is throwing errors

---

vendor/mod/torque.uncompressed.js

@xavijam 
News since last update:
```
- Do not fix values in the edge (#147)
- Windshaft provider accepts an optional data type for coordinates (#149)
- Acceptance tests
- renderTile accepts a callback to be called when rendering finishes
- tile rendering deferred until all assets are loaded
- sprite rendering now scales source to marker dimensions
- Filters accept a canvas class
- Adjusted point position taking resolution into account
- Changed loop: false to pause animation at last frame
- On torque-frame-count: 1, always pause for better performance
- Fixes getTimeSpan
- Adds timetostep method to torque layer
- Function qualifyURL can be provided to not rely on document's one
```

Updates torque with version 2.11

---

src/vis/image.js
test/spec/core/image.spec.js

Password protected visualizations require to get an array with the `auth_tokens`. This PR solves that.
@javisantana: can you :eyes:, please?

Shows password protected visualizations

---

src/geo/ui/infowindow.js

While debugging the [issue with broken <img> that contained `&`s](https://github.com/CartoDB/cartodb/issues/3010) more thoroughly I found the real issue, infowindows are rendered differently in editor vs. using cartodb.js (why the images/URLs break only on embeds). 
The culprit is that [infowindow model's content fields are sanitized on update](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/ui/infowindow.js#L193), so these values will be double-escaped upon render (due to the default mustache template, i.e. `{{ img_url }}`). For the editor the code don't use this way of rendering so was just injected as-is.
With these changes the render is consistent for both the editor and cartodb.js usage by default, i.e. what the user sees in the editor is how it will look in the embed too.

Sanitize infowindow output on render only

---

themes/css/infowindow/cartodb-infowindow-default.css

This PR sets a default style for the title tags (h1-h6) of the infowindows.
Original issue: https://github.com/CartoDB/cartodb/issues/2876

Fixes title tags in the infowindows

---

src/vis/image.js
test/spec/core/image.spec.js

This PR removes the option to force the `https` protocol of a static map and fixes the specs accordingly (as in removing them completely)

We don't allow to force the https anymore. Removed unnecesary specs

---

src/geo/ui/time_slider.js
src/vis/overlays.js

Ref. #446 
Makes sure the timeslider is not templated in when the Torque map is static.
@ohasselblad @javisantana

Doesn't add timeslider with Torque static maps in mobile

---

NEWS
src/geo/leaflet/torque.js

Ref. https://github.com/CartoDB/torque/issues/164
Basically the loop attribute wasn't being passed on to the Torque layer from cartodb.js. 
@javisantana @ohasselblad

Fixes loop functionality with Torque from cdb.js

---

src/vis/image.js
test/spec/core/image.spec.js

`userOptions` wasn't defined for the `loadLayerDefinition`, so in some cases an exception was triggered.
Fixes: https://github.com/CartoDB/cartodb.js/issues/439

Defines userOptions for the layer_definition loader

---

src/vis/image.js
test/spec/core/image.spec.js

This PR adds the possibility to specify a `step` param to render a specific frame of a torque layer.
`cartodb.Image(vizjson, { step: 100 }).size(500, 500)`
Original issue: https://github.com/CartoDB/cartodb.js/issues/351. Related to: https://github.com/CartoDB/cartodb/issues/3268

Allows to specify a step for torque layers

---

doc/API.md

I was searching for the actual definition of ```vis.addInfoWindow``` in the cartodb.js source code after reading about it in the API docs but couldn't find anything with that name. Happens that the method itself is defined as ```addInfowindow``` and not ```addInfoWindow``` (notice the lower case w).

Fix vis.addInfowindow() method name in doc/API.md

---

src/geo/map.js
test/spec/geo/map.spec.js

This PR attempts to fix a problem that occurs when changing between basemaps with different zoom configurations.
See related issue: https://github.com/CartoDB/cartodb/issues/2250
`maxZoom` and `minZoom` get returned as a string (except in development, where they are returned as an integer), so the zoom is never correctly updated.

Fixes problems setting maxZoom and minZoom

---

NEWS
vendor/mod/torque.uncompressed.js

Changes since last replacement:
```
- Added error handling to Torque
- Fixed 'remove' event triggering when removing a Torque layer.
- Value is now capped at 255 instead of performing modulo on higher values.
```
@javierarce ;)

Updates version of Torque to 2.11.2

---

src/geo/ui/legend.js
test/spec/geo/legend.spec.js

This PR allows to specify a template for the items of a Custom Legend.
Related issue: https://github.com/CartoDB/cartodb.js/issues/109

Allows to specify a custom template for the custom legend items

---

grunt/tasks/concat.js
grunt/templates/torque_footer.js
grunt/templates/torque_header.js

Ref. #414 
A header in the Torque module of Cartodb.js that makes sure that the bundled version of jquery (1.7.2) is used, and not one specified in the DOM. Also, as in the visualisations without torque, it restores the user-specified version if there is any.
@javisantana

Uses internal version of jQuery in maps with Torque

---

NEWS
src/geo/ui/infowindow.js
test/spec/geo/ui/infowindow.spec.js

Fixes #461 (as [we did in CartoDB](https://github.com/CartoDB/cartodb/commit/331058ffdb4dbd5aa4a3b958504d0195c1769bf6)).
@xavijam please take a look.

Hide <img> tags in infowindow covers if url is invalid

---

NEWS
doc/API.md
src/geo/ui/legend.js
src/vis/vis.js
test/spec/api/layers/cartodb.spec.js
test/spec/geo/ui/legend.spec.js

This is part of #101. It exposes a legend model on layers/sublayers so that users can do some custom things, such us:
- Changing the template of the legend.
- Customizing the title of the legend.
- Showing/hiding the title of the legend.
- Getting/Setting the items that are displayed in the legend.
- Showing/hiding the legend.
@javisantana what do you think?

Expose legend model in layer views

---

NEWS
src/geo/ui/tooltip.js
src/vis/overlays.js
src/vis/vis.js
test/spec/geo/ui/tooltip.spec.js

Fixes #140.
Another ticket for @javisantana, since you wrote the original issue :stuck_out_tongue_winking_eye:

Handle tooltip overflow

---

NEWS
src/geo/ui/tooltip.js
test/spec/geo/ui/tooltip.spec.js

This fixes cartodb/cartodb#3617. The problems were:
1. There was a layer filled with features (timezones) on top of the map. So we were hovering a feature all the time.
2. We were adding the tooltip cause the other layer had a tooltip (with fields) and we were not checking if layers have fields in the tooltip when we enable.
This PR fixes that by preventing a tooltip from being shown if there are no fields.
cc// @javisantana

Prevent tooltips from being shown when no fields have been selected

---

NEWS
src/geo/ui/tooltip.js
src/vis/vis.js
test/spec/geo/ui/tooltip.spec.js
test/spec/vis/vis.spec.js

Fixes cartodb/cartodb#3351.
With this PR, cartodb.js will only:
- Display legends for visible layers.
- Display torque controls if torque layer is visible.
@fdansv can you please take a look? thanks!

Only show legends and torque controls for visible layers

---

NEWS
vendor/mod/torque.uncompressed.js

Changes since last update:
>- Limited sprite radius to a maximum of 255px
>- Fixed custom marker-file functionality in Firefox
>- **Fixed inertia mismatch of Torque's canvas layer**
>- Added opacity get/setter to canvas layer in Google Maps
>- Fixed issue with `_super` being removed from listeners
@javisantana

Updates torque to 2.11.3

---

src/geo/ui/infowindow.js

Fixes cartodb/cartodb#3515:
- Enables jscrollpane's autoReinitialise option so that the plugin
correctly scrolls after the image has been loaded.
- Enables jscrollpane's maintainPosition option.
More info about these options [here](http://jscrollpane.kelvinluck.com/settings.html).
Before:
After:
@xavijam PTAL. Thanks!

Fix issue with infowindow scrolling due to slow image loading:

---

src/ui/common/dropdown.js
test/SpecRunner.html
test/spec/ui/common/dropdown.spec.js

Fixes #491, by overriding clean to unbind the event bindings done on none-view elements in the constructor.

Unbind dropdown bound events on clean

---

NEWS
src/geo/layer_definition.js
src/vis/vis.js
test/spec/geo/layer_definition.spec.js

Fixes cartodb/cartodb#3949.
We're enabling interaction on every sublayer created using the editor and that was causing some issues. We should only enable interaction when tooltips have 
@javierarce can you PTAL? Thanks!

Do not enable layer interaction if tooltip is empty

---

src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

Fixes #518. We know use the metadata returned by the tiler to determine the right indexes of mapnik layers in the map (anonymous or named map). This is important in when generating the urls for grids and the urls to fetch the attributes of mapnik layers.
@javisantana, what do you think?

Use the right indexes when fetching grids and attributes

---

src/geo/ui/time_slider.js
test/spec/geo/ui/time_slider.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/4135
@alonsogarciapablo mind a quick CR? :)
cc @saleiva

Uses local time in timeslider instead of UTC

---

src/geo/ui/time_slider.js

Fixes https://github.com/CartoDB/cartodb/issues/3951
... by using always the number of steps given by the torque provider, as opposed to the one in the cartocss properties.
@javisantana

Makes the slider have the correct range every time it changes

---

NEWS
src/geo/layer_definition.js
src/vis/vis.js
test/spec/geo/layer_definition.spec.js

Fixes #541. We were using `options.hidden` to determine if layers in "LayerDefinition"s or "NamedMap"s were visible.  But that is something that only gets set after invoking `sublayer.hide()` or `sublayer.show()`. With this PR, we also take into account the `visible` attribute that (sub)layers have in viz.json files so that layers are correctly displayed after loading a viz.json file.
@javisantana, can you please take a look at this? Thanks!

Take `visible` attribute into account when serialising maps 

---

Gruntfile.js
RELEASING.md

so now we have:
- dist task to build the current version
- default task is dist
- the release task is the one that ask about new version
there were several problems:
- imagemin was failing silently when prompt task was being run so when it's not run everything failed because a bug in imagemin. Does make sense to use imagemin?
- the build was working by chance, some of the needed variables were being added to the config when they should be part of the config from the start
- grunt was not reporting any error and it took 3 hours to realize then the process freeze

adds a way to build the current dist without user input

---

.gitignore
README.md
RELEASING.md
bower.json
bower.sh

as long as we check-in the dist files this issue https://github.com/CartoDB/cartodb.js/issues/367 would be solved
this is for example what Backbone or Bootstrap do
https://github.com/jashkenas/backbone
https://github.com/twbs/bootstrap
or, in order to not to pollute the history the dist files could be pushed to a different repo, like Foundation does after a successful publish
https://github.com/zurb/foundation/blob/master/.travis.yml
https://github.com/zurb/bower-foundation
your call @javisantana @alonsogarciapablo, what do you guys think should be the best approach here?
on the long term, it would be great to pull the dependencies from bower, too

prepare for bower

---

src/geo/gmaps/gmaps.js

Fixes cartodb/cartodb-management#4001.
Basically, `this.projector` didn't respond to `fromContainerPixelToLatLng` and this was causing a JS error when moving an annotation through the editor, when the map had a Google Maps basemap.
@javierarce would you mind taking a look at this?
cc/ @iriberri @javisantana

Fixes bug in annotations when using a Google Maps basemaps

---

doc/API.md
src/geo/map.js

While working on https://github.com/CartoDB/cartodb/issues/4552 I found that setBounds wasn't working, because the internal code silently aborted, due to zoom level not being returned.
As with http://leafletjs.com/reference.html, `getBoundsZoom` now always returns a number (fallbacks on max zoom if could not found a suitable one), and enabled. fitBounds to also work since it do not have to check for the `null` value anymore.
Also updated docs to use `setBounds` instead since there's no clear reason for why fitBounds should be used.

Fix setBounds/fitBounds for map w/o suitable zoom

---

src/geo/ui/annotation.js
test/spec/geo/overlays/annotation.spec.js
themes/css/map/cartodb-map-light.css

Original issue: https://github.com/CartoDB/cartodb/issues/4440
tl;dr: fonts weren't being correctly applied to annotations. This PR fixes that.

Fixes problem with fonts in annotations

---

src/api/layers.js
test/spec/api/layers.spec.js

Fixes: #593 
We're assuming that the layer in position #1 was a `layergroup` or `namedmap`. This PR implements a smarter way of looking for the first data layer.
cc/ @xavijam

cartodb.createLayer selects the first data layer instead of assuming that it's in position 1

---

src/api/cartocss.js

Fixes this issue: https://github.com/CartoDB/cartodb/issues/4493

Changes the default basemap ramp to blue to avoid problems with positron

---

src/api/cartocss.js

The `getDefaultCSSForGeometryType` method shouldn't give line styles to the points. This should fix CartoDB/cartodb#4748.
Fixes: https://github.com/CartoDB/cartodb.js/issues/627

Removes line default style from the point generator

---

themes/css/tooltip/cartodb-tooltip-default.css

From the issue description: 
> Sometimes the z-index of the annotations is greater than the z-index of the tooltip (which by default is 5).
> The solution I propose consists in increasing the z-index value of the tooltips to a number that guarantees that a map with a normal amount of annotations won't produce overlapping.
Original issue: CartoDB/cartodb#4872

Bump the z-index value

---

NEWS
src/geo/ui/legend.js
src/vis/vis.js
test/SpecRunner.html
test/spec/api/layers/cartodb.spec.js

Fixes #609.
There's some noise in this PR due to some reordering of classes inside a file. Sorry about that. The actual fix is implemented in these two commits: [1](https://github.com/CartoDB/cartodb.js/commit/153656c5e2eb036f1df4364f8fc2a203c0fed7b5) and [2](https://github.com/CartoDB/cartodb.js/commit/b174863f424ac73ac6e8d220069cfdd1af04c446).
@viddo PTAL. Thanks!

Only display legends if layer is visible

---

examples/search_with_pin.html
src/cartodb.js
src/geo/geocoder.js
src/geo/gmaps/gmaps.geometry.js
src/geo/leaflet/leaflet.geometry.js
src/geo/ui/mobile.js
src/geo/ui/search.js
src/vis/overlays.js
test/SpecRunner.html
test/spec/geo/ui/search.spec.js
themes/css/infowindow/cartodb-infowindow-default.css

Normal:
Mobile:
REVIEWER @alonsogarciapablo 
Related -> https://github.com/CartoDB/cartodb/issues/4914

Changed search ui component adding new functionalities

---

Gruntfile.js

Several problems I've found trying to publish a new version of CartoDB.js.
1. ```grunt release``` task (specified in the [releasing notes](https://github.com/CartoDB/cartodb.js/blob/gruntfile-fix/RELEASING.md)) was publishing dist files to S3.
2. ```grunt set_current_version``` task was ignoring the version selected in the prompt, if it was specified.
3. ```grunt build``` task working properly and ready to be used for CartoDB on-premises stuff (cc @azamorano).
cc @CartoDB/frontend

Fix release and build tasks within gruntfile

---

src/geo/gmaps/gmaps.js
src/geo/gmaps/gmaps_cartodb_layer.js
src/geo/gmaps/gmaps_cartodb_layergroup.js
src/geo/gmaps/torque.js
src/geo/leaflet/leaflet.js
src/geo/leaflet/leaflet_cartodb_layer.js
src/geo/leaflet/leaflet_cartodb_layergroup.js
src/geo/leaflet/torque.js
src/geo/map.js
test/spec/geo/gmaps/gmaps.spec.js
test/spec/geo/leaflet/leaflet.spec.js

These are the changes required to display the custom attributions that were added to the viz.json in cartodb/cartodb#5270.
@javier what do you think? [this](https://github.com/CartoDB/cartodb.js/compare/display-custom-attributions?expand=1#diff-c99f1bfa0704edaea17491896ed25ab7R302) is a bit hacky but it was the only way I found to set the attributions in the order I wanted (CartoDB attribution first and then the rest...). Thanks!

Display custom attributions

---

src/geo/gmaps/gmaps_cartodb_layer.js
src/geo/gmaps/gmaps_cartodb_layergroup.js
src/geo/leaflet/leaflet_cartodb_layer.js
src/geo/leaflet/leaflet_cartodb_layergroup.js
src/geo/map.js

To prevent this in the editor:
@javierarce PTAL! Thanks!

Changed default CartoDB attribution for layers

---

doc/API.md

maybe I'm wrong but I'm pretty sure image url method is lower case [getUrl](https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/image.js#L399) not `getURL`. On the other hand it's not consistent with the subLayer [getURL](https://github.com/CartoDB/cartodb.js/blob/develop/doc/API.md#sublayergeturltemplate) method.

image.getUrl documentation typo

---

src/geo/gmaps/gmaps.js
src/geo/leaflet/leaflet.js
src/geo/map.js
test/spec/geo/gmaps/gmaps.spec.js
test/spec/geo/leaflet/leaflet.spec.js
test/spec/geo/map.spec.js
test/spec/geo/ui/mobile.spec.js

This PR tries to improve/simplify the way we handle attributions for maps. Now the Map model listens to changes on its layers and updates the `attribution` attribute and updates its attribution accordingly (removing empty attributions, duplicates, adding the default CartoDB attribution, etc.).
Also, when a MapView is instantiated, attributions are "refreshed", so the map renders the right attributions if the map model already have some layers loaded (this is what happens in the editor).
@javierarce could you please take a look? thanks!

Handle map attributions a bit better

---

src/geo/ui/fullscreen.js

The problem is iframe content can't be "fullscreen-ed" if the origin/parent url doesn't have a https protocol. And this possible solution would be:
- Check if the map is iframed.
- If so, checks if the parent of the iframe has http protocol.
- If it doesn't have https protocol, fullscreen button is not rendered.
Related:
- Bug in CartoDB: https://github.com/CartoDB/cartodb/issues/4543 
- Happening here: http://mashable.com/2015/07/17/schumer-thrones-google-emmys/#vVL1wykkAZk9
- Explanation: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins 
Using some keys from [here](http://stackoverflow.com/questions/935127/how-to-access-parent-iframe-from-javascript).
Sorry but I'd like to warn all @CartoDB/frontend team.

Add checker to fullscreen button when it is rendered in an iframe

---

src/api/layers.js
test/spec/api/layers.spec.js

Fixes #678. [This commit](https://github.com/CartoDB/cartodb.js/commit/30dca98e51defe0c171a92c24f4d400d4bf87eb3) changed how we select the layer that must be used when `createLayer` doesn't specify an index, and torque layers were not taken into account.
@xavijam easy one...
cc: @iriberri

Select torque layers if no "cartodb" layers are present

---

examples/infowindow-with-different-positioning.html
src/geo/gmaps/gmaps_cartodb_layergroup.js
src/geo/leaflet/leaflet_cartodb_layergroup.js

Fixes #639.
In some circumstances, the map can be fixed to the top but the page might have some scroll that we need to take into account. In these cases it's better not to use the object.offsetParent approach.
@xavijam what do you think?

Do not rely on object.offsetParent when the map is fixed to the top.

---

src/geo/leaflet/leaflet.js
test/spec/geo/leaflet/leaflet.spec.js

Fixes #681.
1. Leaflet maps might have `attributionControl` set to false and CartoDB.js should still handle attributions correctly.
2. Leaflet maps might have some other layers with attributions, and these shouldn't be removed.
@fdansv can you please take a look?
cc: @iriberri

Fixed two issues with attributions in Leaflet maps

---

bower.sh

After [this change](https://github.com/CartoDB/cartodb.js/pull/684), the new version of CartoDB.js wasn't being calculated correctly. This (hopefully) fixes it.
cc/ @matallo

Updated bower.sh

---

src/geo/ui/fullscreen.js
src/vis/overlays.js

Apart from I introduced a bug last time I changed the fullscreen functionality (god), after talking with @iriberri and @oriolbx, if the fullscreen behaviour is not possible, we provide the possibility to open the map in a new tab, how does it sound? This could only happen when the map is added as an iframe.
REVIEWER: @alonsogarciapablo

If fullscreen is not possible, open the map in a new tab

---

test/spec/core/image.spec.js
themes/css/map/cartodb-map-light.css

Working on https://github.com/CartoDB/cartodb/issues/5206, I've noticed that background-clip property is not well managed by html2canvas. Example: http://jsfiddle.net/njLnwrjd/.
Do you think @javierarce it is needed?
REVIEWER: @javierarce

Removed background-clip properties from legends

---

doc/API.md

@andrewxhill , in regards to Docs issue[#156](https://github.com/CartoDB/docs/issues/156).  Please review.  I added the section "Interaction Methods for a Torque Layer", and found an example from fdansv.  I'm sure it needs some corrections (as I cannot see what it looks like in the output from this repo?)  Let me know what needs editing (I'll fix and ask rochoa to merge, when you sign-off).

added interaction methods for torque layers to the API Methods section

---

src/geo/ui/legend.js

This allows for legends that are purely custom (no data, just a template) to be rendered, otherwise
you get a "The legend is empty".
This check happens here: https://github.com/CartoDB/cartodb.js/blob/master/src/geo/ui/legend.js#L1062

Allow pure custom Legends

---

examples/index.html
themes/scss/map/canvas.scss
themes/scss/widgets/canvas.scss
themes/scss/widgets/default.scss

Adapted the markup and styles to take into account the time-series widget that is located below the map canvas instead of the widgets list.
For now it's just hardcoded markup, it will be replaced with the actual widget (not included in these changes, WIP).
@xavijam please review

CSS changes for new time-series widget

---

themes/css/map/cartodb-map-light.css

reviewer @xavijam 
close #752 
CSS style for stacked legen was using `display: none;` that makes the stack legend hidden by default. I have remove that so by default it was visible like any other legend.

Stack legend visible by default

---

examples/map_dragging_disabled.html
src/geo/gmaps/gmaps.js
src/geo/leaflet/leaflet.js
src/geo/map.js
src/vis/vis.js
test/spec/geo/gmaps/gmaps.spec.js
test/spec/geo/leaflet/leaflet.spec.js
test/spec/vis/vis.spec.js

Reviewer @alonsogarciapablo 
Close #789, close https://github.com/CartoDB/cartodb/issues/5995 
This PR allows to disable the map dragging when no zoomControl (overlay) is specified and the `scrollwheel` option is disabled.
**Note with this implementation you can only set dragging at construction time, for the moment is not possible to change the property later.**
Modifications:
- new `drag` property on `cdb.geo.Map` model class.
- Both `cdb.geo.GoogleMapsMapView` and `cdb.geo.LeafletMapView` uses the model `drag` attribute to initialize the map.
> Notes:
> - Can’t test `cdb.geo.LeafletMapView`. Although you disable dragging map continues moving using `panTo` or `setView`. The alternative is emulate a mouse dragging effect.

Feature 789 disable dragging

---

themes/css/map/cartodb-map-light.css

PR initially posted here : https://github.com/CartoDB/cartodb/pull/6112  cc @xavijam
It seems that grunt-sass (node-sass) cannot compile styles from cartodb.css because some !important statements are capitalized (!Important). 
I switched all the !Important to !important in cartodb.css

Remove capitalize in !important statements

---

src/vis/vis.js

Triggers an event when the infowindow is loaded and it's been added to the dom so listeners of the layer are notified when they can interact with the infowindow.

Triggers an event when the infowindow is loaded and ready

---

package.json
src/geo/gmaps/gmaps-torque-layer-view.js
src/geo/leaflet/leaflet-torque-layer.js
src/geo/map/torque-layer.js
src/geo/ui/widgets/histogram/content-view.js
src/geo/ui/widgets/time-series/histogram-view.js
src/geo/ui/widgets/time-series/torque-content-view.js
src/geo/ui/widgets/time-series/torque-controls-view.js
src/geo/ui/widgets/time-series/torque-histogram-view.js
src/geo/ui/widgets/time-series/torque-time-info-view.js
src/geo/ui/widgets/time-series/torque-time-marker-view.js
src/vis/vis.js
src/windshaft/filters/range.js
test/spec/geo/ui/widgets/time-series/torque-content-view.spec.js
test/spec/geo/ui/widgets/time-series/torque-time-marker-view.spec.js
test/spec/windshaft/filters/range.spec.js

Waypoint for #786
This PR adds:
- Torque: animation for a selected time-series range
- Torque: format time-marker step info (time+date)
Basically just minor view changes, although had to modify the torque layer model slightly to handle events properly (for steps/range changes. 
Also notice that this PR depends on having a new minor version of torque.js, these changes are using https://github.com/CartoDB/torque/pull/243 for now I'm testing with a local checkout of that repo and using `npm link` to verify the changes working for this branch.
@javierarce can you review?
cc @javisantana for torque layer model changes

Add histogram selection + time info for torque time-series widget

---

themes/scss/map/dashboard-info.scss

@xavijam take a look.
Fix this one https://github.com/CartoDB/cartodb.js/issues/896

fix extra space in ipad view

---

src/geo/ui/widgets/time-series/torque-controls-view.js
src/geo/ui/widgets/time-series/torque-controls.tpl
themes/scss/widgets/buttons.scss
themes/scss/widgets/control-button.scss
themes/scss/widgets/themes/light.scss
themes/scss/widgets/time-series.scss
themes/styleguide/elements.html
themes/styleguide/layout-loading.html
themes/styleguide/styleguide.css

Resolves #894
Makes the icons appear consistent in all evergreen browsers. Perhaps we should consider applying the same approach for the other (round-kind) icons too, and consolidate the components a little?
Anyway, the code changes should speak for themselves, added inlined comments for non-obvious props though. Also fixed the styleguide to be coherent with the cartodb.css (removing default resets), so things actually will look the same in both styleguide and examples.
@xavijam can you review plz? cc @piensaenpixel @javierarce

Fix torque time-series control icons

---

src/geo/ui/widgets/histogram/chart.js
src/geo/ui/widgets/histogram/content-view.js
test/spec/geo/ui/widgets/histogram/chart.spec.js

This PR moves the hide/show logic to a model-based one. It also fixes a Firefox bug that prevented hiding an histogram right after was appended to the dom.

Refactor the chart hide/show methods

---

src/geo/gmaps/gmaps.js
test/spec/geo/gmaps/gmaps.spec.js

We were mixing up the value of the allowDragging. So when drag was enabled, disableDoubleClick should false.
Fixes cartodb/cartodb#6216.
cc @acanimal

Fixing double click over google maps when drag is enabled

---

Gruntfile.js
package.json
src/api/module-load.js
src/cartodb.js
src/cartodb.mod.torque.js
src/index.js
test/spec/cartodb.mod.torque.spec.js

Same as [standard but with semicolons](https://github.com/Flet/semistandard#rules), as requested offline and https://github.com/CartoDB/cartodb.js/pull/928#issuecomment-165036919
@javisantana @alonsogarciapablo OK with you? This PR was a 5-min change so no biggie. 
cc @CartoDB/frontend FYI

Change linter to semistandard

---

themes/scss/map/attributions.scss

Original issue: #980 
This PR fixes a problem with the map attribution. It's possible to inadvertently click on the attribution of the map and follow the linked URLs.
PR: @piensaenpixel

Fixes issue with non-hidden attribution

---

src/geo/ui/infowindow.js
src/vis/vis.js
styleguide/infowindows.html
test/spec/geo/ui/infowindow.spec.js
themes/scss/infowindow/cartodb-infowindow-default.scss

This PR adds:
- Shows error messages to indicate non-valid URLs for the image cover.
- Adds loader.
- Several fixes (like one for the empty infowindow tip or hook that didn't appear if the infowindow had an image cover; or added ```pointer-events: none``` to certain hidden areas that prevented clicking on the map)
- Renamed  classes:``.is-header``` and ```.is-header-image``` to `.has-header``` and ```.has-header-image```

Adds loader and error message to the infowindow

---

doc/layer_source_object.md

For [Docs issue#626](https://github.com/CartoDB/docs/issues/626), changed type from torque to cartodb for the time being. (Additional issue to enhance this section is also planned, as described in the issue).
@matallo , please merge

changed type from torque to cartodb for layer source object

---

grunt/tasks/jasmine.js
src/geo/gmaps/gmaps-layer-view-factory.js

Some class definitions expected the global "google" object to be defined. This PR introduces a condition in the `gmaps-layer-view-factory` that prevents those files from being required when "google" is not present.
@viddo perhaps there's a better way to do this...

Fixes google maps API dependency

---

doc/api_methods.md

@rochoa , a Support Issue reported the out-of-date versioning number in the CartoDB.js introduction / API Methods.  I have rewritten the intro slightly, and added a link to the more generic Releases folder. That way, whenever versioning changes, this will be correct.
Please let me know if you approve?

added link to Releases folder instead of specific version number

---

Gruntfile.js
grunt/tasks/watch.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/windshaft/filters/base.js
src/windshaft/filters/category.js
src/windshaft/filters/range.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/dataviews-collection.spec.js
test/spec/dataviews/dataviews-factory.spec.js
test/spec/windshaft/filters/base.spec.js
test/spec/windshaft/filters/collection.spec.js

Resolves #1024 
Noteworthy:
- Changed to `listenTo` instead, since that allows to remove _all_ event listeners from the own object (even on other objects), upon calling `stopListening`, which comes handy to cleanup after itself.
- Use `destroy` event (in lieu of a `remove event for example) because it removes the model from the parent collection too w/o any additional code.
- Renamed `dataviews.createFoobarDataview` to `dataview.createFoobarModel` to clarify what's returned
- Some cleanup of build stuff (skip console output that's included in the index file)
@alonsogarciapablo can you review? Also, I'm probably missing things… should a removal need updates in other parts of the code base? E.g. Should the WindshaftMap be re-instantiated?

Implement dataview.remove

---

src/dataviews/category-dataview-model.js
src/dataviews/formula-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

Trying to fix https://github.com/CartoDB/deep-insights.js/issues/105, @javierarce and I realized that dataviewModel(s) are not returning ```suffix``` and ```prefix``` attributes when ```toJSON``` is called.
CR: @javierarce
cc @viddo @alonsogarciapablo

Returning suffix and prefix values for Formula and Category dataviews models

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Changed the until-now-private attrs to snake_case, and changed names to make intentions clearer.
I tried to put names that are semantic to the "outside world", since we'll need to expose/pass these attrs (+`enabled`) from the editor.
@alonsogarciapablo  can you review?

Clarify dataview models' default attrs names

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

[This commit](https://github.com/CartoDB/cartodb.js/commit/ff3960e3ec6f93500f454da4b6cd6f3b1b8f1cfc) renamed `ownFilter` to `enableFilter`, but I think we forgot to replace one usage of the attribute. This PR fixes that and adds a couple of tests to test that behaviour.
@viddo can you please review? thx!

Fixes wrong attribute name ownFilter -> enableFilter

---

src/dataviews/category-dataview-model.js

The exact same code that is being removed on this PR is present in [the "super" method](https://github.com/CartoDB/cartodb.js/blob/remove-duplicated-binding/src/dataviews/dataview-model-base.js#L121-L133) so this object was being bound to the "change:enabled" event twice. This was causing the dataview to fetch it's data twice when the dataview was re-enabled.
@viddo it's pretty trivial, but just in case I'm missing something... PTAL. thanks!

Removed duplicated binding

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

Basically, the acceptedCategories data should only be added when the `enableFilter` is false (before the variable was `ownFilter`).

Fixing change about how to parse data within category dataview

---

src/windshaft/filters/category.js
test/spec/windshaft/filters/category.spec.js

If a category was rejected, when it is accepted, we shouldn't include it in the acceptedCategories "array", it should be removed from the rejectedCategories, and that's it :dancer:.

Fix problem with category filter when accepts a category where it was rejected

---

Gruntfile.js
grunt/tasks/jasmine.js
src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/dataviews/formula-dataview-model.js
src/dataviews/histogram-dataview-model.js
src/dataviews/list-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/formula-dataview-model.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js

Related to #1040, some things were missing in previous PRs
Also discovered that aggregation_column need to be translated to camelcased version when sent to Windshaft, added a todo for this for now so we can move fwd
Finally, moved attrs names definition here as well as some minimal validation (presence) of attrs when creating the dataview.
@alonsogarciapablo 
cc @xavijam

Reload map on prefix+suffix change on category dataview

---

src/dataviews/category-dataview-model.js

Was faulty changed in
https://github.com/CartoDB/cartodb.js/commit/2e9b0ea39440d8bca812c0665b76e114a3e54e17#diff-51a09ea5f3b9485ac7865588bdfa1082R18
it was given as `category` from DI: https://github.com/CartoDB/deep-insights.js/pull/138/files#diff-eb62919dbc9c6c8e66ffed48ee679a92L39,
although in the `toJSON` we have the hardcoded `aggregation` value: 
https://github.com/CartoDB/cartodb.js/blob/2e9b0ea39440d8bca812c0665b76e114a3e54e17/src/dataviews/category-dataview-model.js#L249
It should be category as type still since some code depends on it.
@alonsogarciapablo

Change type to category again

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

This "flag" was being used incorrectly so I fixed it. Since `enableFilter` and `disableFilter` are being used from deep-insights.js, I will open a PR on that repo to fix it there too.
@xavijam what do you think?

Fixed `enableFilter` flag on the category dataview model

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

- Checking if search results are already selected or not.
- Adding methods to calculate filter categories over current data.
Both changes from this [Deep-insights PR](https://github.com/CartoDB/deep-insights.js/pull/151/files#diff-9174d99f35e6d799c1c69c256b44b3c3R126).

Changes over category dataview model

---

src/dataviews/dataview-model-base.js

CR @viddo cc @alonsogarciapablo 
close #1094 
Added `type` attribute to the allowed dataview properties, otherwise the `id` is now well defined and always is named `undefined-xxx`.

Fixed dataview naming

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

I'm pretty sure I'm missing something but changing `bins` should not reinstanciate the map since bins is something you set when you fetch.
cc @alonsogarciapablo @viddo

fixes updating bins

---

src/dataviews/dataview-model-base.js
src/geo/map.js
src/vis/vis.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/map.spec.js
test/spec/vis/vis.spec.js

There used to be several map instantiations when widget dataviews are added to the dataviewsCollection. It generated problems in the map rendering, more requests to the API than expected, etc.
So, from now on, when a dashboard (deep-insights) is created, it will skip the map instantiation until dataviews collection is generated (@viddo idea's, and totally makes sense).
CR: @viddo
cc @javisantana @alonsogarciapablo @javierarce @acanimal 
Deep-insights [PR](https://github.com/CartoDB/deep-insights.js/pull/196).

Map instantiation bug

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

- Adds two public methods: enableFilter and disableFilter, that will be used by deep-insights. This is consistent with the category-dataview-model.
- Histrogram Dataview models now sets the `start`, `end` and `bins` properties after the first fetch.
- `.url` method only includes `start`, `end` and `bins` when `own_filter` is 1.
This is my second attempt to fix #1069 in a nicer way :) :) :). Checkout CartoDB/deep-insights.js#220 to checkout the changes in deep-insights.js.
@javisantana since you suggested following a different approach... what do you think? thanks!

Changes to the histogram dataview model

---

src/windshaft/filters/collection.js
src/windshaft/windshaft-map.js

CR @alonsogarciapablo 
close https://github.com/CartoDB/deep-insights.js/issues/169 (from DI).
Please Pable review this PR. It solves a problem when there are two layers with widgets and you hide one of them. The widgets are hidden and the second layer widgets works until you make some filter.
Check if my reasoning is correct.
I realize we have generating an array of filters for winshaft map with the filters in the same position as the layer index and holes of no layer of filter is empty.
Supposing we have two layer and we hide one, new info is send to server with only one layer (not two). Later if you filter on a widget of the second layer an array with two positions is sent, the first empty (hole) for filters of the first layer and the second for filter in the layer two), generating an …

Di 164 hide layers

---

doc/core_api.md

Add closing parenthesis and semi-colon to make example code work
[Obvious fix]

Close function parenthesis in code example

---

src/dataviews/dataviews-factory.js
src/windshaft/filters/collection.js
test/spec/windshaft/windshaft-map.spec.js

CR @alonsogarciapablo 
close #1020 
- Filters has a reference to the Layer instead had a `layerIndex` property.
- WindshaftMap and WindshaftFilterCollection are updated to compute the list of filters grouped by layer.

Filters has a reference to the Layer instead a `layerIndex` property

---

grunt/tasks/_browserify-bundles.js
src/dataviews/dataview-model-base.js
src/util/backbone-abort-sync.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/util/backbone-abort-sync.spec.js

Fixes part of https://github.com/CartoDB/deep-insights.js/issues/236.
No sure if it could break something from D3 integration.
CR: @javisantana
@viddo @alonsogarciapablo @fdansv @rochoa
PS: Deep insights PR also coming.

Cancel old requests that comes from dataviewModels

---

doc/api_methods.md
doc/ui_functions.md

Removed `cdb.geo.ui code` from the API doc and updated the entire "Specific UI Functions" section. (Related to issue #761 , and [Docs issue#686](https://github.com/CartoDB/docs/issues/686)). Also, applied some clarification in regards to tooltip/infobox descriptions.
@ernesmb , thanks for researching the latest behavior! Can you do a quick review of the changes we discussed and let me know if this is okay?

761 ui function examples

---

src/dataviews/dataview-model-base.js

Spotted while we were testing widgets with namedmaps, where all widgets requests were under `http`.
Do I forget something? Good solution?
@alonsogarciapablo @viddo 
cc @juanignaciosl

Using current window protocol for widget fetch url

---

src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
src/vis/vis.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js

In this PR I changed how we're creating new infowindows and tooltips right now. Instead of listening to the "newLayerView" event and adding infowindows/tooltips when a new layerview is added, we now work directly with the array of layerModels.
In an attempt to make things a bit more simpler and clean up the vis#load method, I've extracted the logic to manage infowindows and tooltips to what I've called an InfowindowManager and a TooltipManager. I'm open to better names.
@javisantana could you please tell me what you think about this approach? Thanks!

Fixes infowindows and tooltips

---

src/dataviews/category-dataview-model.js
src/dataviews/category-dataview/search-model.js
test/spec/dataviews/category-dataview-model.spec.js

After a category search is done, event was wrong because it was change to 'loaded'. Also using new `backbone-abort-sync` thing.
cc @javisantana

Fixing problem with loader in category search

---

src/geo/leaflet/leaflet-cartodb-layer-group-view.js

Seems like our very own [weird-zoom-bug](https://github.com/CartoDB/deep-insights.js/issues/249) is due to a problem of adding the same layer each time the map is instantiated. For example, when a filter is applied. Seems like @javisantana and I have cleaned a little bit the old code.
CR: @javisantana 
cc @alonsogarciapablo 
No more :scream: faces showing a Deep-Insights bug.

Not adding leaflet layer each time map is instantiated

---

examples/v4/leaflet-layergroup-vector.html
examples/v4/leaflet-layergroup.html
src/core/config.js
src/geo/leaflet/leaflet-layer-view-factory.js
src/geo/map-view-factory.js
src/geo/map.js
src/vis/vis.js
test/spec/geo/map/shared-for-interactive-layers.js

This change replaces the current mechanism that we use to determine when to render client-side. With this change, viz.json accepts a new `vector` option that can be used to enforce client-side rendering. I added an example that uses this new option(`examples/v4/leaflet-layergroup-vector.html`).
@javisantana yay or nay?

Enforce client-side rendering with "vector" attribute in the viz.json

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

Extracted from https://github.com/CartoDB/deep-insights.js/blob/96c5b72846d5c6c13c97c10260f435ba60f6b538/src/widgets/histogram/content-view.js#L314-L315 since
this should apply for all histograms, including time-series (which is also why start and end are included)
Required to solve https://github.com/CartoDB/deep-insights.js/issues/244 (PR: https://github.com/CartoDB/deep-insights.js/pull/253)
@alonsogarciapablo can you review?

Disable filter and unset range on bins, start, and end change on a histogram dataview

---

src/dataviews/histogram-dataview-model.js

After discussion w/ @javisantana regarding problematic use-cases related to changing start/end values for a time-series histogram, we concluded that it’s better it works like a normal histogram, i.e. the data range gets set on the initial fetch (calculated server-side based on the dataset), and can’t be changed after that.
I'll update DI and editor after this is merged (to remove the possibility to change the start/end dates).

Remove the possibility to edit start/end values of a histogram

---

src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js

There was a problem with how we were binding featureClick and featureOver events to layerView. We're basically binding the same events multiple times and when one of these two events, handlers were being executed multiple times (one per layer). This PR fixes it.
@javisantana :es: please

Ensure featureClick and featureOver events are bound once

---

examples/tutorials/tutorial-google-driving-2.html

@michellechandra , removed the add/remove CursorInteraction code from the CartoDB.js repo/examples/tutorials/tutorial-google-driving-2.html (in regards to your [tutorial](https://github.com/CartoDB/docs/pull/706)).

updated tutorial code in regards to issue 1137

---

src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js
src/dataviews/formula-dataview-model.js
src/dataviews/histogram-dataview-model.js
src/dataviews/list-dataview-model.js
src/geo/map.js
src/windshaft/windshaft-map.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/formula-dataview-model.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/dataviews/list-dataview-model.spec.js
test/spec/windshaft/windshaft-map.spec.js

Basically, if a widget has disabled sync_on_data_change, it will not change if there is an update of its 'column'.
We need to test this but I'd like your opinion before doing that. How does this approach sound?
Fixes #1144

Forcing dataview model fetch new data although sync_on_data_change attribute is disabled

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

We forgot to use `submitBbox` attribute in order to get the data without any filter (first load) and then get it with all filter parameters.

Fixing problem with first request in histogram dataview

---

src/geo/map/cartodb-layer.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/windshaft/layergroup-config.spec.js

Fixes #1182 
cc @javisantana @fdansv

Do not add cartodb_id column in interactivity column if there is no infowindow or tooltip field names required

---

src/windshaft/windshaft-map.js
test/spec/windshaft/windshaft-map.spec.js

We basically now ignore any possible `tiled` layer at the bottom of layers that comes from Windshaft response when getting the metadata for each of the local layer models.
@xavijam @fdansv PTAL, thanks!

Fixes issue with indexes when setting the metadata of layer models from Windshaft response

---

src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js

@alonsogarciapablo After you fixed the passing of metadata, the only thing that was broken was the tilejson listener reassigning styles by plucking the client styles. Since now we're relying on meta to always pass the styles, removing that style setter fixes the issue. Named maps are visible again in vector.

Prevents tilejson listener from invalidating cartocss

---

package.json

Includes nice fixes such as excluding empty `GeometryCollection` from entering the filter and performing contains checks to lines and polygons.
@xavijam

Points d3.cartodb to latest commit

---

package.json

As discussed with @javisantana, will change the internal libs to not use commits by main branches for reference instead.
@fdansv can you confirm that the gh-pages is the correct “main” branch of d3.cartodb?

Use the main branch instead of commit for dependency

---

src/core/util.js
src/geo/map.js
src/vis/vis.js
src/vis/vizjson.js
test/spec/geo/map.spec.js
test/spec/vis/vis.spec.js
test/spec/vis/vizjson.spec.js

This PR completes the first task of #804.
These changes will allow us to easily extract loading and manipulation of the vizjson (based on `createVis`  options) to `createVis`, which is the next step in #804.
@viddo could you please take a look? Thanks!

Extracts a VizJSON class with some methods to manipulate viz.json objects

---

src/api/sql.js
test/spec/api/sql.spec.js

I.e. 1st argument is always an error, and 2nd is the successful data.
This enabled to know when a `describeXXX` method fails, e.g.
```js
sql.describeGeom('SELECT * FROM foobar', 'the_geom', function(err, data) {
if (err) throw err;
console.log(data) // => { simplified_geometry_type: "line", … 
})
```
@xavijam can you review?

Change SQL API to support node-like callbacks

---

src/geo/gmaps/gmaps-cartodb-layer-group-view.js
src/geo/leaflet/leaflet-cartodb-layer-group-view.js

For some reason, in the new editor, wax was being included before Leaflet in the `editor3.js` file. This was causing a JS error (when trying to use `L.TileLayer`, `L` was undefined). This little change fixes that. Perhaps, there's a better way to ensure Leaflet is required before wax?
@xavijam @javierarce?

Leaflet needs to be required before wax

---

src/analysis/analysis-model.js
test/spec/analysis/analysis-model.spec.js

So, silly me, I was unbinding previous listeners included type, so if type had changed twice, second one won't listen any change :(.

Keep listening type changes when it was changed once

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

The `source` of a layer is not a model anymore, so the method should change.

Fixes return value of the _getSourceId method

---

src/vis/vis-view.js
test/spec/vis/vis-view.spec.js

We were only polling analyses that were the source of a layer or dataview. This removes that limitation and polls all analyses instead. When an analysis that is the source of a layer or dataview becomes "ready", the map is reloaded...
cc: @viddo

Poll all analysis nodes

---

src/analysis/analysis-model.js
src/vis/vis-view.js
test/spec/vis/vis-view.spec.js

Closes CartoDB/cartodb#7319.
@viddo, this is the replacement for CartoDB/cartodb.js#1260. Basically, analysis nodes might be created/defined using `vis.analysis.analyse`, but they might not have been sent to the Maps API for some reason (eg: they are not linked to a layer/dataview yet) so they should not be polled.
cc: @xavijam @juanignaciosl

Polling should not start for analysis nodes that don't have a URL yet

---

src/vis/infowindow-manager.js
test/spec/vis/infowindow-manager-spec.js

Fixes #1267.
I also implemented some changes so that the filter of the tooltipView is cleared when the infowindow is closed. This was causing tooltips not to work on the feature that was clicked and infowindow was then closed.
@xavijam since you opened that issue... 👍 or 👎 ? Thanks!

Hide infowindow when fields are cleared

---

src/geo/map.js
src/geo/map/layers.js
test/spec/geo/map.spec.js

This PR changes things so that `map.createCartoDBLayer`, `map.createTorqueLayer`, etc. accept `at` option to specify where the position where the layer should be inserted. Orders are automatically re-assigned [here](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map/layers.js#L16). Also refactored the method that assign indexes a bit.
@viddo would you please take a look? thx!

Allow creating layers at a given position

---

src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/dataviews/formula-dataview-model.js
src/dataviews/histogram-dataview-model.js
src/dataviews/list-dataview-model.js
src/vis/vis-view.js
src/windshaft/anonymous-map.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/dataviews-factory.spec.js
test/spec/windshaft/anonymous-map.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/7605.
- Dataviews get sourceId from `{ source: { id: 'X' } }` attribute (that's what deep-insights.js is sending). Before, CartoDB.js was assuming attribute was called 'sourceId'.
- Assume dataviews will always have a source, instead of falling back to layer.
- Include an analysis node for dataviews in the map config for named maps, which was missing before.
@viddo 👍  👎  ? Thanks!
cc: @javisantana

Fixed analysis section in map config for anonymous maps:

---

src/dataviews/dataviews-factory.js
src/windshaft/anonymous-map.js
test/spec/dataviews/dataviews-factory.spec.js
test/spec/windshaft/anonymous-map.spec.js

- Instead a default sourceId is generated based on the layer id. This will fix the tests and examples in deep-insights.js
- Also, an analysis source is included in the map config for dataviews that have a layer as their source.
@fdansv please take a look. thanks!

Source attribute for dataviews is not required anymore

---

src/windshaft/map-base.js
src/windshaft/request-tracker.js
src/windshaft/request.js
test/spec/windshaft/map-base.spec.js

Fixes: https://github.com/CartoDB/cartodb.js/issues/1283.
@viddo I'd like to know your thoughts about this approach... CartoDB.js won't try to instantiate the exact same map more than three times with this change.
cc: @rochoa

Limit the number of subsequent requests to the Maps API using the same payload, params and options

---

examples/v4/leaflet-layergroup.html
src/geo/ui/default-infowindow-template.tpl
src/geo/ui/infowindow-model.js
src/geo/ui/infowindow-view.js
styleguide/infowindows.html
test/spec/geo/ui/infowindow.spec.js
themes/scss/infowindow/cartodb-infowindow-default.scss
themes/scss/infowindow/themes/dark.scss

Fixes: https://github.com/CartoDB/cartodb.js/issues/1301.
New markup needs to include the .js-close element.
```
<div class="CDB-infowindow CDB-infowindow--light js-infowindow" style="max-width: 200px;">
<div class="CDB-infowindow-close js-close"></div>
...
</div>
```

Infowindow close button

---

src/api/create-vis.js
src/geo/map.js
src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
src/vis/vis-view.js
src/vis/vis.js
test/spec/api/create-vis.spec.js
test/spec/geo/geocoder/nokia-geocoder.spec.js
test/spec/geo/gmaps/gmaps-map-view.spec.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js
test/spec/vis/vis-view.spec.js
test/spec/vis/vis.spec.js

Prep work for https://github.com/CartoDB/cartodb/issues/7574.
Changes:
- `cdb.createVis` returns a vis model object that responds to `.done` and `.error`. I didn't change how this works and done callback will be called when the map is first instantiated.
- `vis` object triggers `.load` event when vizjson has been loaded so that apps that use `createVis` with `skipMapInstantiation` option can instantiate the map when thy need to when everything is loaded (eg: deep-insights.js -> see https://github.com/CartoDB/deep-insights.js/pull/380).
- To make ^^ happen, I moved model related stuff from `vis-view.js` to `vis.js` (everything related with loading the vizjson).
@viddo: could you please take a look? Thx!

cdb.createVis returns a vis model that triggers load event when vizjson has been loaded

---

src/vis/overlays.js

Vis model is not included within vis, now it is available under `data.map`.

Fixing search problem

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Filter and widget were removed correctly, but map was not reloaded. Now it checks if there was a filter applied and it reloads the map.
Fixes https://github.com/CartoDB/cartodb/issues/7812.
cc @saleiva

Reloading map when widget with filter is removed

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1322.
We're only re-fetching dataviews that were associated to the same layer of the dataview that changed (eg: filter changed).
@viddo :+1: ?

Ensure dataviews are re-fetched when map is reloaded

---

src/analysis/analysis-model.js
src/geo/map/layer-model-base.js
src/vis/model-updater.js
src/vis/vis.js
src/windshaft/anonymous-map.js
src/windshaft/client.js
src/windshaft/error.js
src/windshaft/map-base.js
test/spec/analysis/analysis-model.spec.js
test/spec/api/create-vis.spec.js
test/spec/vis/model-updater.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft/anonymous-map.spec.js
test/spec/windshaft/client.spec.js
test/spec/windshaft/map-base.spec.js

First iteration on https://github.com/CartoDB/cartodb/issues/7574.
So far:
- `vis` model triggers:
- `ok` event when a new instance of the "map" is created successfully in the Maps API.
- `error` event when an unknown error occured error occurred (other errors will be triggered by more specific models like layers). **Error event will only include an error message for now (we can iterate on this and send more info)**.
- `vis` model still supports `.done(callback)` and `.error(callback)`. One of these two callbacks will be invoked when `cdb.createVis` is used without the `skipMapInstantiation` option:
```
var vis = createVis(...);
vis.done(function () { ... });
vis.error(function (error) { ... });
// Also, we can listen to `ok` and `error` events
vis.on('ok', function () { ... }); …
```

Expose some errors from Maps API

---

src/analysis/analysis-factory.js
src/analysis/analysis-model.js
src/api/create-vis.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/vis/vis.js
src/windshaft/map-base.js
test/spec/analysis/analysis-factory.spec.js
test/spec/analysis/analysis-model.spec.js
test/spec/api/create-vis.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/dataviews-factory.spec.js
test/spec/windshaft/map-base.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1226.
Fixes https://github.com/CartoDB/cartodb/issues/7859.
When the vizjson has an auth_token (this will be true for maps that are password protected), the following requests to Windshaft will use it in the query string:
- Requests to instantiate the map
- Requests to get the tiles
- Requests to get the grids
- Requests for dataviews
- Requests for analyses
NOTE: If apiKey and authToken are present these (☝️ ) requests will only include the api_key param.
@xavijam PTAL! Thank you! 💋

Requests to Windshaft include auth_token param

---

src/dataviews/histogram-dataview-model.js

We were just omitting the bins attribute because we were checking if it was a number, when the attribute is stored as a string.
@rochoa

Fixes number of bins not being sent to tiler

---

src/vis/vis.js

When `createVis` is used with `skipMapOptions:true` option, vis will have to be instantiated as follows:
```
vis.on('load', function () {
vis.instantiateMap({
success: function () { ... },
error: function () { ... }
});
});
```
@xavijam since you're already in the loop... will you give me a 👍? thx!

vis.instantiateMap supports success and error

---

src/analysis/analysis-model.js
src/geo/map/layer-model-base.js
src/vis/vis.js
src/windshaft/map-base.js
test/spec/analysis/analysis-model.spec.js
test/spec/geo/map/layer-model-base.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft/map-base.spec.js

The "API" for errors that we implemented initially (see https://github.com/CartoDB/cartodb.js/pull/1324#issuecomment-229647295) is not working properly because we might need to access the errors after the `error` event has been triggered (eg: right after the editor has been loaded).
This PR replaces `ok` and `error` events triggered by vis, layers and analyses by an `error` attribute that we can 'query' at any time. (this was suggested by @viddo at some point).
@viddo 👍 ?

Replaced `ok` and `error` events by `error` attribute on vis, layer and analyses models

---

src/api/create-vis.js
src/api/vizjson.js
src/vis/vis-view.js
test/spec/api/create-vis.spec.js
test/spec/vis/vis-view.spec.js

This PR changes the way we handle the logo in cartodb.js. From the builder we are going to update (not create/remove) the logo overlay.
cc @xavijam @alonsogarciapablo

Remove add overlay logo forced

---

src/geo/cartodb-layer-group-base.js
src/geo/map/layers.js
src/vis/infowindow-manager.js
test/spec/geo/cartodb-layer-group-anonymous-map.spec.js
test/spec/geo/cartodb-layer-group-base.spec.js
test/spec/geo/cartodb-layer-group-named-map.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/8558
- Infowindow was only being updated when it had been clicked before and it was visible.
- Internal collection of layers of the "LayerGroupModel" wasn't being updated correctly (the order wasn't right) when new layers were added/removed.
cc: @matallo

Fix infowindow issues 

---

src/windshaft/map-base.js
src/windshaft/request-tracker.js
test/spec/windshaft/map-base.spec.js

Ensure that new requests to Windshaft can be performed after the max number of subsequent request has been reached, when the request is different.
@xavijam 👍 ?

Ensure new requests to Windshaft can be performed when request limit has been reached

---

src/dataviews/dataview-model-base.js
src/windshaft/anonymous-map.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/windshaft/anonymous-map.spec.js

@javisantana this fixes the issue you encountered. Basically, if a dataview "points" to a layer, and that layer doesn't have `sql`, it means that it's pointing to an analysis node, and the dataview should point to the layers's source in the payload that is sen't to the Maps API. 👍 ?

Fix dataviews pointing to a layer that has a source

---

src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/geo/map.js
src/geo/map/cartodb-layer.js
src/geo/map/torque-layer.js
src/vis/model-updater.js
src/vis/vis.js
src/windshaft/map-base.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/geo/map.spec.js
test/spec/windshaft/anonymous-map.spec.js
test/spec/windshaft/map-base.spec.js
test/unit/dataviews/formula-dataview-model.spec.js
test/unit/dataviews/list-dataview-model.spec.js
test/unit/vis/model-updater.spec.js

Hopefully fixes https://github.com/CartoDB/cartodb.js/issues/1345.
Imagine the following situation, where there's a layer with 2 analysis and there're 4 widgets:
```
Layer A:     <- widget3
- a2       <- widget2
- a1       <- widget1
- a0       <- widget0
```
If the filter of widget0 changes, widget1, widget2 and widget3 need to fetch data again (because a0 affects a1 and a2). But, if the filter of widget1 changes, only widget1, widget2 and widget3 will need to fetch data again...
In summary: dataviews whose source is affected by the source of the dataview that caused the map to be re-instantiated, should fetch again.
@xavijam :+1: ?

Re-fetch dataviews when source is affected by some filtering

---

src/geo/map.js
src/vis/vis.js
test/spec/geo/map.spec.js
test/spec/vis/vis.spec.js

Closes https://github.com/CartoDB/cartodb/issues/8959.
Events were being bound every time `map.instantiateMap` was called and this was causing:
1. `_updateAttributions` not being called right after the layers are reseted.
2. event callbacks probably being executed multiple times every time `map.instantiateMap` was called.
Also, `map.reload` does nothing until `map.instantiateMap`has been called at least once now.
@xavijam 👍 or 👎 ?

Fix attributions

---

.eslintignore
examples/v4/gmaps-layergroup.html
examples/v4/leaflet-layergroup-vector.html
examples/v4/leaflet-layergroup.html
src/cdb.config.js
test/spec/cartodb.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/map.spec.js

This is part of https://github.com/CartoDB/cartodb/issues/8984.
Basically replaced:
`CARTO <a href="https://carto.com/attributions" target="_blank">attribution</a>`
by
`© <a href="https://carto.com/attributions" target="_blank">CARTO</a>`.
@xavijam 👍 ?

Changes default CARTO attribution

---

src/vis/model-updater.js
test/unit/vis/model-updater.spec.js

This PR fixes https://github.com/CartoDB/cartodb/issues/9415
When an analysis fails, the error message come wrapped inside the maps api request as `error_message` parameter:
When the model is updated, we look for this parameter to set error properly. Otherwise the error message will be empty. 
I know there were some intents of solving notifications from the maps api in the past, and I guess some of the solutions implemented aren't valid now. Not sure if this change of behaviour obey to a change in Whidshaft but this is the easy way to fix this today.
cc @xavijam @alonsogarciapablo

Check for error_message when update analysis node.

---

src/vis/vis.js

This PR adds logo option backward compatibility: https://github.com/CartoDB/cartodb/issues/8674
cc @xavijam

Look for options only if not null.

---

src/geo/ui/search/search.js
src/vis/vis-view.js
themes/scss/map/overlays.scss

This PR updates the logic for search overlay positioning when the zoom overlay is present/hidden.
It's related to https://github.com/CartoDB/cartodb/issues/9410
cc @xavijam

Update search overlay position when zoom is visible or hidden.

---

src/geo/map-view.js
src/geo/torque-layer-view-base.js

This is a temporary workaround, it reuses api_key and auth_token
from existing _cartoDBLayerGroup model.

Add/append api_key and auth_token in torque layers

---

src/vis/vis.js
src/windshaft/client.js
test/spec/api/create-vis.spec.js
test/spec/vis/vis-view.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft/client.spec.js

Fixes #1396 and fixes CartoDB/cartodb#9523.
We're always (and mistakenly) enforcing creation/instantiation of maps using POST. This PR implements the following algorithm to determine when to use GET (JSONP) vs POST requests:
- Length of URL with encoded params + `config` param < 2033 -> `GET /api/v1/map?config=…&stat_tag=...`
- Length of URL with encoded params + `lzma` param < 2033 -> `GET /api/v1/map?lzma=…&stat_tag=...`
- Length of URL with encoded params + `lzma` param >= 2033 -> `POST /api/v1/map?stat_tag=…`
@rochoa would you mind taking a look?

Try to create/instantiate maps using JSONP before using POST

---

src/vis/vis.js
src/windshaft/client.js
test/spec/api/create-vis.spec.js
test/spec/windshaft/anonymous-map.spec.js
test/spec/windshaft/client.spec.js
test/spec/windshaft/map-base.spec.js
test/spec/windshaft/named-map.spec.js

In #1398 we removed the code that was enforcing usage of POST requests when creating/instantiating maps. That change revealed something that was wrong: we're hitting the wrong endpoint when instantiating named maps via GET/JSONP.
We're using the following URLs (wrong):
```
.../api/v1/map/named/tpl_13cc78fc_7435_11e6_857e_04013fc66a01?config=...
```
When we should be using the /jsonp endpoint:
```
.../api/v1/map/named/tpl_f9e77bf4_7438_11e6_ac8d_080027a55d4d/jsonp?config...
```
This PR fixes that.
@rochoa would you please take a look? Thanks!
fixes #1402.

Use /jsonp endpoint to instantiate named maps via GET

---

.eslintignore
package.json
src/geo/map/torque-layer.js
test/spec/geo/leaflet/leaflet-torque-layer-view.spec.js
test/spec/geo/map/torque-layer.spec.js

Basically if the `CartoCSS` is using TurboCarto, we have to instantiate in order to receive the "readable" `CartoCSS` from the instantiation, no matter what property has changed.
Things needed for this purpose:
- Added `sql_wrap` to those attributes that trigger vis reload.
- "Updated" *torque* dependency within package.json, now requesting it from repository instead of npm.
- "Updated" *carto* dependency as we do in Builder dependencies, requested from the repository.
cc @rochoa and @javisantana 
This is part from https://github.com/CartoDB/cartodb/issues/9389.

Check if changed CartoCSS is using turbo carto in order to instantiate map

---

src/geo/map/torque-layer.js
test/spec/geo/map/torque-layer.spec.js

After checking new changes in the lastest torque, the instantiation is not needed in order to draw correctly the tiles, so better for us.
Goodbye useless work :(.
cc @alonsogarciapablo @rochoa @javisantana

Removed unnecessary instantiation when there is turbocarto on cartocss

---

themes/scss/infowindow/cartodb-infowindow-default.scss

CR @xavijam 
this is needed along with some changes in https://github.com/CartoDB/cartodb/issues/9701

popups: image header, add order class to hide first field in content

---

src/windshaft-integration/model-updater.js
test/unit/windshaft-integration/model-updater.spec.js

And reflect that in the UI by changing legend's state to "error" when this happens. It was stopping the map re-instantiation before.
Also, ensure that only one rule is used to update each legend model.
@rochoa 👍 ?

Catch errors thrown by legend adapters

---

src/api/create-vis.js
src/geo/map/legends/legends.js
src/geo/ui/legends/layer-legends-view.js
src/geo/ui/legends/legends-view.js
test/spec/geo/ui/legends/layer-legends-view.spec.js
test/spec/geo/ui/legends/legends-view.spec.js

This PR hides the legends container if layer selector is not activated and no legend is visible.
@alonsogarciapablo 🙏

Hide legends if no legend is visible.

---

src/geo/ui/default-infowindow-template.tpl
src/geo/ui/infowindow-model.js
src/geo/ui/infowindow-view.js
test/spec/geo/ui/infowindow-model.spec.js
test/spec/geo/ui/infowindow.spec.js
test/spec/vis/infowindow-manager-spec.js

fixed an issue where values in custom templates weren't appearing, related to alternative names overriding titles
also, removed functionality where titles had underscores and they were _sanitized_, but again used in custom templates, thus not appearing
- added test to check alternative_name, and no title in both default and custom template
- changes in default template, surfaced when adding the tests
find the discussion below:
---
managed to reproduce it, this was already happening in the current editor, where we sanitize the title in the infowindow and replace "_" with spaces (see attached)
https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/ui/infowindow.js#L455
I'm removing this sanitization as it doesn't contribute a lot, and the user could always make this change manually with …

popups: alternative names in custom templates

---

src/geo/cartodb-layer-group-view-base.js
src/geo/map-view.js
src/geo/map.js
src/geo/map/cartodb-layer.js
src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
test/spec/geo/map-view.spec.js
test/spec/geo/map.spec.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js
test/spec/windshaft/anonymous-map.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1438.
This PR implements a mechanism to:
1. Enable/disable popups (enabled by default):
```
vis.map.enablePopups
vis.map.disablePopups
vis.map.arePopupsEnabled
vis.map.arePopupsDisabled
```
2. Enabled/disable "clickable features" (disabled by default).
```
vis.map.enableFeatureInteractivity
vis.map.disableFeatureInteractivity
vis.map.isFeatureInteractivityEnabled
```
When "clickable features" are enabled, `vis.map` triggers the following events:
```
featureOver
featureClick
featureOut
```
Mouse cursor is now changed to `pointer` when "clickable features" are enabled or popups are enabled and any visible layer has popups (infowindow/tooltips).
In order for "clickable features" to work, all visible layers have interactivity enabled by …

Clickable features and "disableable" popups

---

src/api/create-vis.js
src/geo/ui/legends/base/legend-view-base.js
src/geo/ui/legends/layer-legends-template.tpl
src/geo/ui/legends/layer-legends-view.js
src/geo/ui/legends/legends-view.js
src/vis/vis-view.js
test/spec/geo/ui/legends/layer-legends-view.spec.js
test/spec/geo/ui/legends/legends-view.spec.js
themes/scss/map/overlays.scss

This PR fixes cartodb.js side of https://github.com/CartoDB/cartodb/issues/10093
In addition to the issue's description, the layer selector should only be visible in the settings view in the Builder. That's why we need to segment when the vis is rendered from an embed view (by default) or by Builder.
cc @alonsogarciapablo @xavijam

Fine tune layer selector

---

src/geo/ui/legends/bubble/legend-view.js
themes/scss/map/overlays.scss

This PR fixes #1452. Also, it fixes the avg label position for bubbles. In the same manner we did for choropleths, we are including the full range to calculate the position, not assuming that the min value is always 0.
Before:
After:
CR @alonsogarciapablo @piensaenpixel

Fix avg position.

---

src/geo/ui/legends/bubble/legend-view.js
src/geo/ui/legends/choropleth/legend-template.tpl
src/util/formatter.js
test/spec/geo/ui/legends/bubble/legend-view-spec.js
test/unit/util/formatter.spec.js
themes/scss/map/overlays.scss

This fixes #1456. Another round about precision, because if the input is string, the formatter didn't do anything, so we tried to convert to number always in order to apply the format. Also we introduce the exponential numbers:
This PR also fixes the avg bubble position. I was assuming a lineal scale, but the thing is it's not, so we need to place it in the right range (bubble).

Improve precision

---

src/geo/ui/legends/base/error-title.tpl

@nobuti here's the small fix. I like 'Oops' too but it seems that "Sorry..." is [used more consistently](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=%22something+went+wrong%22) across the product

Update message for error

---

examples/v4/leaflet-layergroup-legends.html
src/geo/ui/legends/custom/legend-template.tpl
themes/scss/map/overlays.scss

@piensaenpixel need some help to make this look 👌 .
If you open `examples/v4/leaflet-layergroup-legends.html` in your browser, you'll see that I added one item with icon to the existing custom legend.
The template is `src/geo/ui/legends/custom/legend-template.tpl`, and I added a `Legend-categoryIcon` class to the span for the icon.
cc: @xavijam @nobuti @gfiorav

Render custom legend items with icons

---

src/vis/vis.js

Basically trying to fix [this problem](https://github.com/CartoDB/cartodb/issues/10432), I've realized that if a map is broken, for example, styling by a column, and then applying a query without that column, if we reload the map, the map is not initialized, basically due to the problem that we weren't binded the error in the map instantiation.
cc @alonsogarciapablo @nobuti

We have to bind errors in the instantiation of the map

---

src/geo/map/infowindow-template.js
src/geo/map/tooltip-template.js
src/geo/ui/infowindow-model.js
src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js

Fixes #1475
We're not showing infowindows/tooltips if they didn't have any `fields`. This wasn't working for `custom` infowindows/tooltips, where there's only the `template` attribute. We use that attribute now and, as long as its not empty, the infowindow/tooltip will be displayed.
@matallo could you please take a look? thanks!

Show custom infowindows/tooltips with no fields

---

src/vis/map-cursor-manager.js
test/unit/vis/map-cursor-manager.spec.js

If features of an interactive layer were being overed and the layer is hidden, the cursor wasn't being set to `auto` again. This PR solves that issue by setting the cursor back to `auto` if a layer that was being "feature overed" is hidden and no other clickable layer is being "feature overed".
@matallo can you please take a look?

Take layer visibility into account to determine the mouse cursor

---

examples/v4/geometry-drawing.html
src/geo/geometry-models/geojson-helper.js
src/geo/geometry-models/geometry-base.js
src/geo/geometry-models/geometry-factory.js
src/geo/geometry-models/multi-geometry-base.js
src/geo/geometry-models/multi-point.js
src/geo/geometry-models/multi-polygon.js
src/geo/geometry-models/multi-polyline.js
src/geo/geometry-models/path-base.js
src/geo/geometry-models/point.js
src/geo/geometry-models/polygon.js
src/geo/geometry-models/polyline.js
src/geo/leaflet/geometries/multi-geometry-view-base.js
src/geo/leaflet/geometries/path-view-base.js
src/geo/leaflet/geometries/polygon-view.js
src/geo/leaflet/geometries/polyline-view.js
test/spec/geo/leaflet/geometries/point-view-spec.js
test/spec/geo/leaflet/geometries/shared-tests-for-path-views.js
test/unit/geo/geometry-models/geometry-factory.spec.js
test/unit/geo/geometry-models/multi-point.spec.js
test/unit/geo/geometry-models/multi-polygon.spec.js
test/unit/geo/geometry-models/multi-polyline.spec.js
test/unit/geo/geometry-models/point-spec.js
test/unit/geo/geometry-models/polygon.spec.js
test/unit/geo/geometry-models/polyline.spec.js

Required for https://github.com/CartoDB/cartodb/issues/10530.
Usage example:
```
polygon.setCoordinatesFromGeoJSON({
type: 'Polygon',
coordinates: [
[ [ 0, 0 ], [ 10, 10 ], [ 20, 20 ], [ 0, 0 ] ]
]
});
```
Also, I renamed methods to get coordinates from points, polylines and polygons to `getCoordinates` and `setCoordinates`. Names were a bit inconsistent before.
@matallo could you please take a look? Thanks!

Added method to update geometry coordinates from a GeoJSON object

---

src/geo/cartodb-layer-group-view-base.js

Fixes https://github.com/CartoDB/cartodb/issues/10542.
This PR basically reverts [this change](https://github.com/CartoDB/cartodb.js/commit/917d31f4b76377aed2076820db83b6442f53e0fc#diff-394491c3c8e791282436eb57ad5181c6R20).
@xavijam just for a second pair of eyes... 👍  or 👎  ? Thanks!

Make sure interaction is cleared correctly

---

src/vis/feature-events.js
src/vis/vis-view.js
test/unit/vis/feature-events.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/10542.
After a layer is removed, there's a brief period of time in which the the new interaction grids are being requested/loaded and feature events for an inexistent layer model were being triggered. This fixes that issue by checking if the layer still exists before triggering the events.
@matallo please take a look! Thanks!

Do not trigger feature events if layer no longer exists

---

src/geo/geometry-models/geometry-base.js
src/geo/geometry-models/multi-point.js
src/geo/geometry-models/multi-polygon.js
src/geo/geometry-models/multi-polyline.js
src/geo/geometry-models/point.js
src/geo/geometry-models/polygon.js
src/geo/geometry-models/polyline.js
test/unit/geo/geometry-models/point-spec.js
test/unit/geo/geometry-models/polygon.spec.js
test/unit/geo/geometry-models/polyline.spec.js

To prevent triggering of unnecessary 'change' events.
@matallo please take a look. Thanks!

Only set coordinates when given a GeoJSON with different coordinates

---

src/geo/map/infowindow-template.js
src/geo/map/popup-fields.js
src/geo/map/tooltip-template.js
test/unit/geo/map/infowindow-template.spec.js
test/unit/geo/map/tooltip-template.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1499. Please read the issue for some context.
@matallo 👍  ? Thanks!

Use only field names to compare infowindow/tooltip fields when they are updated

---

src/api/sql.js
test/spec/api/sql.spec.js

Fixes a corner case in the SQL.getBounds function: when the API returns no bounds, neither the promise was resolved nor the callback was called.
CR @alonsogarciapablo 
CC @xavijam

Fixed bug & tests

---

src/geo/ui/legends/choropleth/legend-template.tpl
src/geo/ui/legends/choropleth/legend-view.js

Fixes #1533
The problem was that in the template the variable correspondent to the label wasn't being formatted correctly, so in case it had HTML inside it wasn't interpreted.
1. Go to Builder map
2. Create a gradient legend for a column with number type where at least one field has a decimal value (i.e. `0.0000000078`)
3. In "Creating you legend" step, select left label
4. The expected result is a decimal number formatted as mantissa and exponent (`[mantissa]x10^[exponent]`)

Fixed not formatted label on legends

---

src/dataviews/category-dataview-model.js
src/dataviews/category-dataview/categories-collection.js
src/dataviews/category-dataview/search-model.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/category-dataview/categories-collection.spec.js

This PR fixes https://github.com/CartoDB/cartodb/issues/11198
We need to filter the null values if the aggregation is not `COUNT`. We need a reference to the aggregation (through the dataview model). When the aggregation changes, new data is fetched, so when the new data is reset, we filter the models if aggregation meets the condition.
Could you take a look @alonsogarciapablo? Do you see a better approach?

Filter null values if aggregation is not COUNT for categories dataview.

---

examples/v4/leaflet-layergroup.html
src/geo/cartodb-layer-group-view-base.js
src/geo/gmaps/gmaps-cartodb-layer-group-view.js
src/geo/gmaps/gmaps-map-view.js
src/geo/gmaps/projector.js
src/geo/leaflet/leaflet-cartodb-layer-group-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map-view-factory.js
src/geo/map-view.js
src/vis/vis-view.js
test/spec/geo/fake-wax.js
test/spec/geo/geometry-views/shared-tests-for-multi-point-views.js
test/spec/geo/geometry-views/shared-tests-for-multi-polygon-views.js
test/spec/geo/geometry-views/shared-tests-for-multi-polyline-views.js
test/spec/geo/geometry-views/shared-tests-for-path-views.js
test/spec/geo/geometry-views/shared-tests-for-point-views.js
test/spec/geo/geometry-views/shared-tests-for-polygon-views.js
test/spec/geo/geometry-views/shared-tests-for-polyline-views.js
test/spec/geo/gmaps/gmaps-cartodb-layer-group.spec.js
test/spec/geo/gmaps/gmaps-map-view.spec.js
test/spec/geo/leaflet/leaflet-cartodb-layer-group-view.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/leaflet/leaflet-torque-layer-view.spec.js
test/spec/geo/map-view.spec.js
test/spec/geo/shared-tests-for-cartodb-layer-group-views.js
test/spec/geo/ui/search.spec.js
test/spec/geo/ui/tooltip.spec.js
themes/scss/entry.scss
themes/scss/map/map.scss

Part of https://github.com/CartoDB/cartodb.js/issues/1539.
- Map views manage/generate [it's own `div` element](https://github.com/CartoDB/cartodb.js/pull/1541/files#diff-546b824606bbde96318198869eb2de06R7) (`el` was being injected by the `vis-view` before). 
- Instances of CartoDBLayerGroupViewBase (LeafletCartoDBLayerGroupView and GMapsLayerGroupView) automatically [fetch tiles and setup interactivity when they are initialised](https://github.com/CartoDB/cartodb.js/pull/1541/files#diff-394491c3c8e791282436eb57ad5181c6R7) and the layerGroupModel has info (urls) about tiles/grids (eg: when a view is removed and re-rendered).
- Added [a bunch of tests](https://github.com/CartoDB/cartodb.js/pull/1541/files#diff-c1c98c4bc6a55dfe86034033cba4d625) that were missing.
**Acceptance:**
1. Checkout …

More prep work for Google Maps support

---

src/vis/vis-view.js

Fixes https://github.com/CartoDB/cartodb/issues/11264.
Bug was introduced here: https://github.com/CartoDB/cartodb.js/commit/def83a2bee7174b2c9a9c63739d8b1c504f5def0#diff-e825eba49cff0944452ad6d39e2ae16dL66
cc: @xavijam would you mind taking a look please?

InfowindowManager wasn't getting a visModel

---

src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map-view.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/map-view.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1553.
This was removed by mistake here: https://github.com/CartoDB/cartodb.js/commit/4300488a3708e7c77273b1e372f5be5de799d89f#diff-aaf2180ce09425b310a1186ac37bab76L23.
cc: @xavijam

Remove Leaflet's attributionControl by default

---

examples/v4/leaflet-layergroup-legends.html
src/geo/ui/legends/base/img-loader-view.js
src/geo/ui/legends/custom/legend-template.tpl
themes/scss/map/overlays.scss

prepare custom legends with images, it wasn't working properly before as it was only supported for svg
**custom legend with images (svg, and png), and circles**
before
after

add image support for custom legends beyond svg

---

src/geo/map.js
src/geo/map/layers.js
src/vis/vis.js
test/spec/geo/map.spec.js
test/spec/geo/map/layers.spec.js
test/spec/vis/vis.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/11137.
In BUILDER, when a layer was moved, we used to remove the layer and add it again in the proper position instead of doing that operation in CARTO.js. Why? I don't know, but let's do it properly!
Also, when a CartoDB layer is moved, we have to refresh the map, of course, thanks reload.

Adding moveCartoDBLayer function

---

src/geo/ui/legends/base/legend-title.tpl
test/spec/geo/ui/legends/choropleth/custom-legend-view.spec.js
test/spec/geo/ui/legends/choropleth/legend-view-spec.js

- Before:
- After:
CR: @piensaenpixel

Fixed problem with legend title length

---

themes/scss/vendor/leaflet.scss

There is a problem detected in Surface devices with the map panning. Check videos:
Before:
https://dl.dropboxusercontent.com/u/33489446/IMG_1050.MOV
After:
https://dl.dropboxusercontent.com/u/33489446/IMG_1049.MOV
cc @alonsogarciapablo @piensaenpixel @nobuti

Fixing problem related with Surface map pan

---

src/windshaft/map-base.js
test/spec/windshaft/map-base.spec.js

When no CDN templates are present in the response from Maps API we're trying to use the following subdomains:
- `[ '0', '1', '2', '3' ]` for HTTP requests
- `[ '' ]` for HTTPs requests
This was causing some errors because we're replacing the `{s}.` part of the URL that we're generating by and empty string.
This PR basically disables subdomains for those cases.
cc: @rochoa @donflopez

Do not try to use subdomains when no CDN templates are present

---

src/geo/leaflet/leaflet-map-view.js
src/geo/map.js
src/vis/vis-view.js
src/vis/vis.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/map.spec.js
test/spec/vis/vis-view.spec.js
test/spec/vis/vis.spec.js

Related ticket: https://github.com/CartoDB/support/issues/605
Basically we have noticed that Leaflet 1.0.3 doesn't need to set the center of the map when it is invalidated. It means, for example, when widgets list component appears and map gets stretched.
I'll review the code and make the acceptance with @ivanmalagon.
Then we will need to make changes in deep-insights in order to stop using the `centerMapToOrigin` deprecated function.
cc @alonsogarciapablo @donflopez @ivanmalagon

It is not necessary to reCenter the map after initialization

---

src/geo/map.js
src/geo/map/layer-model-base.js
src/vis/vis.js
test/spec/geo/map.spec.js
test/spec/geo/map/layer-model-base.spec.js
test/spec/vis/vis.spec.js

Related ticket in Builder: https://github.com/CartoDB/cartodb/issues/11910.
Trying to fix the problem above ^^^, we discovered that action parameters were not working properly when a layer was added or removed. So we have reviewed that and here we go!

11910 builder issue

---

src/geo/map/cartodb-layer.js
test/spec/geo/map/cartodb-layer.spec.js

Related ticket: https://github.com/CartoDB/support/issues/592 and https://github.com/CartoDB/cartodb/issues/11921.
Not sure how it happened, but we removed at some point the support for tooltip fields changes. That means, when a tooltip field was added/removed, the visualization was not reloaded and the user didn't see the changes.
With this change that behaviour is fixed.
cc @alonsogarciapablo when you see it.

When tooltip fields are modified, vis should be reloaded

---

src/geo/cartodb-layer-group.js
src/windshaft-integration/model-updater.js
src/windshaft/client.js
src/windshaft/map-base.js
test/spec/geo/cartodb-layer-group.spec.js
test/unit/windshaft-integration/model-updater.spec.js

This is a follow up on https://github.com/CartoDB/cartodb.js/pull/1607 (I had to revert one cleanup commit which broke some stuff). Since Maps API is now returning info about subdomains that should be used for tiles, grids, and attributes, we should just use those. If this info is not available, no subdomains will be used.
cc: @rochoa @donflopez

Clean up subdomains

---

src/windshaft/named-map.js
test/spec/windshaft/named-map.spec.js

This PR implements https://github.com/CartoDB/cartodb/issues/11838.
We are filtering the google basemap from the layers collection in order to set the json styles. This will work because we are assuming the first layer is always the basemap. See [this comment](https://github.com/CartoDB/support/issues/577#issuecomment-286424774) for more context.

Filter GMapsBase layer before to set styles.

---

src/geo/ui/infowindow-view.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1655.
It looks like this was only broken in Google Chrome. It was working fine on Firefox and Safari.

Do not pan map while scrolling down the infowindow

---

src/dataviews/dataview-model-base.js
src/dataviews/histogram-dataview/histogram-data-model.js

Related to https://github.com/CartoDB/cartodb/issues/12177
There was a 'race condition' when changing the number of bins in a timeseries widget. If a change response delays and then we request another number of bins, the datamodel enters a spiral of request the data for those two numbers till infinity.
This fix is independent of the original issue cited but has appeared while developing it.
Related PR:
- cartodb: https://github.com/CartoDB/cartodb/pull/12246
- cartodb.js: https://github.com/CartoDB/cartodb.js/pull/1665
- deep-insights.js: https://github.com/CartoDB/deep-insights.js/pull/547

Time series context menu

---

doc/getting_started.md
doc/static_maps.md

@oriolbx , related to [Docs issue#1212](https://github.com/CartoDB/docs/issues/1212) (via reported SB issue).
- Okay, first things first. I confirmed that there was a broken hyperlink. I edited the description of `layerSource`, under the `cartodb.Image(layerSource[, options])` section; to include all the details reported by the user. I also linked to the correct doc location and the example he found on Github.
- The bigger issue is how to handle all the existing examples that appear in the Static Maps API doc (in regards to `cartodb.image`).  Do we need to update all the examples and add missing configurations?  For now, let me know if this update is correct, then I'll loop in a developer to figure out how to move forward with the rest of the examples.

doc updated related to SB12619947

---

src/dataviews/histogram-dataview-model.js

Related to https://github.com/CartoDB/cartodb/issues/11536
While doing acceptance we found this bug: when changing the column used in a histogram widget, there is no notification to the original data model. This way, when showing totals there were no changes at all.
Furthermore, in the cartodb associated PR, after a validation error in the column type, it prevented to fetch the right data when choosing a proper column.
We dug in `git blame` to find a reason for `once` to be there but it doesn't make any sense. The dataview model is changing its URL, so it's backing data model must change it as well.

Change histogram data URL properly with column changes

---

src/api/create-vis.js
src/geo/geocoder/mapzen-geocoder.js
test/spec/geo/geocoder/mapzen-geocoder.spec.js
test/spec/geo/ui/search.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1669.
`createVis` now requires the `mapzenApiKey` option for the Search bar to work properly.
Usage example:
```
cartodb.createVis('map', vizjson, {
mapzenApiKey: 'MAPZEN_API_KEY'
})
```
If Mapzen's API Key is not provided or is no longer valid, the library will log an error in the console and the map will not be panned or zoomed when a user searches though the UI.
cc: @juanignaciosl

Customisable Mapzen's API Key

---

src/core/view.js
src/dataviews/dataview-model-base.js
src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

Part of https://github.com/CartoDB/cartodb/issues/12179
In this PR we made two things:
- Add the calculation of the total amount of items and the filtered amount of items in the histogram dataview model..
- Added `stopListening` to the core `View` in case you use `listenTo` instead of `on` (One side effect spotted while doing the task).

12179 time series selected text

---

src/api/sql.js
test/spec/api/sql.spec.js

This PR improves the SQL fetch queries to let them be cancellable. The default option is `false`, as the same as it is now.
```
var sql = new SQL({
cancellable: true
});
```

Cancellable sql fetch.

---

package.json
src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js
src/geo/leaflet/leaflet-layer-view-factory.js

This removes the dependency on tangram-cartocss, but more important,
the validation will happen against the same parser version the rendering
component is using, so no need to keep the versions updated in two different
libraries. Win-win.

[Vector] Use tangram.cartodb method to validate CartoCSS

---

.gitignore
src/geo/map.js
src/geo/map/cartodb-layer.js
test/spec/geo/map.spec.js
test/spec/geo/map/cartodb-layer.spec.js

Regarding to #1697.
https://team.carto.com/u/javi/builder/74bb971d-5554-459a-b67d-92834dec63a0/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B50.31653121149523%2C6.892890930175782%5D%2C%22sw%22%3A%5B50.395825267023824%2C7.019577026367188%5D%2C%22center%22%3A%5B50.35619479483569%2C6.956233978271485%5D%2C%22zoom%22%3A13%7D%7D 
This map was rendered in . `raster mode`  because `"estimatedfeaturecount=not-available"`
this was strange because the estimatedFeatureCount was included for every layer.
After doing some research we found that the `hasEstimatedFeatureCount` function in the map object has a bug when the `layerModel.getEstimatedFeatureCount()` returns 0. (For example when the layer is hidden)
This PR changes the `layerModel.getEstimatedFeatureCount()`. (This function is now ignoring the …

1697 fix feature count

---

src/geo/leaflet/leaflet-layer-view-factory.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1706

Use info instead of error when vector can't render

---

src/api/create-vis.js
src/api/vizjson.js
test/spec/api/vizjson.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/12513
We're having problems with the vectors in Builder, in the editor view we override the vizJSON in the rails controller to force raster, but in the datasets view we make a call to the API directly, so it doesn't work.
We were using a `vector: false` option in `deep-insights-integration` which we thought forced the raster mode, but debugging I've realised it does nothing, but I liked that approach so I implemented it to use it in the datasets view, and also, when we split the front/back it will work in the editor view too.
Pinging @rochoa since my knowledge about vector/raster is pretty limited

Allow overriding vizJSON with options in create vis

---

examples/base.html
examples/viz/viz1.json
examples/viz/viz2.json

This PR adds a demo html file where you can easy play with `cartodb.js` and load different `viz.json` files improving manual testing and development speed.

Add Playground html to easy testing

---

src/geo/ui/infowindow-model.js
test/spec/geo/ui/infowindow-model.spec.js

Sending 'null' instead of `null` makes it hard to use conditional statements if `showEmptyFields` is set to true
Sending `null` literal still renders as 'null' without conditionals, but advanced users are able to parse this in a more granular way.

Support for mustache conditional statements

---

themes/scss/infowindow/_cartodb-infowindow-default.scss
themes/scss/tooltip/_cartodb-tooltip-default.scss

This PR is related to https://github.com/CartoDB/support/issues/935. It applied a more modern break word technique for infowindows and popups.

Applied modern word break.

---

themes/scss/infowindow/_cartodb-infowindow-default.scss
themes/scss/tooltip/_cartodb-tooltip-default.scss

Related to https://github.com/CartoDB/cartodb/pull/12833
The next solution is using word-wrap (overflow-wrap), another property to specify whether or not the browser may break lines within words.

Overflow wrap.

---

.gitignore
.travis.yml
README.md
jsdoc.json
package.json
scripts/deploy-to-gh-pages.sh
src/core/sanitize.js
src/dataviews/dataview-model-base.js

Related to: #1741
With each v4 commit, the API documentation is built with [JSDoc](http://usejsdoc.org/) and commited to [gh-pages branch](https://github.com/CartoDB/cartodb.js/commits/gh-pages). No generated docs in v4 branch!
This is the main page: http://cartodb.github.io/cartodb.js/

Build & deploy Docs automatically to gh-pages

---

src/geo/leaflet/leaflet-layer-view-factory.js

We want to avoid logging "Unsupported CartoCSS" errors, since they are not really errors.

Filter log, to avoid treating "Unsupported CartoCSS" as errors

---

src/geo/map/popup-fields.js
src/geo/ui/tooltip-model.js

This PR is related to https://github.com/CartoDB/cartodb/issues/11430.
Until now, we only check for names, but no titles. So when the user
selected a field, and later, changed the title, the model wasn't updated
because we only looked for fields' names.

Take account of title in order to update infowindow models.

---

src/vis/layers-factory.js
test/spec/vis/layers-factory.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/12881#issuecomment-333042882 until a more definitive fix is implemented (https://github.com/CartoDB/cartodb/issues/12885).
I opened an issue to bring back that check (https://github.com/CartoDB/cartodb.js/issues/1791).

Remove `source` attribute check for "CartoDB" and "Torque" layers

---

src/windshaft/map-serializer/anonymous-map-serializer/layers-serializer.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/layers-serializer.spec.js

`layers-serializer` should ignore layers that are not supported by Maps API (eg: layers of type `GMapsBase` instead of throwing an error that breaks the map.
**Acceptance Criteria**
1. Checkout this branch and run `grunt dev`.
2. Visit http://localhost:9001/examples/gmaps-geometry-editor.html.
3. Map should load and you shouldn't see any errors in the console.
cc: @IagoLast @Jesus89

Layers serializer ignores layers not supported by Maps API

---

src/analysis/analysis-service.js
src/vis/vis.js
src/windshaft-integration/model-updater.js

* Do not use analysisCollection when reseting models in the analysisPoller (extract sources from layers and dataviews instead).
* Remove code-duplication, move getUniqueNodes to the AnalysisService

Remove analysis collection analysis poller pr0

---

src/geo/gmaps/gmaps-map-view.js
src/geo/gmaps/projector.js
src/geo/leaflet/leaflet-map-view.js
test/spec/geo/geometry-views/shared-tests-for-path-views.js

Related to: #1798
The issue is that gmaps projection in the projector is not ready when `latLngToPixel`and `pixelToLatLng`methods are called and they return always (0, 0) failing some tests.
More precisely: in the polygons edition tests (6 tests) the middle points are not added in the coordinates because the `computeMidLatLng` method calls `mapView.latLngToContainerPoint` that returns (0, 0) when the projection is not ready. So no middle points in the coordinates list, no tests passed.
It depends on the platform. In Chrome when all the tests are executed they pass. If you run some tests individually they fail. In Firefox the 6 tests fail when all tests are executed, as in Jenkins.
Changes to solve the issue:
- Refactor of Projector. Remove _ready method trick, use idle event instead
- …

Fix gmaps tests

---

src/geo/map/cartodb-layer.js
src/geo/map/torque-layer.js
test/spec/geo/map/shared-for-interactive-layers.js

[CartoDB|Torque].prototype.update will raise an error when given a `source` attr.
cc: @IagoLast @Jesus89

Source cannot be updated via [CartoDB|Torque].prototype.update

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

Related to https://github.com/CartoDB/cartodb/issues/12945
We need to send the bins info when `own_filter` is set for histogram dataviews. If not, a change in bins can be parsed, resulting in an unwanted map instantiation and closing the zoom view in the widget.

Send bins when own_filter is set

---

src/analysis/analysis-service.js
test/spec/analysis/analysis-service.spec.js

https://github.com/CartoDB/support/issues/1091
----
This PR fixes the `preview map` functionality in dataset view. With the latest changes, it didn't show anything.

Fix preview map functionality

---

src/geo/map/legends/legend-model-base.js
src/geo/map/legends/static-legend-model-base.js
test/spec/geo/map/legends/static-legend-model.spec.js

This PR fixes a regression introduced recently that breaks static legends (custom, torque, custom-choropleth...etc)
Static legends never go into 'loading' state, this was prevented before with a base class that overrode the handler for vis:reload. Because there were no tests, it went unnoticed with the recent refactor.
I added a small spec just to be safe in the future 🤞

fix regression for static legends

---

src/windshaft/response.js
test/spec/engine.spec.js
test/spec/windshaft/response.spec.js

Related to: https://github.com/CartoDB/cartodb-platform/issues/3709
---
The mock server response used in the unit tests was wrong so we couldn't catch this error.
This PR:
- Fixes the unit tests using a mocked server response where cdn_url is not inside the metadata object.
- Fixes the ResponseWrapper to use  `serverResponse.cdn_url` inside `serverResponse.metadata. cdn_url`

Use cdn_url in the server response wrapper

---

examples/v4/_style.css
examples/v4/basic.html
examples/v4/bounding-box-filter.html
examples/v4/category-dataview.html
examples/v4/errors.html
examples/v4/formula-dataview.html
examples/v4/interactivity.html
src/api/v4/client.js
src/api/v4/error.js
src/api/v4/events.js
src/api/v4/source/dataset.js
src/api/v4/source/sql.js
src/api/v4/style/cartocss.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/dataview/category.spec.js
test/spec/api/v4/dataview/formula.spec.js
test/spec/api/v4/layer/layer.spec.js
test/spec/api/v4/leaflet/layer-group.spec.js
test/spec/api/v4/source/dataset.spec.js
test/spec/api/v4/source/sql.spec.js
test/spec/api/v4/style/cartocss.spec.js

#1869
----
- Client throws cartoErrors wrapped from engine errors.
- `.addLayer` and `.addDataview` return a promise, if those promises are rejected the parameter is a CartoError
- Add an error example with a code snippet and description.
- Update carto.events doc, use a custom namespace with constants instead enum
[![https://gyazo.com/cb4c6c96d4c9f31c7e1dc87e6f2ff5dd](https://i.gyazo.com/cb4c6c96d4c9f31c7e1dc87e6f2ff5dd.gif)](https://gyazo.com/cb4c6c96d4c9f31c7e1dc87e6f2ff5dd)

1869 error handling

---

src/dataviews/helpers/histogram-helper.js
src/dataviews/histogram-dataview-model.js
src/dataviews/histogram-dataview/histogram-data-model.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/dataviews/histogram-dataview/histogram-data-model.spec.js

Related to https://github.com/CartoDB/cartodb/issues/13070
----
This PR removes all code that applied offset to timestamps in histogram dataview. See related issue for more details.

Parse histogram dataview timestamps as UTC

---

examples/public/time-series-dataview.html

The Timeseries example shows the EPOCH timestamps.
This PR formats them to show the years instead.

Format TS example years

---

examples/public/gmaps/single-layer.html
src/api/v4/client.js
src/api/v4/index.js
src/api/v4/native/google-maps-map-type.js
src/api/v4/native/leaflet-layer.js
src/api/v4/native/trigger-layer-feature-event.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/native/google-maps-map-type.spec.js
test/spec/api/v4/native/leaflet-layer.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1734
**NOTE**
Now you need to pass the map to the get function because of WAX:
```js
var map = new google.maps.Map(document.getElementById('map'), {
zoom: 10,
center: {lat: 41.850, lng: -87.650}
});
var mapType = client.getGoogleMapsMapType(map);
map.overlayMapTypes.push(mapType);
```
This could be optimized in the future when WAX is removed.

Add getGoogleMapsMapType function

---

src/windshaft-integration/legends/rule-to-choropleth-legend-adapter.js
test/spec/windshaft-integration/legends/rule-to-choropleth-legend-adapter.spec.js

If we receive just one filter we're not showing the ramp color properly
because the `linear_gradient` css property in the template need two
values so we're going to pass the same value and legend twice

Fix Choropleth legend with one bucket

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

We're redesigning how the node info is showed in the widgets and we need to know if the dataview is of type source.

Add .isSourceType() to dataview-model-base

---

package.json

Fixes #1828
This commit adds our rebranded name and a link to our cartodb.js
docs. It also removes the contact email, since it's not compulsory
and is a 'foo' value.

Improve author information

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

We need to remove the category stringification to distinguish between numeric categories and string categories that contains numbers.

Remove category value stringify

---

package.json
src/geo/ui/legends/bubble/legend-template.tpl
src/vis/vis-view.js
test/spec/geo/ui/legends/bubble/legend-view.spec.js
themes/scss/map/_attributions.scss
themes/scss/map/_overlays.scss

Related to: https://github.com/CartoDB/cartodb/issues/13393
This PR renders the legends view outside of Carto.js views if the class `js-embed-legends` is found, not the best approach but works for now until we create a public API for legends in v4
Extras
------
- Fix "Allow hover on map elements beneath CDB-OverlayContainer". https://github.com/CartoDB/cartodb/issues/13341

Append legends view if js-embed-legends is found

---

src/api/create-vis.js

When migrating the dashboard to builder (which uses cartodb.js v4 now) we found a problem with the `user feed` view, where you could scroll the map with the trackpad/mouse wheel. I've found out it was because of this:
```
vizjson.options.scrollwheel = options.scrollwheel || vizjson.options.scrollwheel;
```
In the `vizjson` the option is true, and why are trying to override it with `false`, which is impossible using an `||`.

Override scrollwheel if it's boolean

---

examples/examples.json
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-order-leaflet.html
package.json
src/api/v4/client.js
src/api/v4/error-handling/error-list/validation-errors.js
src/api/v4/layer/layer.js
src/api/v4/layers.js
src/api/v4/native/google-maps-map-type.js
src/api/v4/native/leaflet-layer.js
src/api/v4/native/trigger-layer-feature-event.js
src/engine.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/layer/layer.spec.js
test/spec/engine.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1982

Define layers order

---

package.json
src/api/v4/client.js
src/api/v4/filter/bounding-box-leaflet.js
src/geo/leaflet/leaflet-map-view.js

Set Leaflet `zoomAnimationThreshold` to 1000 (in the internal API) to avoid unnecessary gray background flashes.

Set Leaflet zoomAnimationThreshold to 1000 (internal only)

---

examples/internal/basemap-selector.html
examples/internal/gmaps-geometry-editor.html
examples/internal/leaflet-geometry-editor.html
examples/internal/leaflet-vector.html
examples/internal/search-geocode.html
examples/internal/vizjson.html
examples/public/filters/bounding-box-leaflet.html
examples/public/filters/custom-bounding-box-leaflet.html
examples/public/layers/change-feature-columns-leaflet.html
examples/public/layers/change-order-leaflet.html
examples/public/layers/change-source-leaflet.html
examples/public/layers/change-style-leaflet.html
examples/public/layers/feature-click-leaflet.html
examples/public/layers/feature-over-out-leaflet.html
examples/public/layers/layer-with-aggregation-leaflet.html
examples/public/layers/layer-with-zoom-options-leaflet.html
examples/public/layers/multilayer-leaflet.html
examples/public/layers/single-layer-leaflet.html
examples/public/misc/boilerplate-leaflet.html
examples/public/misc/edit-sql-cartocss-leaflet.html
examples/public/misc/error-handling-leaflet.html
examples/public/misc/guide-leaflet.html
examples/public/misc/legends-leaflet.html
examples/public/misc/populated-places-leaflet.html
examples/public/misc/popups-leaflet.html

I missed the examples when updating Leaflet to version 1.3.1 here: https://github.com/CartoDB/cartodb.js/pull/2037

Update all examples to Leaflet1.3.1

---

examples/public/misc/popups-gmaps.html
examples/public/misc/popups-leaflet.html

Related to: https://github.com/CartoDB/cartodb.js/issues/2043
---
In this PR both popup examples (leaflet/gmaps) are updated in order to check if the popup/infowindow is opened only to call the open function:
```js
if (!popup.isOpen()) {
popup.openOn(map);
}
```
```js
if (!infowindow.map) {
infowindow.open(map);
}
```

Fix popup examples for polygons

---

src/engine.js

Just to not fill trackjs with this error.
When Auth API is available, we can force this error and not letting it pass through. In this moment, we're flooding trackjs and console with this error in legit cases where we do not provide a key.

Warn instead of error if no API key

---

examples/public/filters/bounding-box-gmaps.html
examples/public/layers/change-feature-columns-gmaps.html
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-source-gmaps.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/feature-click-gmaps.html
examples/public/layers/feature-over-out-gmaps.html
examples/public/layers/layer-with-aggregation-gmaps.html
examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/multilayer-gmaps.html
examples/public/layers/single-layer-gmaps.html
examples/public/misc/boilerplate-gmaps.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/guide-gmaps.html
examples/public/misc/legends-gmaps.html
examples/public/misc/populated-places-gmaps.html
examples/public/misc/popups-gmaps.html
grunt/tasks/jasmine.js
src/core/util.js
test/spec/api/v4/client.spec.js
test/spec/core/util.spec.js

A recent deploy of a new GMaps experimental version provokes errors, both in our specs and in our API examples.
This PR freezes the GMaps version to the currently stable one, `v=3.30`.

Freeze GMaps script version

---

.gitignore
NEWS.md
RELEASING.md
bower.json
examples/gmaps/gmaps_driving_directions_plus_sql_api.html
examples/gmaps/gmaps_heatmap_plus_sql_api.html
examples/gmaps/gmaps_satellite.html
examples/gmaps/gmaps_with_torque.html
examples/gmaps_driving_directions_plus_sql_api.html
examples/gmaps_force_basemap.html
examples/gmaps_heatmap_plus_sql_api.html
examples/gmaps_satellite.html
examples/gmaps_with_torque.html
examples/tutorial-google-driving-2.html
examples/tutorial-google-heatmap-2.html
examples/tutorial-google-heatmap.html
examples/tutorials/tutorial-google-driving-2.html
examples/tutorials/tutorial-google-heatmap-2.html
examples/tutorials/tutorial-google-heatmap.html
grunt/tasks/jasmine.js
package.json
src/cartodb.js
test/SpecRunner-src.html
test/SpecRunner.html
test/demos/geo/google_maps.html

A recent deploy of a new GMaps experimental version provokes errors, both in our specs and in our API examples.This PR freezes the GMaps version to the currently frozen one, v=3.30.

Freeze Google Maps version to v3.3.0

---

src/geo/map/torque-layer.js

re: https://github.com/CartoDB/support/issues/1294
- cartodb.js: https://github.com/CartoDB/cartodb.js/pull/2057
- cartodb: https://github.com/CartoDB/cartodb/pull/13590
update cartodb.js dependencies, to add `marker-size` to layer cartocss props to reinstantiate torque map

add marker size to layer cartocss props to reinstantiate torque map

---

src/geo/map/layers.js
src/geo/ui/legends/legends-view.js
test/spec/geo/map/layers.spec.js
test/spec/geo/ui/legends/legends-view.spec.js

Related to https://github.com/CartoDB/support/issues/1379
This PR adds a custom `layerMoved` event to refresh legends when `moveCartoDBLayer` is used.

Re-render legends when layers order is changed

---

src/dataviews/histogram-dataview/histogram-data-model.js
test/spec/dataviews/histogram-dataview/histogram-data-model.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/13706
Cartodb PR: https://github.com/CartoDB/cartodb/pull/13705
This PR adds a flag when the `histogram-data-model` has been fetched to be able to handle event bindings related to it in Builder.

Add hasBeenFetched flag to histogram

---

src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/dataviews/histogram-dataview-model.js
src/engine.js
src/vis/vis.js
test/helpers/mockFactory.js
test/spec/api/v4/dataview/category.spec.js
test/spec/api/v4/dataview/histogram.spec.js
test/spec/api/v4/dataview/time-series.spec.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/dataviews-factory.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/engine.spec.js
test/spec/fixtures/engine.fixture.js
test/spec/geo/cartodb-layer-group.spec.js
test/spec/geo/gmaps/gmaps-torque-layer-view.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
test/spec/geo/leaflet/leaflet-torque-layer-view.spec.js
test/spec/geo/map-view.spec.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/geo/map/plain-layer.spec.js
test/spec/geo/map/tile-layer.spec.js
test/spec/geo/map/torque-layer.spec.js
test/spec/geo/ui/overlays-view.spec.js
test/spec/vis/infowindow-manager.spec.js
test/spec/vis/tooltip-manager.spec.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/dataviews-serializer.spec.js

Related to https://github.com/CartoDB/cartodb.js/issues/2071
----
This PR propagates the credentials set in `carto.client` to dataviews. It fixes a bug, where the dataviews didn't had the API key and then they build URLs with no keys.
*Public API*
- Create all type of widgets against a private dataset.
- Use an API key [1] with SQL select and MAPS permission for that dataset.
- Check that the widgets return data. No 403 must be received.
- Create all type of widgets against a public dataset.
- Use the `default_public` key.
- Check that widgets work.
*Builder*

Propagate API keys to dataviews in public API

---

src/api/v4/client.js

I have [this example](https://codepen.io/jsanz/pen/MVmNpm) running against a current carto instance, but was hesitant to use a real one since that carto instance can disappear anytime. I think it's worth adding that example to make clear that the URL needs the `/user/username`, even the console error is meaningful enough to be easy to fix, so not really strong on this suggestion :smile:

Added example for the url server parameter

---

CHANGELOG.md
DEVLOG.md
README.md

Related to https://github.com/CartoDB/cartodb.js/issues/2077
----
This PR just adds:
- the current content of DEVLOG.md, that contains all merge and tag information for both the internal and public API.
- Four notes to CHANGELOG.md. The ones that are important since the first version of CHANGELOG.md. Take into account that this file is the starting point so no detailed info is needed now, only a big picture of what CARTO.js v4 enables.
- a changelog reference to README.
Please review if you miss something.

Check README.md

---

.github/ISSUE_TEMPLATE.md
.github/stale.yml

This PR sets stale bot for CARTO.js.
It adds an issue template as well.

Enable stale bot

---

package.json
src/geo/ui/infowindow-view.js

Related to CartoDB/cartodb#13808
Popups with just images don't look good on IE and Edge, because they don't support the CSS clip-path property, used on the hook.
This PR provides a fallback, removing the clipped image and the hook itself.
The result looks like this (on IE11):

Better popups with just images on IE and Edge

---

examples/public/filters/bounding-box-gmaps.html
examples/public/layers/change-feature-columns-gmaps.html
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-source-gmaps.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/feature-click-gmaps.html
examples/public/layers/feature-over-out-gmaps.html
examples/public/layers/layer-with-aggregation-gmaps.html
examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/multilayer-gmaps.html
examples/public/layers/single-layer-gmaps.html
examples/public/misc/boilerplate-gmaps.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/guide-gmaps.html
examples/public/misc/legends-gmaps.html
examples/public/misc/populated-places-gmaps.html
examples/public/misc/popups-gmaps.html
grunt/tasks/jasmine.js
package.json
src/core/util.js
test/spec/api/v4/client.spec.js
test/spec/core/util.spec.js
test/spec/geo/geometry-views/shared-tests-for-polygon-views.js
test/spec/geo/geometry-views/shared-tests-for-polyline-views.js

Related to https://github.com/CartoDB/carto.js/issues/2067
**Context**
- Current tests and examples are now working fine with v3.32 (experimental)
- We have decided though to upgrade to v3.31 (stable) and wait for v3.32 to stabilize
---
**Tasks**
**Acceptance**

Upgrading carto.js to gmaps v3.31

---

src/geo/map/cartodb-layer.js

This methods help to solve https://github.com/CartoDB/support/issues/1399

Add new methods to cartoDB layer

---

src/api/v4/client.js
src/api/v4/layers.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/layers.spec.js

This PR fixes `removeLayers`.
We were removing elements from the same array that we were traversing. The side effect of that is that the internal array was not completely emptied so next time the user instantiate the map, it has layers that were supposed to be removed.
This PR adds also missing tests. Neither `client.removeLayers` nor `layers.remove` had any.

Fix remove layers

---

package.json

We need to rename the package to be able to have both this version and the public one on builder.
Sorry for the lengthy Code Review

Rename package to internal-carto.js

---

themes/scss/map/_overlays.scss

Related to: https://github.com/CartoDB/support/issues/1521
This PR changes how the paddings in legends work so perfect-scrollbar doesn't get activated when it shouldn't.

Fix legends paddings / margins

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Related to: https://github.com/CartoDB/onpremises/issues/510
We were having problems with callbacks not being called because of canceled requests (see the related issue for more info).
This PR fixes that by creating a hasBinds flag which we set to true after setting them, and calling the _fetch method in both, the _initialFetch and _onMapBoundsChanged methods which were the ones conflicting.

Avoid problems with cancelled requests in dataviews

---

docs/guides/01-quickstart.md
docs/support/03-error-messages.md

Related issues: 
- Dataview error table dangling column https://github.com/CartoDB/developers/issues/297
- carto.js quickstart app skeleton quote consistency https://github.com/CartoDB/developers/issues/295

Small typo fixes for dev center docs

---

examples/internal/basemap-selector.html
examples/internal/gmaps-geometry-editor.html
examples/public/filters/bounding-box-gmaps.html
examples/public/layers/change-feature-columns-gmaps.html
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-source-gmaps.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/feature-click-gmaps.html
examples/public/layers/feature-over-out-gmaps.html
examples/public/layers/layer-with-aggregation-gmaps.html
examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/multilayer-gmaps.html
examples/public/layers/single-layer-gmaps.html
examples/public/misc/boilerplate-gmaps.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/guide-gmaps.html
examples/public/misc/legends-gmaps.html
examples/public/misc/populated-places-gmaps.html
examples/public/misc/popups-gmaps.html
grunt/tasks/jasmine.js
src/core/util.js
test/spec/api/v4/client.spec.js
test/spec/core/util.spec.js

There are several issues, regarding to the new gmaps v3.32 version, as noticed in https://github.com/CartoDB/carto.js/issues/2067
A fix is needed for current **v4** and **v3** versions.
Tasks:

Update gmaps to v3.32 in v4 [WIP]

---

examples/public/filters/bounding-box-gmaps.html
examples/public/layers/change-feature-columns-gmaps.html
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-source-gmaps.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/feature-click-gmaps.html
examples/public/layers/feature-over-out-gmaps.html
examples/public/layers/layer-with-aggregation-gmaps.html
examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/multilayer-gmaps.html
examples/public/layers/single-layer-gmaps.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/guide-gmaps.html
examples/public/misc/legends-gmaps.html
examples/public/misc/populated-places-gmaps.html
examples/public/misc/popups-gmaps.html

Fixes https://github.com/CartoDB/carto.js/issues/1995
This PR substitutes all `const map` with `var map` in Google Maps examples.
This is a bug in Safari. You can't have an element with an id and a const variable with the same name.

Fix iOS examples

---

test/spec/geo/geocoder.spec.js
vendor/wax.cartodb.js

Related issue: https://github.com/CartoDB/carto.js/issues/2067
This PR upgrades the wax cache to record the number of calls to `getTile`.
Starting with Google Maps v3.32 (with a new renderer), Gmaps provides a smoother zoom. A side effect is that they call `getTile` several times for the same tile, releasing them as well. We have a cache in wax that removes the `<img>` from the DOM, so we were removing a required tile.
This is the sequence during a pinch zoom in mobile:
```
a: start zooming.
b: getTile(32)
c: stop zooming.
d: getTile(32)
e: releaseTile(32) (the one required on b) -> we remove it from the DOM.
f: the tile disappear.
```
Now we track the number of calls to `getTile`, à la reference counting, and we only remove the `<img>` from the DOM if there are no active calls.

Fix Gmaps 3.32

---

src/geo/ui/legends/base/legend-view-base.js
src/geo/ui/legends/bubble/legend-view.js
src/geo/ui/legends/layer-legends-template.tpl
themes/scss/map/_overlays.scss

This PR fixes margins and spacing on legends, specially on Bubble legend.
The problem was that the legend was taking more space than what it has assigned due to absolute positioning. So the margins were collapsed, appearing misaligned.
See https://github.com/CartoDB/support/issues/1566
Related to https://github.com/CartoDB/support/issues/1566

Fix margins on legends

---

examples/examples.json
examples/public/misc/hexagon-aggregation-gmaps.html
examples/public/misc/hexagon-aggregation-leaflet.html

Add Leaflet and Gmaps example of point aggregation with hexagon aggregation

add hexagon aggregation example

---

themes/scss/map/_overlays.scss

Fix choropleth legends margin

---

src/api/v4/client.js
src/api/v4/native/leaflet-layer.js
test/spec/api/v4/native/leaflet-layer.spec.js

Related to: https://github.com/CartoDB/carto.js/issues/2125
This PR allows passing options to `getLeafletLayer` to override our default options.
Open the `single-layer-leaflet.html` example and use this code:
```html
<script>
const map = L.map('map').setView([30, 0], 1);
map.scrollWheelZoom.disable();
L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}.png', {
maxZoom: 18,
noWrap: true
}).addTo(map);
const client = new carto.Client({
apiKey: 'default_public',
username: 'cartojs-test'
});
const source = new carto.source.Dataset(`
ne_10m_populated_places_simple
`);
const style = new carto.style.CartoCSS(`
#layer {
marker-width: 7;
marker-fill: #EE4D5A;
marker-line-color: #FFFFFF;
}
`);
const layer = new carto.layer.Layer(source, style); …
```

Add options to getLeafletLayer

---

src/dataviews/helpers/histogram-helper.js
test/spec/dataviews/helpers/histogram-helper.js

To sync with the windshaft dateIntervalQueryTpl query at https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/dataview/histograms/date-histogram.js#L131-L132.
Fixes #2161

Add century and millenium to date aggregation

---

src/geo/map/cartodb-layer.js
test/spec/api/v4/layer/layer.spec.js
test/spec/geo/map/cartodb-layer.spec.js

Related to: https://github.com/CartoDB/carto.js/issues/2089
This PR changes how we check if a layer is interactive or not.
The problem is that we were checking `this.getInteractiveColumnNames().length > 1` because we always add `cartodb_id` by default, so when adding it manually the check was false.

Fix interactivity when only 'cartodb_id' is selected

---

src/api/v4/client.js
test/spec/api/v4/client.spec.js

Related to: https://github.com/CartoDB/carto.js/issues/2119
This PR calls `dataview.disable()` in `removeDataview`.
- Use the example provided in the issue
- Open the map and check that moving the map calls the api
- Click in the _Remove widget_ button
- Check that moving the map doesn't call the api

Fix removeDataview

---

docs/guides/quickstart-example.html

The example in the quickstart guide is not working because we're using `YOUR_API_KEY` instead of `default_public` as API key
https://carto.com/developers/carto-js/guides/quickstart/#conclusion

Fix API key in quickstart example

---

src/api/v4/layer/layer.js
test/spec/api/v4/layer/layer.spec.js

Related to: https://github.com/CartoDB/carto.js/issues/2004
This PR adds `visible` to the layer options so people can create layers that are hidden by default.
It also improves the examples a little bit.

Add 'visible' to layer options

---

src/geo/torque-layer-view-base.js
test/spec/geo/torque-layer-view-base.spec.js

Related to: https://github.com/CartoDB/support/issues/1038
This PR uses the proper query from the source instead of a simple one. This fixes torque layers when analyses are made.

Fix torque

---

src/geo/leaflet/leaflet-map-view.js

Get rid also of the tiles borders during zoom transitions with the +, - buttons.
| Bug |
|---|
| ![bug-buttons-zoom](https://user-images.githubusercontent.com/2227572/42696589-eb9b86c8-86b8-11e8-9663-3b4c009d6f38.gif) |
| Fix |
|---|
| ![fix-buttons-zoom](https://user-images.githubusercontent.com/2227572/42696627-0a2faac4-86b9-11e8-827b-1ed17d97c2cf.gif) |

Use setView instead of flyTo to improve zoom transitions

---

examples/acceptance/displaced-popups.html
src/geo/leaflet/leaflet-cartodb-layer-group-view.js

Related issue: https://github.com/CartoDB/support/issues/1659
So this has been broken since we introduced zera, but probably never seen it because we almost never have maps that are not full screen (iframes work just fine). I've attached an example that would be broken with the previous implementation if you scroll vertically or horizontally. Feel free to try it out on master.
I assume there's some difference between what we're getting with zera and what we used to get with wax. The thing is, there's apparently a Leaflet method that retrieves the containerPoint from the layerPoint, it seems to work perfectly.

Fix popups/featureClick positions when scrolled

---

src/api/v4/index.js
src/engine.js
src/index.js
test/spec/engine.spec.js

**promise-polyfill** was included but not linked from `engine.js`, causing the reported exception. Adding `var Promise = require('promise-polyfill');` in that file fixed the error, but then another error raised, as `Promise` is also used from **whatwg-fetch** polyfill
Add `Promise` to `window`, so it is widely available and no errors are thrown in IE11.
> Note: This should be a patch, to be deployed to npm and our CDN

Fix `Promise is undefined` in IE11

---

package.json
src/vis/vis-view.js
test/spec/api/v4/source/dataset.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/14115
This PR fixes a bug introduced in https://github.com/CartoDB/zera/commit/317a82f61b137299f6b959b2addc65c52dd11df0 while trying to fix https://github.com/CartoDB/carto.js/issues/1952
The problem is that Builder is listening directly to document click events, so it closes the edit button as soon as soon as it's shown. Instead of stopping the event propagation to avoid that error we're going to handle it using carto.js events and stop listening to document click.

Fix safari drag problem

---

src/api/v4/filter/base-sql.js
src/api/v4/filter/category.js
src/api/v4/filter/filters-collection.js
src/api/v4/filter/range.js
test/spec/api/v4/filter/base-sql.spec.js
test/spec/api/v4/filter/category.spec.js
test/spec/api/v4/filter/filters-collection.spec.js

This PR fixes a bug and introduces several improvements in filters described in https://github.com/CartoDB/carto.js/issues/2186.
There were a problem when combining several filters, when having one of them empty. So, now the problem is gone. You can:
```js
const roomTypeFilter = new carto.filter.Category('room_type', { in: getSelectedRoomTypes() });
const emptyFilter = new carto.filter.Category('price', { });
const source = new carto.source.SQL('SELECT * FROM table');
source.addFilters([ roomTypeFilter, emptyFilter ]);
```
Filters now have `.resetFilters()` method to remove all filter conditions and leave it empty.
```js
const roomTypeFilter = new carto.filter.Category('room_type', { in: getSelectedRoomTypes() });
roomTypeFilter.resetFilters();
```
From now on, we're going to allow …

Filters improvements

---

CHANGELOG.md
src/api/v4/filter/category.js
src/api/v4/filter/range.js
test/spec/api/v4/filter/category.spec.js
test/spec/api/v4/filter/range.spec.js

In a previous PR we introduced subquery parameter in NOT IN and IN category filters. I noticed that it can be passed in to another filters such as GT, GTE, LT, etc... So this PR add that features :)

Allow subqueries parameter in Range filters and more Category Filters

---

src/util/get-object-value.js

Fix undefined behaviour in `get-object-value.js`.
I found a case that the function was returning `defaultValue` instead of `value` because it was 0. The return condition behaviour is different to what it was supposed to do.

Return default value only if value is undefined in get-object-value

---

CHANGELOG.md
src/api/v4/client.js
test/spec/api/v4/client.spec.js

https://github.com/CartoDB/carto.js/issues/2198
---
- Fixed `{username}` pattern in `serverUrl` parameter (+test).
- Unify URL regex in `checkServerUrl` function.
- Fixed the documentation:
- `http(s)://{username}.your.carto.instance` is the general pattern.
- `http(s)://your.carto.instance/user/{username}`  is only for On-Premises environments.
- Update Changelog

Fix server url parameter

---

package.json

While investigating an issue on Builder's shrinkwrap I encountered a problem with carto.js. By having browserify-shim as a dependency, if a project installs it, shrinkwrapping will fail unless you have browserify installed as well (it's a peer dependency of browserify-shim).
To verify this, create a new npm project (tested with npm 3), add carto.js as a dependency, and try having something like `update-internal-deps` in builder. Check it against this branch later and it should work fine.
I personally see no reason why browserify-shim is a dependency instead of a devDependency, it's only used when bundling with browserify which only affects running the specs right now, since the bundling was migrated to Webpack.
Pinging @rochoa because he moved it there explicitely [3 years …

Move browserify-shim to dependencies from devDependencies

---

docs/guides/01-overview.md
docs/guides/05-upgrade-considerations.md
docs/reference/01-introduction.md
docs/reference/02-authentication.md
docs/reference/04-loading-the-library.md
docs/support/02-faq.md
docs/support/05-release-announcement.md

Related to: https://github.com/CartoDB/carto.js/issues/2182
It includes fixes to two issues:
1. On the reference page. Since @Jesus89 already made a PR including the string replace task for the reference page, the `Loading the library` section would be as follows:
```
<script src="https://libs.cartocdn.com/carto.js/%CURRENT_VERSION%/carto.min.js"></script>
<script src="https://libs.cartocdn.com/carto.js/%VERSION%/carto.min.js"></script>
```
`%CURRENT_VERSION%` will be replaced by the newest tag (specified in https://github.com/CartoDB/developers/blob/master/_app/_data/technologies.yml#L153) 
`%VERSION%` will remain the same to show where the version should be specified to load a different one.
2. Replacing `4.0` with `v4` in guides
These changes will be live when a new tag is ready and …

Fix versioning and tags in guides

---

CHANGELOG.md
src/geo/geocoder/tomtom-geocoder.js
src/geo/ui/search/search.js
test/spec/geo/geocoder/tomtom-geocoder-response-0.json
test/spec/geo/geocoder/tomtom-geocoder.spec.js
test/spec/geo/ui/search.spec.js

Objectives:
This process is very similar to what we did in: https://github.com/CartoDB/carto.js/pull/2020

Add new tomtom geocoder

---

CHANGELOG.md
src/api/v4/filter/base-sql.js
test/spec/api/v4/filter/base-sql.spec.js

Fixes Support issue https://github.com/CartoDB/support/issues/1898
_(copied from the issue)_
The range filter can use dates as follows, using `lte` & `gte` filters:
```js
let mi = new Date("2014-01-01T00:00:00.00Z");
let ma = new Date("2014-12-31T23:59:59.00Z");
let filtreData = new Carto.filter.Range('dat_data', { lte: ma, gte: mi});
```
However, when it uses the `between` filter like the next block of code:
```js
let mi = new Date("2014-01-01T00:00:00.00Z");
let ma = new Date("2014-12-31T23:59:59.00Z");
let filtroData = new Carto.filter.Range('dat_data', {between:{max: ma, min: mi}});
```
It gets the next error message: `message: "syntax error at or near "Jan""`:
File:
[between_test.html.zip](https://github.com/CartoDB/support/files/2726507/between_test.html.zip)
1. Create a JS map …

Fix filter "between" using dates

---

NEWS.md
bower.json
package-lock.json
package.json
src/cartodb.js
src/geo/geocoders/mapbox_geocoder.js

This PR changes Mapbox Geocoder ephemeral URL to permanent URL in CARTO.js v3.
Related to https://github.com/CartoDB/carto.js/issues/2217

Change Mapbox geocoder URL to the permanent one in CARTO.js v3

---

CHANGELOG.md
package.json
src/geo/map.js
src/geo/ui/search/search.js

Fixes support issue: https://github.com/CartoDB/support/issues/1888
* Open Builder.
* Import [test map](https://github.com/CartoDB/support/files/2681758/Untitled.Map.1.on.2018-12-14.at.21.18.23.zip)
* Go to edit the map
* Click the magnifying glass icon.
* Enter Atlanta GA in the search field & hit Enter.
The map should be centered in Atlanta GA.

Avoid 'silent:true' when setting view after search

---

.gitmodules

This PR removes unused `.gitmodules` file containing `phantom-jasmine` submodule from repository.
Related to and fixes #2207

Remove unused .gitmodules from repository

---

src/api/create-vis.js
src/geo/ui/search/search.js
test/spec/geo/ui/search.spec.js

This PR allow us to select the geocoding provider for the search box overlay in Builder by injecting `geocodingConfiguration` variable containing the needed configuration into window scope.
Mirror PR from `cartodb`: https://github.com/CartoDB/cartodb/pull/14622
Related to #2223.

Enable search box geocoder provider selection

---

examples/internal/gmaps-geometry-editor.html
examples/public/filters/bounding-box-gmaps.html
examples/public/layers/change-feature-columns-gmaps.html
examples/public/layers/change-feature-columns-leaflet.html
examples/public/layers/change-order-gmaps.html
examples/public/layers/change-source-gmaps.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/feature-click-gmaps.html
examples/public/layers/feature-over-out-gmaps.html
examples/public/layers/layer-with-aggregation-gmaps.html
examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/multilayer-gmaps.html
examples/public/layers/single-layer-gmaps.html
examples/public/misc/boilerplate-gmaps.html
examples/public/misc/custom-search-dataset-gmaps.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/filter-data-map-gmaps.html
examples/public/misc/guide-gmaps.html
examples/public/misc/hexagon-aggregation-gmaps.html
examples/public/misc/legends-gmaps.html
examples/public/misc/populated-places-gmaps.html
examples/public/misc/popups-gmaps.html
examples/public/misc/popups-video-gmaps.html

We need to add the new API key for Google Maps examples. This is the first update to see if it works properly. If it works, I'm going to update the rest of the examples.

update api key

---

CHANGELOG.md
docs/guides/01-overview.md

Fixes #2230 
This adds a note in Overview guide regarding the name of the npm package.
It will be available when publishing the next CARTO.js version to dev-center

Add npm install note in Overview guide

---

CHANGELOG_INTERNAL.md
package.json
src/geo/ui/attribution/attribution-template.tpl
src/geo/ui/attribution/attribution-view.js
test/spec/geo/ui/attribution-view.spec.js
test/spec/vis/overlays-factory.spec.js
test/spec/vis/vis-view.spec.js

This PR is to change the attribution widget character because it can be confusing as suggested in 
https://github.com/CartoDB/cartodb/issues/14914.
We are also making the widget to appear condensed when the map width is small enough to prevent if from taking too much space, and appear expanded in bigger map sizes so the attributions appear clearly visible.

Change attribution character and toggle widget based on container

---

CHANGELOG_INTERNAL.md
src/geo/ui/attribution/attribution-view.js
test/spec/geo/ui/attribution-view.spec.js

This PR is related to https://github.com/CartoDB/carto.js/pull/2235. 
This PR only contains a fix for a mini bug that made the attributions button not work the first time it was pressed. This is because changes in the view should be done by changing the model so view and and model don't desynchronize.
Also, prevent autocollapsing the attributions widget when user clicks on the document.

Fix attribution widget

---

themes/scss/map/_overlays.scss

https://github.com/CartoDB/support/issues/1521
Using `flex` in `Legends` element to include margin in gradient legend.
(Margin was added to cover average text below the bar)

Fix scroll in gradient legends

---

src/cdb.config.js
test/spec/api/vizjson.spec.js
test/spec/cartodb.spec.js
test/spec/geo/map.spec.js
test/spec/vis/vis.spec.js

The new attributions page is https://carto.com/about-carto/

Replace reference to carto.com/attributions by carto.com/about-carto/

---

src/geo/ui/attribution/attribution-view.js

[Shortcut story](https://app.shortcut.com/cartoteam/story/178449/notify-about-the-limit-of-4096-named-maps-in-builder)
Datasets' attributions are not working fine when loading a map. Sometimes the attributions are duplicated, or an empty space is being shown.
I've checked that the attributions array doesn't contain duplicated elements. I've also checked with a regular expression that the string that is going to be rendered is clean.

Check attributions text before loading them

---

CHANGELOG_INTERNAL.md
package-lock.json
package.json

For #2261 to land Builder via internal-carto.js

Prepare 4.2.2-2 internal-carto.js version

---

package.json

Shortcut: https://app.shortcut.com/cartoteam/story/221282/carto2-deploys-are-broken-due-to-git-protocol-security-enforment
Github security notice: https://github.blog/2021-09-01-improving-git-protocol-security-github/
cartodb-platform: https://github.com/CartoDB/cartodb-platform/pull/7245/files
cartodb: https://github.com/CartoDB/cartodb/pull/16407
Deploy to staging cloud: http://deploy.int.cartodb.net/job/Carto_deploy_to_staging_(carto.com)_stag/3019/console
- Update github URLs from `git://github.com/CartoDB` to `git@github.com:CartoDB`
- Update `package.json` git URLs from `git://github.com/CartoDB` to `github:CartoDB || https://`

Updating v3 github URL to https
