CartoDB/carto.js

src/geo/leaflet/leaflet.js
test/spec/api/layers.spec.js

https://github.com/CartoDB/cartodb.js/issues/264

fix layers order

---

vendor/mod/torque.uncompressed.js

Ref https://github.com/CartoDB/torque/issues/89
@javisantana

Adds fixed torque

---

vendor/mod/torque.uncompressed.js

Coming from https://github.com/CartoDB/cartodb.js/pull/274
@javisantana

Replaces Torque.js to preload images properly

---

examples/bing.html
src/geo/ui/slides_controller.js
src/vis/overlays.js

fixes https://github.com/CartoDB/cartodb/issues/1879 cc @javierarce

1879 mouse slide

---

doc/API.md

Just linking in named maps a bit more

Added links to named maps, etc. in API.md doc

---

doc/vizjson_format.md

Fixed typo, added missing entries to named map portion

Added missing entries to vizjson spec

---

vendor/mod/torque.uncompressed.js

This updates cartodb.js with:
- Problem with the icon preloader's counter
- Smarter way of correcting out of bounds coordinates
cc @javisantana

Adds latest fixes from torque

---

src/geo/ui/mobile.js
src/vis/vis.js

Fixes the hiding of the loader in mobile

---

doc/API.md

@javisantana 
Takes care of #203

Fixed json format

---

src/api/layers.js
src/vis/vis.js

fixes createLayer with legends

---

vendor/mod/torque.uncompressed.js

Changes:
- Fixes non-filtered marker files by checking CORS.
- Clears cache on CSS change.

Adds new version of torque

---

Gruntfile.js

Checking if:
- version is empty
- version is not semver valid.
cc @fdansv

Grunt checks package version before running any task

---

src/vis/layers.js
test/spec/api/layers.spec.js

Ref. #254 
@javisantana 
@matallo

Fixes use of https parameter in torque layer

---

src/geo/ui/time_slider.js

Fixes https://github.com/CartoDB/torque/issues/103
@ohasselblad @javisantana

Makes play() and pause() interact with the timeslider button

---

src/geo/ui/time_slider.js

Ref #357 
@javisantana 
@iriberri

Allowing to show time in time slider when range is less than 72h

---

doc/API.md

@javisantana 
Adding layer source info as suggested in #279 
Not sure if this is a good place on the page to put the layer metadata. It's such a large amount of text I wonder if it should be in a separate section with a link under createLayer.

Added layer source info

---

README.md
doc/API.md

I was reading the docs to learn about cartodb.js...
I found a typo..
I cloned the repo to fix THE typo...
...I ended up fixing more typos and changing a bunch of things.
:expressionless:

Fixes some typos and introduces some changes to API.md

---

doc/API.md

@javisantana 
Updating the version numbers on the API doc to the current version

updated api version number

---

src/vis/image.js
test/spec/core/image.spec.js

This PR:
- Enables the CDN.
- Allows to use the `no_cdn` param (see specs)
- Updates specs.
- Adds a couple of new specs to test the `no_cdn` param.

Uses the CDN to retrieve the images

---

bower.json

Remove cdbui bower dependency

---

src/vis/image.js
test/spec/core/image.spec.js

- Updates specs.
- Replaces `_requestPOST`  with `getLayerToken`.

Uses the CDN from the layegroup

---

NEWS
themes/css/map/cartodb-map-light.css

fixes bootstrap compatibilites, closes #87, #107

---

src/core/template.js
vendor/mustache.js

@CartoDB/frontend., this PR bumps the version of mustache.js from v0.5.2 to v1.1.0.
We (@javisantana and I) discovered a bug in mustache.js when investigating cartodb/cartodb#2420 and this bump fixes it.
PTAL @javisantana, @xavijam

Upgraded mustache.js to v1.1.0

---

doc/API.md
src/vis/overlays.js
test/spec/vis/vis.spec.js

Fixes #405
This one is for you @xavijam.

Fixes typo in docs for vis.addOverlay and refactors it

---

src/vis/vis.js

Fix issue #415

---

test/spec/core/sanitize.spec.js
vendor/html-css-sanitizer-bundle.js

Change the policy to allow target attribute

Fix <a target="_blank" attribute

---

examples/tutorials/tutorial-google-driving-2.html
examples/tutorials/tutorial-google-driving.html

adding google driving directions tutorial example code

---

src/cartodb.js
src/geo/gmaps/torque.js
src/geo/leaflet/torque.js

cc @fdansv 
cc @alonsogarciapablo to see if you understand why is not needed

removed CDN_HOST since it's not needed anymore

---

vendor/wax.cartodb.js

This will allow us to reorder layers with infowindow in GFW

Reorder infowindow layers

---

doc/API.md
src/geo/ui/time_slider.js
test/spec/geo/ui/time_slider.spec.js

Ref. https://github.com/CartoDB/torque/issues/135
...instead of concrete dates:
@javisantana @ohasselblad

Shows date ranges on sliders with few steps

---

src/geo/ui/time_slider.js
test/spec/geo/ui/time_slider.spec.js

Only ranges dates if the total range is less than a year

---

src/geo/gmaps/torque.js

Ref #452 
Same fix as above, but for google maps.

Applies loop fix to google maps

---

src/vis/layers.js

Ref. #458 
Not sure if there is anything else you want to add.
@javisantana @zenitraM

Adds new basemap url scheme to https to http converter

---

src/geo/geocoder.js
test/spec/geo/geocoder.spec.js

See the related issue: https://github.com/CartoDB/cartodb.js/issues/390
I've also enabled the commented specs and added a new one.

Don't remove the spaces in the user-submitted addresses using the NOKIA geocoder

---

doc/API.md

Waiting to add an example of the `basemap` option, but rest is ready for review!
Ref: #371 
cc @javierarce @javisantana

adding static maps to cartodb.js docs

---

grunt/tasks/jasmine.js
test/SpecRunner.html

Use http version of google maps api in tests

---

doc/API.md
src/vis/layers.js
test/spec/vis/layers.spec.js

Forces https basemaps if https property has been explicitly defined

---

NEWS
README.md
RELEASING.md
doc/API.md
package.json
src/cartodb.js
src/geo/layer_definition.js
src/vis/image.js
test/SpecRunner.html
test/spec/api/layers.spec.js
test/spec/geo/layer_definition.spec.js

- Merged develop which contains the fix to use the right indexes when fetching grids and attributes.
- Moved some logic to MapProperties.
- Rewrote some of the tests.
- Renamed layerDefinition.getLayerToken -> layerDefinition.createMap

Updates sandwiches branch

---

src/api/layers.js

@javisantana @alonsogarciapablo 
Fixes #535

Removes check for http-beginng vizjson addresses

---

NEWS
doc/API.md
src/geo/sublayer.js
test/spec/geo/sublayer.spec.js

I hope everything is fine :smile:

fixes 538 adding the isVisible function

---

src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

Handle hidden layers properly when fetching attributes from tiler

---

src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

cdn_url from tiler has preference over cdn_url in the options

---

src/geo/sublayer.js
test/spec/geo/sublayer.spec.js

see https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.3.0.md

adds raster_band support for raster layers

---

README.md

One less command to copy and paste to build the project.

Combine global node deps in build instructions

---

src/vis/vis.js

nice and easy :) @javierarce how does it look?
Ref. #481

Updates version of infowindow template

---

src/api/sql.js

Adds nullchecking to date column analysis

---

src/api/sql.js

Only buckets if there are distinct values

---

src/api/cartocss.js
src/api/sql.js

Normalize category names to avoid problems with single and double quotes

---

src/api/cartocss.js
src/api/sql.js

@javierarce 
Closes https://github.com/CartoDB/cartodb.js/issues/568

Adds describeBoolean

---

grunt/tasks/jasmine.js
src/api/cartocss.js
test/spec/api/cartocss.spec.js

Closes #582, adds some cartocss tests.
@javierarce

Adds bubble maps to Pecan

---

examples/easy.html
src/geo/layer_definition.js
src/geo/map.js
src/vis/image.js
src/vis/vis.js
test/spec/core/image.spec.js
test/spec/geo/layer_definition.spec.js
test/spec/geo/map.spec.js

This PR contains all the necessary changes to support a tiled layer with labels on top of a map.

[WIP] Labels on top

---

src/api/cartocss.js

Improves behaviour of ramps

---

src/api/sql.js

Info: https://github.com/CartoDB/cartodb.js/issues/598

Adds try catch block

---

src/api/cartocss.js

@fdansv: can you review, please?
Original issue: https://github.com/CartoDB/cartodb/issues/4491

Updates boolean colors

---

test/spec/api/sql.spec.js

Closes #612 
@javierarce 
cc @javisantana

Adds spec tests for column description methods

---

src/core/util.js
src/geo/ui/infowindow.js
src/geo/ui/tiles_loader.js
src/vis/vis.js
test/SpecRunner.html
test/spec/core/util.spec.js

Removes occurrences of $.browser

---

vendor/wax.cartodb.js

Closes #636 
cc @xavijam / @javisantana

Updates wax to fix gmaps race condition

---

vendor/mod/torque.uncompressed.js

Fixes #631
cc @javierarce quick look plz?

Updates torque to 2.11.4

---

test/spec/geo/ui/time_slider.spec.js

@jesusvazquez these are not depending on timezones anymore, shouldn't give you any problems.

Timeslider tests fix

---

Gruntfile.js

Fixes #618.
@CartoDB/frontend what do you guys think? It seems to be working :+1:

Do not try to read secrets.json for every grunt task

---

grunt/tasks/jasmine.js
src/cartodb.js

The file was removed in #649 but these refs were missed

Remove refs to deleted file

---

src/geo/ui/search.js
test/spec/geo/ui/search.spec.js

Search pin enhancements

---

package.json

cc @CartoDB/frontend @azamorano

Updating imagemin package solving a problem under Oracle distros

---

examples/header_overlay.html

Adds example to create Header overlays with createLayer

---

examples/leaflet_hover_features.html

`getSQL` didn't exist when I tried this.

replace missing layer `getSQL` with `getQuery`

---

vendor/mwheelIntent.js

Not sure why this is happening, maybe I'm doing something wrong elsewhere, but this should fix it. See the original issue for details.

Fix #512, mousewheel error

---

doc/API.md

Small edits

---

grunt/tasks/replace.js

Replace the version of CartoDB.js in bower.json

---

src/core/util.js
test/spec/geo/layer_definition.spec.js

Fixing btoa method within cartodb.js utils

---

examples/easy.html
examples/index.html
grunt/tasks/jasmine.js
src/cartodb.js
src/core/datasource.js
src/geo/common.js
src/geo/layer_definition.js
src/geo/leaflet/leaflet.js
src/geo/leaflet/leaflet_cartodb_layergroup.js
src/vis/vis.js
src/windshaft/client.js
src/windshaft/private_map.js
src/windshaft/public_map.js
test/SpecRunner.html
test/spec/geo/layer_definition.spec.js
test/spec/windshaft/client.spec.js

@xavijam This integrates my WIP with your branch.

Widgets making a single request to the client

---

NEWS.md
src/geo/layer_definition.js
test/spec/geo/layer_definition.spec.js

Reverts CartoDB/cartodb.js#714

Revert "Fixing bug getting infowindow data from an incorrect data layer"

---

src/cartodb.js
src/geo/ui/widget.js
src/geo/ui/widgets/category/content_view.js
src/geo/ui/widgets/category/item_view.js
src/geo/ui/widgets/category/items_view.js
src/geo/ui/widgets/category/model.js
src/geo/ui/widgets/category/view.js
src/geo/ui/widgets/standard/widget_content_view.js
src/vis/vis.js
src/windshaft/client.js
src/windshaft/dashboard.js
src/windshaft/filters/base.js
src/windshaft/filters/category.js
src/windshaft/filters/collection.js

Widgets category filter

---

src/cartodb.js
src/geo/ui/widgets/widget_model.js
src/vis/vis.js
src/windshaft/dashboard.js
src/windshaft/dashboard_instance.js
src/windshaft/filters/bounding_box.js

It would be nice to be able to setup if a widget needs to be synced to the actual bounding box of the map. In this PR we're always sending the bbox filter when fetching the data for all widgets.
cc// @xavijam

Widgets using BBOX filter

---

src/geo/ui/infowindow.js

Reviewer @xavijam.
Close #737 and #739.
Solves bug that happens when zoom changes, showing popup really small making content never displayed.

Fixed empty popup

---

grunt/tasks/browserify.js
grunt/tasks/concat.js
grunt/tasks/jasmine.js
package.json
src-browserify/odyssey.js
test/spec/src-browserify/odyssey.spec.js

Part milestone for #699 
Just bundle since there were no specific tests for this one, added an integration test case to verify the load working as expected though.
@javierarce can your review? :pray: 
cc @matallo @alonsogarciapablo

Migrate cartodb.mod.odyssey to browserify

---

src/vis/vis.js
src/windshaft/client.js
src/windshaft/dashboard.js
src/windshaft/dashboard_instance.js
src/windshaft/filters/collection.js

Fixes #743.
@xavijam what you do you think?

Refresh layer widgets

---

doc/api_methods.md
doc/core_api.md
doc/events.md
doc/getting_started.md
doc/other_stuff.md
doc/sql.md
doc/static_maps.md
doc/ui_functions.md

formatting changes needed for the new docs
CR @csobier @rochoa

new docs formatting

---

doc/api_methods.md

Reviewer @xavijam 
Although possible there was no documentation about the use of `no_cdn` in the `createLayer` method.
Close #759

Added documentation about the no_cdn option used in the createLayer method

---

grunt/tasks/_browserify-bundles.js
grunt/tasks/browserify.js

Load jQuery dependency for Torque from cartodb.js bundle

---

package.json
src/geo/ui/widgets/category/content.tpl
src/geo/ui/widgets/category/content_view.js

Let’s :fire: those pesky string concats inside the views
@xavijam @alonsogarciapablo @javierarce

Add browserify transform for templates

---

doc/getting_started.md

In regards to [Docs issue#488](https://github.com/CartoDB/docs/issues/488)
@matallo , can this be merged please?

removed links to out-of-date The Hobbit

---

examples/index.html
src/geo/ui/widgets/widgets_view.js
src/vis/vis.js
themes/scss/map/canvas.scss
themes/scss/widgets/canvas.scss
themes/scss/widgets/default.scss

- Adding new element (only css) to the map stack, dashboard map, it will have the map (always) and widgets (when they are any). In the future we will add to this content the torque time series.
- Fixed responsive version, it was broken.
@alonsogarciapablo.

Adding Dashboard-canvas to the stack

---

src/geo/map/torque-layer.js
src/vis/overlays.js
src/vis/vis.js

this will allow non layer group layers to have a infowindow.

---

src/geo/ui/widgets/histogram/model.js

adds setBins to histogram

---

doc/getting_started.md
examples/map_dragging_disabled.html
src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map.js
src/vis/vis.js
test/spec/geo/gmaps/gmaps.spec.js
test/spec/geo/leaflet/leaflet.spec.js
test/spec/vis/vis.spec.js
themes/scss/map/cartodb-map-light.scss

This PR contains the fixes on `develop` branch (until today nov-16) into the `v4` branch which is the base for `widgets` branch.
reviewer @alonsogarciapablo cc @xavijam @viddo 
close #803

Merge fixes from develop into v4 branch

---

src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js

reviewer @viddo (related with #803 and comments on #806)
Removed useless comments con leaflet and gmaps views.

Removed useless comments

---

doc/getting_started.md
examples/map_dragging_disabled.html
src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map.js
src/vis/vis.js
test/spec/geo/gmaps/gmaps.spec.js
test/spec/geo/leaflet/leaflet.spec.js
test/spec/vis/vis.spec.js
themes/scss/map/cartodb-map-light.scss

reviewer @alonsogarciapablo 
close #803 
Ported changed from `v4` to `widgets`.

Merge `v4` changes into `widgets` branch

---

src/geo/ui/widgets/histogram/chart.js
themes/scss/widgets/chart.scss

Now the elements of the axis are linked to the vertical lines: 
Example with 4 divisions:
Example with 6 divisions:

Improves xAxis calculation

---

src/windshaft/client.js

Fixes #778.
@rochoa will this work? Thanks!

Encodes filters param when instantiating a dashboard

---

src/geo/ui/widgets/histogram/model.js
test/spec/geo/ui/widgets/histogram/model.spec.js

We've changed the backend to return only the bins that contains actual data. This PR updates the histogram model to generate the missing bins in the client.
/cc @viddo @rochoa

Adapts the histogram model to generate a full bucket list from the server data

---

themes/scss/infowindow/cartodb-infowindow-jspanel.scss

take a look @javisantana  @xavijam

remove styles

---

src/geo/ui/widgets/histogram/chart.js
src/geo/ui/widgets/histogram/content-view.js

This PR removes the previous dependency between the two histograms.

Removes dependency between chart and mini chart

---

doc/api_methods.md

[doc] Layer Source Object

---

src/core/config.js
src/geo/map.js
test/spec/core/config.spec.js
test/spec/geo/map.spec.js

reviewer @xavijam  cc @alonsogarciapablo @viddo @javisantana

Sanitized attribution to avoid XSS

---

src/cdb.config.js
src/geo/map.js
test/spec/cartodb.spec.js
test/spec/geo/map.spec.js

Attribution issue fixed

---

src/geo/ui/widgets/category/content_view.js
src/geo/ui/widgets/category/title/search_title_template.tpl
src/geo/ui/widgets/category/title/search_title_view.js
src/geo/ui/widgets/formula/content_view.js
src/geo/ui/widgets/formula/template.tpl
src/geo/ui/widgets/widget_content_model.js
test/spec/geo/ui/widgets/category/items_view.spec.js
test/spec/geo/ui/widgets/category/options_view.spec.js
test/spec/geo/ui/widgets/category/search_title_view.spec.js
test/spec/geo/ui/widgets/category/stats_view.spec.js
themes/scss/widgets/default.scss
themes/scss/widgets/shapes.scss

Collapse behaviour \o/

---

src/core/format.js
src/geo/ui/widgets/category/list/item/item_clickable_template.tpl
src/geo/ui/widgets/category/list/item/item_unclickable_template.tpl
src/geo/ui/widgets/category/list/item/item_view.js
src/geo/ui/widgets/category/list/item/search_item_view.js
src/geo/ui/widgets/histogram/chart.js
src/geo/ui/widgets/histogram/content-view.js
test/spec/core/format.js
test/spec/geo/ui/widgets/histogram/chart.spec.js

REVIEWER: @javierarce 
Closes https://github.com/CartoDB/cartodb.js/issues/867

Moving standard formatNumber to format helper class

---

src/geo/ui/widgets/category/model.js
src/geo/ui/widgets/category/models/category_model_range.js
src/geo/ui/widgets/category/models/search_model.js
src/geo/ui/widgets/category/stats/stats_template.tpl
src/geo/ui/widgets/category/stats/stats_view.js
test/spec/geo/ui/widgets/category/model.spec.js
test/spec/geo/ui/widgets/category/stats_view.spec.js

Added new category stats

---

src/geo/ui/dashboard-info-view.tpl
themes/scss/map/dashboard-info.scss

Fixes size of icons in the Blue Bar:tm:

---

src/geo/ui/widgets/histogram/chart.js
src/geo/ui/widgets/histogram/content-view.js
src/geo/ui/widgets/time-series/histogram-view.js
src/geo/ui/widgets/time-series/torque-histogram-view.js
test/spec/geo/ui/widgets/histogram/chart.spec.js
themes/scss/widgets/chart.scss

This PR add the shadow bars behind the data bars:

Adds shadow bars

---

src/geo/ui/widgets/animate_values.js

This PR adds a debounce to the counters animation in order to reduce the browser load.

Adds debounce to the counters animation

---

examples/time-series-widget.html
examples/torque-time-series-widget.html
src/geo/ui/widgets/histogram/model.js
src/geo/ui/widgets/time-series/torque-histogram-view.js
src/windshaft/dashboard-instance.js
src/windshaft/dashboard.js
src/windshaft/filters/range.js
test/spec/geo/ui/widgets/histogram/content_view.spec.js
test/spec/geo/ui/widgets/histogram/model.spec.js
test/spec/geo/ui/widgets/time-series/content-view.spec.js
test/spec/geo/ui/widgets/time-series/torque-content-view.spec.js
test/spec/geo/ui/widgets/time-series/torque-time-slider-view.spec.js

cc @javierarce @viddo as you were working on histogram and time-series

Widgets timeseries filtered from meta

---

NEWS.md
package.json
src/vis/vis.js
test/spec/vis/vis.spec.js

No matter if scrollwheel is enabled or if zoom overlay is added.
Fixes #902.
REVIEWER: @alonsogarciapablo

Don't disable drag/pan of the map if device is mobile

---

NEWS.md
package.json
src/vis/vis.js
test/spec/geo/ui/legend.spec.js
test/spec/vis/vis.spec.js

Applying drag-map bug-fixing

---

test/spec/core/sanitize.spec.js

Added more sanitize scenarios.
reviewer @xavijam

Added more sanitize cases

---

package.json

Fix phantomjs processes not dying after test run

---

src/geo/ui/tiles-loader.js
themes/scss/widgets/overlays.scss

change loader

---

src/geo/ui/tiles-loader.js
src/vis/overlays.js

Instead of using fadeIn fadeOut or fadeTo opacity thing, let's use 'is-visible' standard class for CDB-Loader.
REVIEWER: @javierarce 
cc @piensaenpixel

Loader review

---

.eslintignore
package.json
src/geo/ui/infowindow.js
test/spec/geo/ui/infowindow.spec.js
themes/scss/infowindow/cartodb-infowindow-default.scss
vendor/clip-path.js

Replaces clip path plugin with a cross-browser version

---

themes/scss/widgets/overlays.scss

fix transition

---

examples/openlayers3.html

reviewer @viddo 
This PR includes a new sample for OpenLayers3 derived from a question @oriolbx has received on support.

Added new sample for OpenLayers3

---

src/vis/vis.js

Turns out it’s not needed anymore, so remove the checks.
@alonsogarciapablo ping

Remove check for layergroup to setup WindshaftMap

---

src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js

This PR removes all the unnecessary stuf from `src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js` so that we can focus on the important things :)
cc: @fdansv PTAL (here's the [resulting file](https://github.com/CartoDB/cartodb.js/blob/f470a561be543cb3f96dd2d3925a8c4dc060bdf4/src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js)).

Vector layer cleanup

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

Including nulls and undefines. Fixes #1019.
RW: @viddo

Cast any category value to string

---

src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js

Only add boundingBox if set

---

Gemfile

Update compass gem version matching with Editor compass version

---

doc/getting_started.md

For [Docs issue#634](https://github.com/CartoDB/docs/issues/634)
@rochoa , we got a Support complaint that this info was hard to find. I've applied minor enhancements to the Getting Started section to add clarity and make it easier to locate.  Let me know if you approve?

enhanced other mapping libraries as part of Getting Started

---

doc/api_methods.md

For [Docs issue#596](https://github.com/CartoDB/docs/issues/596#issuecomment-178009348)
Thanks for clarifying @alonsogarciapablo !  Are you okay with these suggested changes?

moved createLayer up one level and provided link to layer source options

---

src/geo/leaflet/leaflet-torque-layer.js

fixed infinite loop with torque and update torque metadata

---

package.json
src/geo/ui/search/search_template.tpl
themes/scss/map/attributions.scss
themes/scss/map/overlays.scss

- Fixed magnify icon.
- CartoAssets pointing to master branch.
cc @piensaenpixel

Search icon fix

---

.travis.yml
src/dataviews/category-dataview-model.js
src/dataviews/dataview-model-base.js
src/dataviews/formula-dataview-model.js
src/dataviews/histogram-dataview-model.js
src/dataviews/list-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/formula-dataview-model.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/dataviews/list-dataview-model.spec.js

Fixes #1040 
Basically, renamed `_onFilterChanged ` to `_reloadMap` (since that's what it does), and use that as the side-effect on attrs changes.
@alonsogarciapablo review, please 
cc @javisantana

1040 make dataviews reactive

---

src/dataviews/formula-dataview-model.js
test/spec/dataviews/formula-dataview-model.spec.js

@alonsogarciapablo missed some attrs in #1048  :disappointed:

Reload map on prefix+suffix change on a formula dataview

---

Gruntfile.js
src/dataviews/category-dataview-model.js
src/dataviews/dataviews-collection.js
src/dataviews/histogram-dataview-model.js
src/dataviews/list-dataview-model.js
src/geo/leaflet/leaflet-torque-layer.js
src/windshaft/filters/range.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/formula-dataview-model.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/dataviews/list-dataview-model.spec.js

Fixes #1051 
To follow conventions on how data attrs should be named
Also removed `columns_title` on list dataview since not actually used/needed here
@alonsogarciapablo ping

1051 camelcase to snake case

---

doc/api_methods.md

Being proactive until issue #1035 is addressed. 
@rochoa , ok to merge? 
(Also need approval to merge [PR#369](https://github.com/CartoDB/Windshaft-cartodb/pull/368), Named Map doc, for consistency)

added note to setParam regarding Torque

---

doc/layer_source_object.md

For [Docs issue#593](https://github.com/CartoDB/docs/issues/593).
@rochoa , I took my best guess. Please review and advise of any corrections needed?

Docs 593 layer source arguments

---

doc/ui_functions.md

(just got hooked up with Jenkins and VPN access, testing live docs deploy with this hyperlink fix)

fixed hyperlink, testing deploy of docs

---

doc/ui_functions.md

Thanks for explaining your thoughts @ernesmb . Give me a thumbs up to remove this note, and I'll merge :-)

removed confusing note from infowindow section

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

Fixes #1063.
I think the problem was that the following line was not doing anything:
`this.set.bind(this, 'submitBBox', true))`
@javierarce since I think you wrote the original code... makes sense? Thanks!

Ensure `submitBBox` is set to true after the first fetch in the histogram dataview

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Fixes #1070, by reverting this commit.
@viddo PTAL! Thanks!
NOTE to @viddo : this might have some effects on the deep-insights.js test suite since I remember you mentioning something related (there's some history about it on slack)

Fixes bounding box issue

---

package.json
src/geo/gmaps/gmaps-torque-layer-view.js
src/geo/leaflet/leaflet-torque-layer.js
src/geo/map/torque-layer.js

this is needed for a DI.js fix I'll push
cc @viddo

fixes and adds a method to torque layer

---

src/geo/data-providers/geojson/geojson-data-provider.js

Fixes #1087  
@alonsogarciapablo

[dnm] Adds sum, min and max for formula generator function

---

src/vis/vis.js

Code-review proposal for #1104 
Make the public method to not require any argument, and explain what it’s intended for.
@xavijam I figured doing a PR was easiest way to showcase this, instead of a comment. :)

Improve map instantiation mechanism

---

src/dataviews/category-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js

Fixes #1085 and #1086 (two for the price of one):
@xavijam can you PTAL! Thanks!

Fixes category search functionality for vector layers

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

CR @javisantana 
workaround for #926 
close https://github.com/CartoDB/deep-insights.js/issues/165
This is a workaround to fix a problem with last bucket selection.

Rounded end for last bin

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

CR @xavijam 
Fix issue when buckets has no data.

Ensure bucket has values

---

src/vis/vis.js
test/spec/vis/vis.spec.js

Added done trigger after map instantiation

---

examples/createLayer_custom_tooltip.html
examples/createLayer_noLegend.html
examples/createLayer_refresh_time.html

add some examples

---

doc/core_api.md
src/core/decorator.js
test/spec/geo/gmaps_cartodb_layer/hide.js
test/spec/geo/gmaps_cartodb_layer/interaction.js
test/spec/geo/gmaps_cartodb_layer/show.js

Fix spelling of 'functionality'

---

src/geo/map.js
test/spec/geo/map.spec.js

Fixes #1096.
@javisantana what do you think?

Debounce map instantiation through map.reload

---

src/vis/vis.js

allow viz.json to be loaded from an url

---

src/geo/data-providers/geojson/category-geojson-data-provider.js

This will fix https://github.com/CartoDB/cartodb.js/issues/1151
@alonsogarciapablo

[vector] Handling no features on category generator

---

src/geo/data-providers/geojson/category-geojson-data-provider.js
src/geo/data-providers/geojson/formula-geojson-data-provider.js
src/geo/data-providers/geojson/geojson-data-provider-base.js
src/geo/data-providers/geojson/histogram-geojson-data-provider.js

Reduces usage of getValues

---

src/dataviews/dataviews-factory.js

Removes _indexOf

---

src/dataviews/category-dataview-model.js
src/dataviews/category-dataview/search-model.js
src/dataviews/dataview-model-base.js
src/dataviews/histogram-dataview-model.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js

Partially fixes #1158. The bounding box that widgets were using to get information from Windshaft was not right.
@xavijam please review. Thanks!
cc: @fdansv

Dataviews get bounding box from map object

---

package.json

Bumped d3.cartodb

---

doc/api_methods.md
doc/core_api.md
doc/getting_started.md
doc/sql.md
src/geo/gmaps/gmaps.js
src/geo/leaflet/leaflet.js
src/geo/leaflet/leaflet_cartodb_layergroup.js

cc @javisantana @alonsogarciapablo

Checking attributions

---

src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js
src/windshaft/windshaft-map.js
test/spec/geo/leaflet/leaflet-cartodb-vector-layer-group-view.spec.js

Fixes #1176 
Needs merge of https://github.com/CartoDB/Windshaft/pull/457 for it to work. Merging won't break non-named maps though.

[vector] Gets style from meta when map is named

---

src/windshaft/windshaft-map.js
test/spec/windshaft/windshaft-map.spec.js

@fdansv please take a look. Thanks!

Fixes wrong Windshaft layer type

---

src/ui/common/fullscreen/fullscreen-template.tpl
themes/scss/map/overlays.scss

fixes #1047
@xavijam could you take a look?

add changes

---

src/geo/leaflet/leaflet_tiledlayer.js
src/geo/leaflet/leaflet_wmslayer.js

As discussed with Santana, adding support for tileSize 512 and zoomOffset.

Adding support for tileSize 512 and zoomOffset.

---

src/geo/map.js
test/spec/geo/map.spec.js

Add method to get layer by id

---

src/geo/map.js
test/spec/geo/map.spec.js

Fixes #1202.
@viddo how do you like it now? :smile:

Removes map.createBackgroundLayer in favor of map.createPlainLayer + image attribute

---

src/geo/cartodb-layer-common.js
src/geo/cartodb-layer-group-anonymous-map.js
src/geo/cartodb-layer-group-base.js
src/geo/cartodb-layer-group-named-map.js
src/windshaft/windshaft-map.js
test/spec/geo/cartodb-layer-group-anonymous-map.spec.js
test/spec/geo/cartodb-layer-group-base.spec.js
test/spec/geo/cartodb-layer-group-named-map.spec.js
test/spec/windshaft/windshaft-map.spec.js

I spent some time to (hopefully) clarify the code a bit and added some more tests to (hopefully) avoid more issues with indexes & infowindows :)
@xavijam can you please CR? Thanks!

Fixes bug with indexes when generating the TileJSON for Named Maps.

---

.eslintignore
src/api/create-vis.js
src/vis/vis.js
test/spec/api/create-vis.spec.js
test/spec/api/fake-vizjson.js
test/spec/vis/vis.spec.js

This PR completes the second task of #804.
The create-vis function now fetches the viz.json file from a URL when given one.
@viddo could you please CR? Thanks!

Extract vizjson loading to create-vis function

---

src/vis/vis.js
test/spec/vis/vis.spec.js

Closes #1197.
@xavijam can you please take a look? Thanks!

Generate graph of analyses from analyses present in the viz.json

---

src/vis/overlays.js
src/vis/vis.js
test/spec/vis/vis.spec.js

Change visualization public API to be used from DI.js

[WIP] changed public api

---

src/analysis/analysis-model.js
src/geo/cartodb-layer-group-base.js
test/spec/analysis/analysis-model.spec.js
test/spec/api/create-vis.spec.js

Reload map when type of analyses change

---

src/analysis/analysis-model.js
src/dataviews/dataview-model-base.js
src/vis/model-updater.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/vis/model-updater.spec.js

Closes #1212.
@javierarce can you please take a look? Thanks!

Dataviews can be associated to an analysis via the sourceId attribute

---

src/windshaft/map-base.js
test/spec/windshaft/map-base.spec.js

Try to get dataview's metadata from the 'widgets' dictionary inside the metadata of layers

---

src/windshaft/map-base.js
test/spec/windshaft/map-base.spec.js

Fixes https://github.com/CartoDB/d3.cartodb/issues/177 and a couple more.
cc @rochoa ok?

Discards plain layers as basemaps

---

package.json
test/spec/analysis/camshaft-reference.spec.js

I feel it is better to set the proper version of the reference instead of ^0.X.0, what do you think @alonsogarciapablo?

Updated camshaft

---

package.json

Use latest browserify versions to rely on factor-bundle plugin

---

doc/api_methods.md
doc/getting_started.md

For [Docs issue#816](https://github.com/CartoDB/docs/issues/816)
@michellechandra , simple edit applied. Can you sanity check for me and approve?

added layer.setsql and layer.setcartocss

---

.eslintignore
src/api/sql.js
test/spec/api/sql.spec.js

CR: @viddo 
cc @alonsogarciapablo 
Check [this commit](https://github.com/CartoDB/cartodb.js/commit/ec7e4ae01a311192fab52347a5e9ec709cd7da63) in order to see only that change.

Changed SQL for describing dataset geometry

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

Following the same logic we used in Pecan: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_DistType.sql cc @ohasselblad 
@javisantana @alonsogarciapablo mind having a look? :)

Adds method to histogram dataview model to obtain its shape

---

src/geo/map/cartodb-layer.js
src/windshaft/anonymous-map.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/windshaft/anonymous-map.spec.js

Closes #1258.
cc: @javisantana @rochoa

Map config includes layer's sql_wrap option if present

---

src/geo/geocoder.js
src/geo/ui/search.js
test/spec/geo/geocoder.spec.js
test/spec/geo/ui/search.spec.js

It solves #1194 .
@alonsogarciapablo  I'm waiting for the mapzen correct api key. The api key used inside geocoder.js is not the final one.

1194 mapzen geocoder in search

---

src/windshaft/anonymous-map.js
test/spec/windshaft/anonymous-map.spec.js

Do not try to include 'interactivity' and 'attributes' options in the map config for layers that don't have infowindow

---

examples/tutorials/named-maps-example.html
examples/tutorials/named-maps-template.html

currently failing: http://docs.cartodb.com/tutorials/named_maps/
cc @matallo

updating to https to avoid cross domain on docs

---

package.json
src/geo/gmaps/gmaps-torque-layer-view.js
src/geo/leaflet/leaflet-torque-layer.js
src/geo/map/torque-layer.js
test/spec/geo/map/shared-for-interactive-layers.js
test/spec/geo/map/torque-layer.spec.js
test/spec/geo/shared-tests-for-torque-layer.js

(Hopefully) closes #1266.
@javisantana: yay or nay?

Torque layer reloading

---

src/geo/map/infowindow-template.js
src/geo/ui/default-infowindow-template.tpl
src/geo/ui/infowindow-model.js
src/geo/ui/infowindow-view.js
test/spec/geo/ui/infowindow-model.spec.js
test/spec/geo/ui/infowindow.spec.js
test/spec/vis/infowindow-manager-spec.js

Fixes CartoDB/cartodb#7421.
@xavijam 👍  or 👎 ?

Add default infowindow template instead of trying to load "infowindow_light"

---

examples/tutorials/tutorial-1.html
examples/tutorials/tutorial-2.html
examples/tutorials/tutorial-google-driving-2.html
examples/tutorials/tutorial-query_by_distance.html
examples/tutorials/tutorial-toggle_map_view.html

Updated examples/tutorials files from http to https to work with docs output. Testing output with this PR...

update http to https for documentation tutorial images

---

src/windshaft/named-map.js
test/spec/windshaft/named-map.spec.js

Fixes CartoDB/cartodb#7422.
@fdansv can you please review this? Thanks!
cc: @javitonino

Make sure indexes are correct in the styles key

---

src/analysis/analysis-model.js
src/geo/map.js
src/windshaft/map-base.js
test/spec/analysis/analysis-model.spec.js
test/spec/windshaft/map-base.spec.js

Mark analysis node that changed as "failed" if request to Maps API fails

---

src/geo/ui/infowindow-model.js
src/geo/ui/infowindow-view.js
test/spec/geo/map-view.spec.js
test/spec/geo/ui/infowindow-model.spec.js
test/spec/geo/ui/infowindow.spec.js

It was also possible to set a template by it's name.

InfowindowView only supports model's "template" attribute

---

src/vis/infowindow-manager.js
test/spec/vis/infowindow-manager-spec.js

@matallo please take a look! Thanks!

Always fetch attributes when clicking on a feature (fields might have changed)

---

src/geo/geocoder/mapzen-geocoder.js
src/geo/ui/search/search.js
test/spec/geo/geocoder/mapzen-geocoder.spec.js
test/spec/geo/ui/search.spec.js

It solves #1194 for v4.
@alonsogarciapablo

add mapzen geocoder

---

src/geo/map-view.js
test/spec/geo/map-view.spec.js

fixes layergroup view not being cleared

---

src/dataviews/category-dataview-model.js
src/dataviews/dataviews-factory.js
src/dataviews/histogram-dataview-model.js

Makes dataviews consider temporary states

---

themes/scss/infowindow/themes/dark.scss

@alonsogarciapablo is a minor fix, could you take a look pablito?

fix color text

---

styleguide/infowindows.html
themes/scss/infowindow/cartodb-infowindow-default.scss

fix break word

---

package.json

Same motivation as for #1199
A `npm update camshaft-reference` would be needed to update locally
cc @rochoa @alonsogarciapablo ok?

Relax camshaft-reference version used

---

src/windshaft/client.js
test/spec/windshaft/client.spec.js

@javisantana Didn't think too much about this, but this could be a start... what do you think? Am I missing something (apart from some tests 😄)? Thanks!

Abort previous requests to the Maps API before sending a new one

---

src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
test/spec/geo/gmaps/gmaps-map-view.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js

Title says it all :)
@xavijam this is what we need in https://github.com/CartoDB/cartodb/pull/8182 😄

vis.map triggers `dragend` event

---

src/geo/ui/infowindow-model.js
src/vis/tooltip-manager.js

- Fixing problem rendering false values like 0, false, ...
Fixes https://github.com/CartoDB/cartodb/issues/8251
also, map reloads after change fields in the tooltip

Tooltip issue

---

src/windshaft/client.js
test/spec/windshaft/client.spec.js

Fixes: https://github.com/CartoDB/cartodb.js/issues/1327

"Ignore" error callback when ajax request is aborted

---

src/vis/vis-view.js

This PR allows the view to show/hide overlays when builder says so.
cc @alonsogarciapablo @xavijam

Bind overlays collection to make the view responsive to changes.

---

src/api/create-vis.js
src/geo/ui/logo-view.js
src/vis/overlays.js
src/vis/vis-view.js
themes/scss/map/overlays.scss

Fixes https://github.com/CartoDB/cartodb/issues/8473.
cc @saleiva @urbanphes @piensaenpixel

Hello logo

---

src/api/create-vis.js
src/api/vizjson.js
src/vis/vis-view.js

Logo placeholder

---

doc/API.md
doc/api_methods.md
doc/core_api.md
doc/events.md
doc/getting_started.md
doc/layer_source_object.md
doc/sql.md
doc/static_maps.md
doc/ui_functions.md
doc/versions.md
doc/vizjson_format.md

rebranding

---

src/windshaft/error.js
test/spec/vis/model-updater.spec.js

Closes https://github.com/CartoDB/cartodb.js/issues/1349.
@dgaubert could you please take a look? Thx!

Set error on the right analysis node

---

.eslintignore
src/geo/map.js
src/geo/map/cartodb-layer.js
src/geo/map/gmaps-base-layer.js
src/geo/map/layer-model-base.js
src/geo/map/layers.js
src/geo/map/plain-layer.js
src/geo/map/tile-layer.js
src/geo/map/wms-layer.js
src/vis/vis/layers.js
test/spec/geo/map.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1346 and fixes https://github.com/CartoDB/cartodb.js/issues/1297.
cc: @AbelVM

Couple of API fixes

---

package.json
src/analysis/analysis-factory.js
src/analysis/analysis-model.js
src/dataviews/dataview-model-base.js
src/dataviews/dataviews-factory.js
src/vis/vis.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/windshaft/anonymous-map.spec.js
test/spec/windshaft/map-base.spec.js
test/unit/dataviews/dataviews-collection.spec.js
test/unit/dataviews/dataviews-factory.spec.js
test/unit/dataviews/formula-dataview-model.spec.js
test/unit/dataviews/list-dataview-model.spec.js

1357 fix dataviews analysis states

---

src/core/config.js
test/spec/core/config.spec.js
test/spec/geo/leaflet/leaflet.spec.js
test/spec/geo/map.spec.js
test/spec/geo/ui/mobile.spec.js

Same change we did in https://github.com/CartoDB/cartodb.js/pull/1362.
cc: @xavijam

Changed default attribution

---

src/geo/map.js
test/spec/geo/map.spec.js

Wait until map has been instantiated explicitly before binding events

---

src/vis/model-updater.js
src/windshaft/error.js
src/windshaft/map-base.js
test/spec/windshaft/map-base.spec.js

Better error handling when trying to instantiate the map

---

.eslintignore
src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map-view.js
src/vis/vis-view.js
test/spec/geo/map-view.spec.js

Hopefully fixes https://github.com/CartoDB/cartodb/issues/9064.
We're trying to listen to `newLayerView` event, after the events had been triggered, and that was preventing the Blue Bar from being displayed while tiles were being loaded... 
@nobuti could you please take a look? thx!

Add layers to the map when .render is called to allow listening to 'newLayerView' event

---

doc/api_methods.md
doc/ui_functions.md

URL fixes in regards to [Docs issue#959](https://github.com/CartoDB/docs/issues/959)...
Will merge as soon as this PR passes test.

fixed broken links related to Docs domain change

---

src/geo/torque-layer-view-base.js
src/vis/vis.js
test/spec/vis/vis.spec.js

Closes https://github.com/CartoDB/cartodb.js/issues/1382 and closes https://github.com/CartoDB/cartodb/issues/9295.
@xavijam since you're already in the loop... mind taking a look?

Initialise torque layer models using datasource attributes

---

examples/tutorials/named-maps-example.html

fixing the cross domain issues here: https://carto.com/docs/tutorials/named_maps/

adding https flag to avoid cross domain issues

---

src/analysis/analysis-model.js
src/api/create-vis.js
src/dataviews/category-dataview-model.js
src/dataviews/category-dataview/category-model-range.js
src/dataviews/category-dataview/search-model.js
src/dataviews/dataview-model-base.js
src/dataviews/histogram-dataview-model.js
src/dataviews/histogram-dataview/histogram-data-model.js
src/windshaft/client.js
src/windshaft/map-base.js
test/spec/api/create-vis.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1381.
cc: @javitonino... do you think we should leave the actual code (i.e: getting auth tokens from viz.json) as a fallback?

[WIP] createVis supports authToken option

---

examples/add_custom_searchbox.html

Add example requested in https://github.com/CartoDB/cartodb.js/pull/1378
@alonsogarciapablo @csobier

add custom searchbox example

---

src/geo/cartodb-layer-group-view-base.js
src/geo/cartodb-layer-group.js
src/geo/leaflet/leaflet-cartodb-vector-layer-group-view.js
test/spec/geo/leaflet/leaflet-cartodb-vector-layer-group-view.spec.js

Fixes vector layer rendering

---

package.json

Using same d3 version than torque.js

---

.eslintignore
src/geo/leaflet/leaflet-layer-view.js
src/geo/leaflet/leaflet-tiled-layer-view.js
test/spec/geo/leaflet/leaflet-layer-view.spec.js
test/spec/geo/leaflet/leaflet-tiled-layer-view.spec.js

Related with https://github.com/CartoDB/cartodb/issues/9398.
Pair programmed with @matallo.

Update TMS property when basemap model has changed

---

src/geo/ui/legends/base/legend-title.tpl
themes/scss/map/overlays.scss

@alonsogarciapablo could you take a look?

fix legends ui

---

src/windshaft-integration/legends/rule-to-bubble-legend-adapter.js
src/windshaft-integration/legends/rule-to-category-legend-adapter.js
src/windshaft-integration/legends/rule-to-choropleth-legend-adapter.js
src/windshaft-integration/legends/rule.js
test/unit/windshaft-integration/legends/rule-to-bubble-legend-adapter.spec.js
test/unit/windshaft-integration/legends/rule-to-category-legend-adapter.spec.js
test/unit/windshaft-integration/legends/rule-to-choropleth-legend-adapter.spec.js
test/unit/windshaft-integration/model-updater.spec.js

Adapt to new format of carto_css meta coming from Maps API

---

themes/scss/map/overlays.scss

until we have a solution for mobile view, it's better hide them in mobile view.
could you take a look @nobuti ?
cc/ @xavijam

hide legends in mobile view

---

src/windshaft-integration/legends/rule-to-bubble-legend-adapter.js
test/unit/windshaft-integration/legends/rule-to-bubble-legend-adapter.spec.js

Fixes https://github.com/CartoDB/cartodb/issues/10135

Bubble for lines.

---

src/geo/ui/legends/choropleth/legend-view.js
src/windshaft-integration/legends/rule-to-choropleth-legend-adapter.js
test/unit/windshaft-integration/legends/rule-to-choropleth-legend-adapter.spec.js

This PR fixes https://github.com/CartoDB/cartodb/issues/10182

Fix avg percentage calculation.

---

src/util/formatter.js
test/unit/util/formatter.spec.js

Set 2 as max digits after .

---

doc/api_methods.md
doc/getting_started.md
doc/static_maps.md

@alonsogarciapablo , no content changes here.  Just catching up on fixing some broken urls. Can I merge?

fixed broken links from rebranding baseurl changes

---

src/geo/map/legends/custom-choropleth-legend-model.js
src/geo/map/legends/legends.js
src/geo/ui/legends/custom-choropleth/legend-template.tpl
src/geo/ui/legends/custom-choropleth/legend-view.js
src/geo/ui/legends/layer-legends-view.js
src/geo/ui/legends/legend-view-factory.js
test/spec/geo/ui/legends/layer-legends-view.spec.js

This PR fixes https://github.com/CartoDB/cartodb/issues/10224 from cartodb.js side.

Custom choropleth for pixel aggregation.

---

themes/scss/map/overlays.scss

@xavijam ready. Also I consolidate mediaquery :)

could you take a lofix 1458

---

src/api/sql.js
test/spec/api/sql.spec.js

Just avoiding `null` and `undefined` values.
_Not a big deal_

Include extra param in the sql request when it is false or 0

---

src/geo/ui/legends/base/legend-title.tpl
themes/scss/map/overlays.scss

@nobuti this is a fix for some, margins and paddings.. could you take a look?

fix spaces

---

themes/scss/map/overlays.scss

Add more space for bubble legend. @nobuti could you take a look?

add padding

---

src/geo/map-view.js
themes/scss/map/overlays.scss

@xavijam take a look
Fix https://github.com/CartoDB/cartodb.js/issues/1468

Fix z-index

---

themes/scss/map/overlays.scss

fix custom legend

---

themes/scss/infowindow/cartodb-infowindow-default.scss

@xavijam could you take a look?
cc/ @javisantana

fix custom infowindows

---

src/geo/ui/legends/bubble/legend-template.tpl

This PR fixes https://github.com/CartoDB/cartodb/issues/10449

Fix html rendering.

---

src/geo/ui/legends/base/legend-title.tpl
src/geo/ui/legends/bubble/legend-view.js
src/geo/ui/legends/choropleth/legend-template.tpl
themes/scss/map/overlays.scss

@alonsogarciapablo could you take a look?
cc/ @saleiva

remove hover

---

themes/scss/tooltip/cartodb-tooltip-default.scss

@nobuti could you take a look?
Fix - https://github.com/CartoDB/cartodb/issues/10441
cc @juanignaciosl

@nobutFix tooltips

---

themes/scss/map/overlays.scss

@nobuti could you take a look?
Related - https://github.com/CartoDB/cartodb/pull/10492

hide zoomInfo in publicView

---

src/geo/ui/infowindow-view.js

This PR fixes https://github.com/CartoDB/cartodb/issues/10669
cc @juanignaciosl @xavijam 

Adding .cartodb-popup-close-button.close as close popup trigger.

---

themes/scss/infowindow/cartodb-infowindow-default.scss

@nobuti  could you take a look?

fix infowindow

---

src/geo/ui/legends/bubble/legend-template.tpl
src/geo/ui/legends/categories/legend-template.tpl
src/geo/ui/legends/choropleth/legend-template.tpl
src/geo/ui/legends/custom-choropleth/legend-template.tpl
src/geo/ui/legends/custom/legend-template.tpl
src/geo/ui/legends/html/legend-view.js
test/spec/api/create-vis.spec.js
themes/scss/map/overlays.scss

This PR fixes https://github.com/CartoDB/cartodb/issues/10596. 
Yes, it doesn't make sense but apparently it does legends to work 😢 🔫 
CR @piensaenpixel 
@alonsogarciapablo please take a look to the tests fixes. I remove the defer method to use the `load` event. I think it makes more sense.

IE11 legends

---

src/geo/map/legends/choropleth-legend-model.js
src/geo/map/legends/custom-choropleth-legend-model.js
src/geo/map/legends/legends.js
src/geo/ui/legends/bubble/legend-template.tpl
src/geo/ui/legends/bubble/legend-view.js
src/geo/ui/legends/choropleth/legend-template.tpl
src/geo/ui/legends/choropleth/legend-view.js
test/spec/geo/ui/legends/bubble/legend-view-spec.js
test/spec/geo/ui/legends/choropleth/legend-view-spec.js
themes/scss/map/overlays.scss

This PR fixes https://github.com/CartoDB/cartodb/issues/10687 at cartodb.js's side.

Custom labels for legends

---

themes/scss/map/attributions.scss

CR @piensaenpixel 
easy one, needed for the feature overlay button

attribution: disabled button

---

src/geo/map.js

Fix map bounds so it takes considers the biggest dimension

---

src/vis/overlays-factory.js

Fixes https://github.com/CartoDB/cartodb/issues/10882.
@xavijam 👍  ?

log.error -> log.log

---

src/geo/ui/legends/custom-choropleth/legend-template.tpl
src/geo/ui/legends/custom-choropleth/legend-view.js
test/spec/geo/ui/legends/choropleth/custom-legend-view.spec.js

Adds labels for the custom choropleth legend

---

src/vis/vis.js
test/spec/vis/vis.spec.js

Part of https://github.com/CartoDB/cartodb.js/issues/1542.

Only reload vis when CartoDB or torque layers are added/removed

---

grunt/tasks/scss.js
package.json

This PR updates the perfect scrollbar library to fix https://github.com/CartoDB/cartodb/issues/11190. You can read more about what it's included in the update here: https://github.com/nobuti/perfect-scrollbar/pull/1

[DON'T MERGE YET] Update perfect scrollbar dependency.

---

themes/scss/infowindow/cartodb-infowindow-default.scss
themes/scss/map/overlays.scss

Fix scroll legend and align issue in infowindow

---

test/spec/geo/gmaps/gmaps-cartodb-layer-group.spec.js
vendor/wax.cartodb.js

[Here is the explanation](https://github.com/CartoDB/wax/pull/11)

Fix #1540 wax upper limit

---

themes/scss/map/attributions.scss

This PR fix [#1529](https://github.com/CartoDB/cartodb.js/issues/1529)

Fix #1529, first point

---

src/geo/map/cartodb-layer.js
src/vis/infowindow-manager.js
src/vis/tooltip-manager.js
src/vis/vis.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/vis/infowindow-manager-spec.js
test/spec/vis/tooltip-manager-spec.js
test/spec/vis/vis.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1586, https://github.com/CartoDB/cartodb.js/issues/1585, and https://github.com/CartoDB/cartodb.js/issues/1582.
@xavijam 🙏

Fixed several bugs related to infowindows and tooltips

---

src/geo/cartodb-layer-group.js
src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js
test/spec/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.spec.js

This PR fixes https://github.com/CartoDB/tangram-carto/issues/28
It allows tangram to get protected MVT.

Get tile url by type (png or mvt)

---

src/vis/vis.js
src/windshaft/error.js
src/windshaft/map-base.js
test/spec/vis/vis.spec.js
test/spec/windshaft/map-base.spec.js

Related to https://github.com/CartoDB/deep-insights.js/pull/526.

Propagate Maps API errors properly

---

src/vis/vis.js
src/windshaft/error.js
src/windshaft/map-base.js
test/spec/vis/vis.spec.js
test/spec/windshaft/map-base.spec.js

Reverts CartoDB/cartodb.js#1590

Revert "Propagate Maps API errors properly"

---

src/geo/cartodb-layer-group.js
src/windshaft-integration/model-updater.js
test/spec/geo/cartodb-layer-group.spec.js
test/spec/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.spec.js
test/unit/windshaft-integration/model-updater.spec.js

Little refactoring plus some new tests for the generation of .mvt tiles.
@donflopez what do you think? Thanks!

Simplifies (hopefully!) generation of url templates for .mvt tiles

---

vendor/wax.cartodb.js

Leaflet 1.0.3 last minute migration fixes

---

src/geo/cartodb-layer-group.js
src/windshaft-integration/model-updater.js
src/windshaft/map-base.js
test/spec/geo/cartodb-layer-group.spec.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1606
@donflopez can you please take a look? Thanks!

Handle subdomains properly in URLs for static images

---

src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/map-view.js
src/geo/map.js
test/spec/geo/gmaps/gmaps-map-view.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js

This PR exposes some internal through map model in order to avoid consuming them globally. Related to https://github.com/CartoDB/cartodb/issues/11846
cc @xavijam @alonsogarciapablo

Exposed some method and info through map model.

---

src/geo/leaflet/leaflet-map-view.js

Use flyto instead of setview to have animation also in vector

---

src/geo/cartodb-layer-group.js
src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js
test/spec/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.spec.js

It depends on #1624 and fix https://github.com/CartoDB/tangram.cartodb/issues/8

Vector tooltips infowindow

---

src/core/profiler.js
src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js

To have metrics about how many time takes a tangram to render in vector we have to send them to a backend.

Send stats

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/dataview-model-base.spec.js

Required for https://github.com/CartoDB/cartodb/issues/11783.
Hopefully fixes https://github.com/CartoDB/cartodb.js/issues/1610.
@xavijam mind taking a look at this 🙏 ? 💋 
cc: @donflopez

Do not fetch dataviews until view bounds are available if sync_on_bbox_change is true

---

src/core/util.js

Improve isWebGLSupported to detect disabled hardware acceleration

---

src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js
src/geo/leaflet/leaflet-layer-view-factory.js

This PR needs this other to work https://github.com/CartoDB/tangram.cartodb/pull/13

Add vector decision log and geometries count

---

src/cartodb.js
src/cdb.js

expose the superb geojson helpers @alonsogarciapablo cooked to use in https://github.com/CartoDB/cartodb
(omit last PR)

expose geojson helpers

---

package.json
src/geo/map/torque-layer.js
src/geo/torque-layer-view-base.js
test/spec/geo/map/torque-layer.spec.js
test/spec/geo/shared-tests-for-torque-layer.js
test/spec/geo/torque-layer-view-base.spec.js

re: https://github.com/CartoDB/cartodb/issues/12387
---
Cartodb PR: https://github.com/CartoDB/cartodb/pull/12482
Deep-insights.js PR: https://github.com/CartoDB/deep-insights.js/pull/561
Cartodb.js PR: https://github.com/CartoDB/cartodb.js/pull/1701
---

Move play / pause buttons to the side of animated time-series

---

src/dataviews/histogram-dataview-model.js
test/spec/dataviews/histogram-dataview-model.spec.js

This PR aims to fix https://github.com/CartoDB/cartodb/issues/12477 adding a property to hide nulls if they don't exist in the dataview model.

Has nulls property.

---

src/geo/ui/legends/categories/legend-template.tpl
src/geo/ui/legends/custom/legend-template.tpl
themes/scss/map/_overlays.scss

Related to: https://github.com/CartoDB/cartodb/issues/12619, https://github.com/CartoDB/cartodb.js/issues/1639
- Changed icon/color position in legend
- Resized legends icon to 12x12px

Change legend layout

---

src/dataviews/dataview-model-base.js
src/dataviews/helpers/histogram-helper.js
src/dataviews/histogram-dataview-model.js
src/dataviews/histogram-dataview/histogram-data-model.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/dataviews/helpers/histogram-helper.spec.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/dataviews/histogram-dataview/histogram-data-model.spec.js

Related to https://github.com/CartoDB/cartodb/issues/12618
Related PRs:
- cartodb https://github.com/CartoDB/cartodb/pull/12622
- deep-insights.js https://github.com/CartoDB/deep-insights.js/pull/577

hotfix: fix histograms data range change.

---

src/dataviews/histogram-dataview/histogram-data-model.js

Still in development 🐣 
Related to https://github.com/CartoDB/cartodb/issues/12480

Out of bounds filtering

---

src/geo/ui/legends/categories/legend-template.tpl
src/geo/ui/legends/categories/legend-view.js
src/geo/ui/legends/custom/legend-template.tpl
src/windshaft-integration/legends/rule-to-bubble-legend-adapter.js
src/windshaft-integration/legends/rule-to-category-legend-adapter.js
src/windshaft-integration/legends/rule-to-choropleth-legend-adapter.js
src/windshaft-integration/legends/rule.js
src/windshaft-integration/model-updater.js
test/spec/vis/model-updater.spec.js
test/spec/windshaft-integration/legends/rule-to-category-legend-adapter.spec.js
test/spec/windshaft-integration/model-updater.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/11630
Now the icons are shown in the category legend

Fix icons in category legends

---

src/geo/ui/legends/categories/legend-view.js
src/windshaft-integration/legends/rule-to-category-legend-adapter.js
test/spec/windshaft-integration/legends/rule-to-category-legend-adapter.spec.js

Related to: https://github.com/CartoDB/cartodb/issues/12683

Fix showing Others icon in the legend

---

src/geo/ui/legends/base/img-loader-view.js

Related to https://github.com/CartoDB/support/issues/974

Change color for rect in SVG icons

---

src/geo/leaflet/leaflet-layer-view-factory.js

Restore vector error log to see problems with vector rendering. (Temporal change).

Restore vector error log

---

src/dataviews/dataview-model-base.js

Temporary code to track in real usage if Dataviews' source is changed often (if ever) and in what circumstances.

Add tracking code

---

src/analysis/analysis-model.js
src/analysis/analysis-poller.js
src/dataviews/dataviews-collection.js
src/geo/map/cartodb-layer.js
src/geo/map/layers.js
src/vis/vis.js
test/spec/analysis/analysis-model.spec.js
test/spec/analysis/analysis-poller.spec.js
test/spec/geo/map/cartodb-layer.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/layers-serializer.spec.js

Reverts CartoDB/cartodb.js#1805

Revert "[WIP] Decouple Analysis Polling from AnalysisCollection"

---

examples/analysis_test.html
src/analysis/analysis-model.js
src/analysis/analysis-service.js
src/vis/vis.js
src/windshaft-integration/model-updater.js
src/windshaft/map-serializer/anonymous-map-serializer/analysis-serializer.js
test/spec/analysis/analysis-model.spec.js
test/spec/analysis/analysis-service.spec.js
test/spec/api/createVis/create-vis.spec.js
test/spec/dataviews/category-dataview-model.spec.js
test/spec/dataviews/dataview-model-base.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft-integration/model-updater.spec.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/analysis-serializer.spec.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/anonymous-map-serializer.spec.js

Related to: #1790
Publish analysis.findNodeById(id) using the static method findNodeById from the AnalysisService

Public findNodeById method using static AnalysisService method

---

src/vis/vis.js
src/windshaft-integration/model-updater.js
test/spec/api/createVis/create-vis.spec.js
test/spec/windshaft-integration/model-updater.spec.js

ModelUpdater doesn't depend on MapModel anymore

---

src/dataviews/dataview-model-base.js
test/spec/dataviews/histogram-dataview-model.spec.js
test/spec/vis/dataviews-tracker.spec.js

We haven't seen any errors in Track.js so we can assume BUILDER is not updating the `source` of dataview models. It doesn't make sense conceptually either so this PR ensures it's not possible to do so.

Dataview sources cannot be updated

---

src/vis/vis.js
src/windshaft-integration/model-updater.js
src/windshaft/error.js
src/windshaft/map-base.js
test/spec/api/createVis/create-vis.spec.js
test/spec/vis/vis.spec.js
test/spec/windshaft-integration/model-updater.spec.js
test/spec/windshaft/client.spec.js
test/spec/windshaft/map-base.spec.js

Part of https://github.com/CartoDB/cartodb.js/issues/1774
cc: @IagoLast

Decouple VisModel & ModelUpdater

---

src/geo/gmaps/gmaps-map-view.js
test/spec/geo/gmaps/gmaps-map-view.spec.js

Related to: https://github.com/CartoDB/support/issues/1069

Fix Gmaps boundig box not working

---

src/vis/infowindow-manager.js
test/spec/vis/infowindow-manager.spec.js

Related to: https://github.com/CartoDB/support/issues/988

Fix infowindow null values

---

src/analysis/analysis-model.js

https://github.com/CartoDB/camshaft/issues/334
----
This PR fixs a bug related to SQL functions with only one source.

Fix analysis-model when there are optional sources

---

src/engine.js
src/vis/vis.js
src/windshaft/client.js
src/windshaft/error-parser.js
test/spec/engine.spec.js
test/spec/vis/vis.spec.js

Refactor extract-engine branch

Re refactor

---

src/geo/gmaps/gmaps-cartodb-layer-group-view.js
src/geo/leaflet/leaflet-cartodb-layer-group-view.js

Related to: https://github.com/CartoDB/cartodb/issues/12593#issuecomment-338977986

Don't display error tiles for raster tiles

---

examples/v4/category-dataview.html
examples/v4/formula-dataview.html
examples/v4/index.html
src/api/v4/README.md
src/api/v4/dataview/base.js
src/api/v4/dataview/category.js
src/api/v4/dataview/formula.js
src/api/v4/dataview/index.js
src/api/v4/layer/layer.js
src/api/v4/source/dataset.js
src/api/v4/source/sql.js
src/dataviews/category-dataview-model.js
test/spec/api/v4/dataview/base.spec.js
test/spec/api/v4/dataview/category.spec.js
test/spec/api/v4/dataview/formula.spec.js
test/spec/dataviews/category-dataview-model.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1852
[WIP] Add maxCategories attribute

Add category dataview

---

src/api/v4/dataview/histogram/histogram-data.js
src/api/v4/dataview/histogram/index.js
src/api/v4/dataview/histogram/parse-histogram-data.js

This PR moves the HistogramData to its custom object so the `histogram-dataview` file is more readable.
Also adds a small code-refactoring issues.

Create HistogramData Object

---

examples/v4/histogram-dataview.html
src/api/v4/dataview/histogram/index.js

https://github.com/CartoDB/cartodb.js/issues/1884
----

Add Bounding Box filter support to v4 histogram dataview

---

examples/v4/basic.html
examples/v4/bounding-box-filter.html
examples/v4/bounding-box-leaflet-filter.html
examples/v4/category-dataview.html
examples/v4/formula-dataview.html
examples/v4/histogram-dataview.html
examples/v4/interactivity.html
src/api/v4/dataview/base.js
src/api/v4/filter/bounding-box-leaflet.js
src/api/v4/filter/bounding-box.js
src/api/v4/filter/index.js
src/windshaft/filters/bounding-box.js
test/spec/api/v4/dataview/base.spec.js
test/spec/api/v4/filter/bounding-box.spec.js

Related to: #1887
```js
var bboxFilter = new carto.filter.BoundingBox();
dataview.addFilter(bboxFilter);
bboxFilter.setBounds(bounds);
```
Example:

Add generic Bounding Box filter

---

examples/leaflet-namedmap.html
src/api/create-vis.js
src/geo/gmaps/gmaps-layer-view-factory.js
src/geo/gmaps/gmaps-layer-view.js
src/geo/gmaps/gmaps-torque-layer-view.js
src/geo/leaflet/leaflet-layer-view-factory.js
src/geo/leaflet/leaflet-layer-view.js
src/geo/leaflet/leaflet-torque-layer-view.js
src/geo/map-view-factory.js
src/geo/map-view.js
src/geo/torque-layer-view-base.js
src/vis/vis.js
test/spec/geo/gmaps/gmaps-torque-layer-view.spec.js
test/spec/geo/leaflet/leaflet-torque-layer-view.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1872
This PR depends on https://github.com/CartoDB/torque/pull/288

Add limits overlay to torque layers

---

grunt/tasks/_browserify-bundles.js
grunt/tasks/jasmine.js
package.json
src/api/v4/index.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1890

Remove Leaflet from the bundle

---

package.json

Update semver version
Fixes [#159](https://github.com/CartoDB/bug-bounty/issues/159)

Update semver version in package.json

---

src/api/v4/dataview/base.js
src/api/v4/dataview/category/index.js
src/api/v4/dataview/category/parse-data.js
src/api/v4/dataview/formula/index.js
src/api/v4/dataview/formula/parse-data.js
src/api/v4/dataview/histogram/index.js
src/api/v4/dataview/histogram/parse-data.js
src/api/v4/dataview/time-series/index.js
src/api/v4/dataview/time-series/parse-data.js
test/spec/api/v4/dataview/base.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1901
---

Add getSource to dataview.Base

---

examples/examples.json
examples/public/inmutable-source-style.html
examples/public/layer-errors.html
examples/public/mutable-source-style.html
src/api/v4/layer/layer.js
src/api/v4/source/sql.js
src/api/v4/style/base.js
src/api/v4/style/cartocss.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/layer/layer.spec.js
test/spec/api/v4/source/sql.spec.js
test/spec/api/v4/style/cartocss.spec.js

1907 async methods

---

src/api/v4/dataview/base.js
src/api/v4/dataview/category/index.js
src/api/v4/dataview/formula/index.js
src/api/v4/dataview/histogram/index.js
src/api/v4/dataview/time-series/index.js
test/spec/api/v4/dataview/base.spec.js
test/spec/api/v4/dataview/category.spec.js
test/spec/api/v4/dataview/formula.spec.js
test/spec/api/v4/dataview/histogram.spec.js
test/spec/api/v4/dataview/time-series.spec.js

https://github.com/CartoDB/cartodb.js/issues/1896
---

Remove internal listeners

---

src/geo/gmaps/gmaps-map-view.js
src/geo/leaflet/leaflet-map-view.js
test/spec/geo/geometry-views/shared-tests-for-path-views.js
test/spec/geo/gmaps/gmaps-map-view.spec.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1816
---
Implement the onReady function proposed here: https://github.com/CartoDB/cartodb.js/pull/1803, https://github.com/CartoDB/cartodb.js/pull/1813

Refactor gmaps fix

---

examples/public/dataviews/error-handling.html
src/api/v4/client.js
src/api/v4/dataview/base.js
src/api/v4/dataview/category/index.js
src/api/v4/dataview/formula/index.js
src/api/v4/dataview/histogram/index.js
src/api/v4/dataview/time-series/index.js
src/api/v4/error-handling/carto-error.js
src/api/v4/error-handling/carto-validation-error.js
src/api/v4/events.js
src/api/v4/filter/base.js
src/api/v4/filter/bounding-box-gmaps.js
src/api/v4/filter/bounding-box-leaflet.js
src/api/v4/filter/bounding-box.js
src/api/v4/layer/base.js
src/api/v4/layer/event-types.js
src/api/v4/layer/layer.js
src/api/v4/native/google-maps-map-type.js
src/api/v4/native/leaflet-layer.js
src/api/v4/native/trigger-layer-feature-event.js
src/api/v4/source/base.js
src/api/v4/source/dataset.js
src/api/v4/source/sql.js
src/api/v4/style/base.js

Fixes https://github.com/CartoDB/cartodb.js/issues/1961.

Review documentation of events

---

src/api/v4/index.js

This is done by webapack + UMD.

Dont expose carto on window (this is done by UMD)

---

package.json
src/api/v4/native/leaflet-layer.js
src/cartodb.js
src/geo/geometry-views/leaflet/point-view.js
src/geo/geometry-views/leaflet/polygon-view.js
src/geo/geometry-views/leaflet/polyline-view.js
src/geo/leaflet/leaflet-cartodb-layer-group-view.js
src/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.js
src/geo/leaflet/leaflet-map-view.js
src/geo/leaflet/leaflet-plain-layer-view.js
src/geo/leaflet/leaflet-tiled-layer-view.js
src/geo/leaflet/leaflet-wms-layer-view.js
src/geo/map.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/native/leaflet-layer.spec.js
test/spec/cartodb.mod.torque.spec.js
test/spec/geo/leaflet/leaflet-cartodb-layer-group-view.spec.js
test/spec/geo/leaflet/leaflet-cartodb-webgl-layer-group-view.spec.js
test/spec/geo/leaflet/leaflet-map-view.spec.js
webpack/webpack.config.js
webpack/webpack.min.config.js

Related to: https://github.com/CartoDB/cartodb.js/issues/1974
This PR fixes:
- Leaflet was required before Carto.js in the browser
- Leaflet was required using Carto.js in node

Use window leaflet

---

src/index.js

Add polyfills

---

src/dataviews/helpers/histogram-helper.js

Related to https://github.com/CartoDB/support/issues/1071
----

Add support to decades in time series

---

test/spec/geo/gmaps/gmaps-cartodb-layer-group.spec.js
test/spec/geo/leaflet/leaflet-cartodb-layer-group-view.spec.js
test/spec/geo/shared-tests-for-carto-layer-group.js

https://github.com/CartoDB/cartodb.js/issues/1984
---
- Implement pending tests
- Remove duplication in tests

1984-refactor-tests

---

src/api/v4/client.js
src/api/v4/error-handling/error-list/validation-errors.js
src/api/v4/layer/base.js
src/api/v4/layer/layer.js
test/spec/api/v4/client.spec.js
test/spec/api/v4/layer/layer.spec.js

https://github.com/CartoDB/cartodb.js/issues/2000
--- 
Pending documentation update.

2000 allow custom IDs in layers

---

examples/public/layers/layer-with-zoom-options-gmaps.html
examples/public/layers/layer-with-zoom-options-leaflet.html
src/api/v4/layer/layer.js
src/windshaft/map-serializer/anonymous-map-serializer/layers-serializer.js
test/spec/windshaft/map-serializer/anonymous-map-serializer/layers-serializer.spec.js

2002 add layer zoom options

---

src/geo/geocoder.js
src/geo/ui/search.js
test/SpecRunner.html
test/spec/geo/geocoder.spec.js
test/spec/geo/ui/search.spec.js

https://github.com/CartoDB/cartodb-management/issues/5067
---
The real change is [here](https://github.com/CartoDB/cartodb.js/compare/mapbox-geocoder-editor?expand=1#diff-e6adbee5b72a26c50f89655d03a61461R177)

Add MAPBOX geocoder (v3)

---

CHANGELOG.md
DEVLOG.md
package.json

2011 autogenerate changelog

---

examples/public/layers/change-source-gmaps.html
examples/public/layers/change-source-leaflet.html
examples/public/layers/change-style-gmaps.html
examples/public/layers/change-style-leaflet.html
examples/public/misc/edit-sql-cartocss-gmaps.html
examples/public/misc/edit-sql-cartocss-leaflet.html
examples/public/misc/error-handling-gmaps.html
examples/public/misc/error-handling-leaflet.html
examples/public/misc/legends-gmaps.html
examples/public/misc/legends-leaflet.html

Related to: https://github.com/CartoDB/documentation/issues/87 -> https://github.com/CartoDB/cartodb.js/issues/2035
- Fixed change-source examples labels
- Updated change-style examples labels
- Update legends examples: add dynamic interactivity
- Add style to error-handling examples

Examples feedback

---

src/api/v4/error-handling/carto-error-extender.js
src/api/v4/error-handling/error-list/validation-errors.js
src/api/v4/layer/aggregation.js
src/api/v4/layer/layer.js
test/spec/api/v4/error-handling/carto-error-extender.spec.js
test/spec/api/v4/layer/aggregation.spec.js
test/spec/api/v4/layer/layer.spec.js

Related to #2032 
----
This PR does:
- Make `placement` optional.
- Validate that interactivity columns are present in `aggregation` columns to avoid a runtime error.

Server aggregation tweaks

---

package.json

re: https://github.com/CartoDB/support/issues/894
- carto: https://github.com/CartoDB/carto/pull/47
- torque: https://github.com/CartoDB/torque/pull/293
- carto.js: https://github.com/CartoDB/cartodb.js/pull/2060
- cartodb: https://github.com/CartoDB/cartodb/pull/13612

prepare shield-placement-keyword CartoCSS property

---

src/geo/ui/legends/legends-view.js
themes/scss/map/_overlays.scss

Related to: https://github.com/CartoDB/cartodb/issues/13635
CartoDB PR: https://github.com/CartoDB/cartodb/pull/13640

Suppress horizontal scroll in legends. Fixes IE11

---

docs/guides/02-upgrade-considerations.md

Explaining that the auth system behaves the same way regardless the version of the library.

add tip about authorization system

---

src/geo/ui/legends/layer-legends-template.tpl
themes/scss/map/_overlays.scss

Required for https://github.com/CartoDB/cartodb/pull/13824

Minor adjustments to legends style

---

src/api/v4/error-handling/carto-error.js
src/api/v4/error-handling/error-list/windshaft-errors.js
src/windshaft/error.js
test/spec/api/v4/error-handling/carto-error.spec.js
test/spec/windshaft/error.spec.js

Related to https://github.com/CartoDB/cartodb.js/issues/2045
----
Adapt to the possible errors from Auth API that can happen in CARTO.js v4 public API.

Adapt to Auth API errors

---

package.json
src/geo/gmaps/gmaps-cartodb-layer-group-view.js
src/geo/leaflet/leaflet-cartodb-layer-group-view.js

Related issue https://github.com/CartoDB/cartodb-platform/issues/4314

Ugrade zera to fix fractional zoom levels

---

package.json
themes/scss/map/_overlays.scss

https://github.com/CartoDB/support/issues/1510
---
[![https://gyazo.com/454f2401bd77f70c0d400ef8263420ef](https://i.gyazo.com/454f2401bd77f70c0d400ef8263420ef.gif)](https://gyazo.com/454f2401bd77f70c0d400ef8263420ef)

Fix layer legends margin

---

src/geo/cartodb-layer-group.js
test/spec/geo/cartodb-layer-group.spec.js

Send empty string when url can not be build

---

examples/gmaps/gmaps_heatmap_plus_sql_api.html
examples/gmaps_heatmap_plus_sql_api.html
examples/tutorial-google-heatmap-2.html
examples/tutorial-google-heatmap.html
examples/tutorials/tutorial-google-heatmap-2.html
examples/tutorials/tutorial-google-heatmap.html
grunt/tasks/jasmine.js
src/geo/ui/fullscreen.js
src/vis/vis.js
test/SpecRunner-src.html
test/SpecRunner.html
vendor/wax.cartodb.js

Related to https://github.com/CartoDB/carto.js/issues/2138

Fix hide bug in cartodb.js v3

---

README.md

Closes https://github.com/CartoDB/carto.js/issues/2129

Fixes Getting Started links

---

src/geo/ui/legends/choropleth/legend-template.tpl
themes/scss/map/_overlays.scss

| ![selection_185](https://user-images.githubusercontent.com/2227572/42310722-70519822-803c-11e8-8a12-6e0f4fda3511.png) | ![selection_184](https://user-images.githubusercontent.com/2227572/42310740-77d4414e-803c-11e8-9ad0-8b21e55aca36.png) |
|---|---|
| ![selection_186](https://user-images.githubusercontent.com/2227572/42310758-81ecefdc-803c-11e8-80a8-61b326fa8aec.png) | ![selection_187](https://user-images.githubusercontent.com/2227572/42310768-8775c3fc-803c-11e8-896c-a7ee5e84b908.png) |

Fix gradient legends margin

---

RELEASING.md
bower.json
package.json
src/cartodb.js
src/geo/gmaps/gmaps_cartodb_layergroup.js

Related to https://github.com/CartoDB/carto.js/issues/2147

Fix load and loading events in v3

---

.hound.yml
.scss-lint.yml
Gemfile

Does this one solve that issue: https://github.com/CartoDB/carto.js/issues/1909?

Remove Gemfile (compass)

---

test/spec/windshaft/client.spec.js

Tried to refactor tests to avoid conflicts with real Ajax calls in another spec.
No results so specs are ignored. Pending a real refactor of integration tests.

Refactor and ignore tests

---

docs/support/02-support-options.md
docs/support/03-contribute.md

Add v3 support docs

---

src/dataviews/helpers/histogram-helper.js
src/dataviews/histogram-dataview-model.js
test/spec/dataviews/helpers/histogram-helper.js

Fixes:
https://github.com/CartoDB/support/issues/1871
Useful comments found in an older closed issue:
https://github.com/CartoDB/carto.js/issues/926

Fix wrong bound selection in histogram last bucket

---

CHANGELOG.md

Just adding changes on #2211 and #2212 to changelog

Add missing unreleased changes to changelog

---

src/api/v4/constants.js
test/spec/api/v4/client.spec.js

`https://carto.com/attribution` -> `https://carto.com/about-carto/`

Change attribution URL to about CARTO

---

CHANGELOG_INTERNAL.md
package.json
src/geo/ui/infowindow-view.js
test/spec/geo/ui/infowindow-view.spec.js

Fix wrong position when several features of different layers overlap, and that was causing a race-condition when setting template & content for the popup

Fix popup wrong position

---

CHANGELOG.md
package-lock.json
package.json
scripts/package.public.json

I've already made a 4.2.2 release from this branch

Replace git protocol with https
